### ISSUE TITLE
Use of OpenSSL is GPL-incompatible

### ISSUE THREAD

**Issue by EionRobb** [majn/telegram-purple#1]
This plugin uses OpenSSL of which there is no GPL-exception for in the libpurple GPL license.  Consider switching to using the SSL functions built into libpurple or use an alternatively library such as PolarSSL

**Comment by Croydon** [comment]
As mentioned here: https://github.com/majn/telegram-purple/issues/52#issuecomment-126689684
the OpenSSL license is going to change to Apache v2

**Comment by majn** [comment]
Now that libtgl is ported thanks to ben and the whole thing is tested and merged into the master, I think we can finally get rid of this annoying issue :)
