### ISSUE TITLE
Pidgin crashes very frequently when connected to Telegram

### ISSUE THREAD

**Issue by Sesivany** [majn/telegram-purple#106]
Pidgin recently started crashing so often that it's pretty much impossible to use it for Telegram. I'm not sure what triggers it, Pidgin crashes even when it's on the background not being used actively. It crashes right after start very frequently.

Here is one of a backtrace ABRT collected  for me after one of the crashes:

{   "signal": 6
,   "executable": "/usr/bin/pidgin"
,   "only_crash_thread": true
,   "stacktrace":
      [ {   "crash_thread": true
        ,   "frames":
              [ {   "address": 225068665288
                ,   "build_id_offset": 215496
                ,   "function_name": "raise"
                ,   "file_name": "/usr/lib64/libc-2.21.so"
                }
              , {   "address": 225068672602
                ,   "build_id": "b15dd696048bfbba1f1a9c089ce8c56932392c18"
                ,   "build_id_offset": 222810
                ,   "function_name": "abort"
                ,   "file_name": "/usr/lib64/libc-2.21.so"
                }
              , {   "address": 225068634503
                ,   "build_id": "b15dd696048bfbba1f1a9c089ce8c56932392c18"
                ,   "build_id_offset": 184711
                ,   "function_name": "__assert_fail_base"
                ,   "file_name": "/usr/lib64/libc-2.21.so"
                }
              , {   "address": 225068634674
                ,   "build_id": "b15dd696048bfbba1f1a9c089ce8c56932392c18"
                ,   "build_id_offset": 184882
                ,   "file_name": "/usr/lib64/libc-2.21.so"
                }
              , {   "address": 139815873301622
                ,   "build_id": "0475592214df07bdca50fcca2777eeb3d29d7b67"
                ,   "build_id_offset": 617590
                ,   "file_name": "/usr/lib64/purple-2/telegram-purple.so"
                }
              , {   "address": 139815873301670
                ,   "build_id": "0475592214df07bdca50fcca2777eeb3d29d7b67"
                ,   "build_id_offset": 617638
                ,   "function_name": "tglm_message_alloc"
                ,   "file_name": "/usr/lib64/purple-2/telegram-purple.so"
                }
              , {   "address": 139815873314859
                ,   "build_id": "0475592214df07bdca50fcca2777eeb3d29d7b67"
                ,   "build_id_offset": 630827
                ,   "function_name": "tglf_fetch_alloc_message"
                ,   "file_name": "/usr/lib64/purple-2/telegram-purple.so"
                }
              , {   "address": 139815873361136
                ,   "build_id": "0475592214df07bdca50fcca2777eeb3d29d7b67"
                ,   "build_id_offset": 677104
                ,   "function_name": "tglu_work_update"
                ,   "file_name": "/usr/lib64/purple-2/telegram-purple.so"
                }
              , {   "address": 139815873365810
                ,   "build_id": "0475592214df07bdca50fcca2777eeb3d29d7b67"
                ,   "build_id_offset": 681778
                ,   "function_name": "tglu_work_updates"
                ,   "file_name": "/usr/lib64/purple-2/telegram-purple.so"
                }
              , {   "address": 139815873196780
                ,   "build_id": "0475592214df07bdca50fcca2777eeb3d29d7b67"
                ,   "build_id_offset": 512748
                ,   "function_name": "rpc_execute_answer"
                ,   "file_name": "/usr/lib64/purple-2/telegram-purple.so"
                }
              , {   "address": 139815873201431
                ,   "build_id": "0475592214df07bdca50fcca2777eeb3d29d7b67"
                ,   "build_id_offset": 517399
                ,   "function_name": "rpc_execute"
                ,   "file_name": "/usr/lib64/purple-2/telegram-purple.so"
                }
              , {   "address": 139815873107360
                ,   "build_id": "0475592214df07bdca50fcca2777eeb3d29d7b67"
                ,   "build_id_offset": 423328
                ,   "function_name": "conn_try_read"
                ,   "file_name": "/usr/lib64/purple-2/telegram-purple.so"
                }
              , {   "address": 4624942
                ,   "build_id": "97949ba9d8c746ec8b303badd7541ba9831293cb"
                ,   "build_id_offset": 430638
                ,   "function_name": "pidgin_io_invoke"
                ,   "file_name": "/usr/bin/pidgin"
                }
              , {   "address": 225110694538
                ,   "build_id": "7c936c01704440a7500d25147101437483bf8624"
                ,   "build_id_offset": 301706
                ,   "function_name": "g_main_context_dispatch"
                ,   "file_name": "/usr/lib64/libglib-2.0.so.0.4400.1"
                }
              , {   "address": 225110695456
                ,   "build_id": "7c936c01704440a7500d25147101437483bf8624"
                ,   "build_id_offset": 302624
                ,   "function_name": "g_main_context_iterate.isra.29"
                ,   "file_name": "/usr/lib64/libglib-2.0.so.0.4400.1"
                }
              , {   "address": 225110696258
                ,   "build_id": "7c936c01704440a7500d25147101437483bf8624"
                ,   "build_id_offset": 303426
                ,   "function_name": "g_main_loop_run"
                ,   "file_name": "/usr/lib64/libglib-2.0.so.0.4400.1"
                }
              , {   "address": 251519061815
                ,   "build_id": "1290da723674791fe8d7768578038080bba8e49e"
                ,   "build_id_offset": 1330999
                ,   "function_name": "gtk_main"
                ,   "file_name": "/usr/lib64/libgtk-x11-2.0.so.0.2400.28"
                }
              , {   "address": 4397337
                ,   "build_id": "97949ba9d8c746ec8b303badd7541ba9831293cb"
                ,   "build_id_offset": 203033
                ,   "function_name": "main"
                ,   "file_name": "/usr/bin/pidgin"
                } ]
        } ]
}

I'm using the 1.0.0 version packaged in Copr: https://copr.fedoraproject.org/coprs/lsof/telegram-purple/

**Comment by majn** [comment]
Check out current master should be fixed.

**Comment by mandree** [comment]
For me, master f10b683fc9c6c9202c5f0c2910f3e7efe938e1c2 crashes frequently when secret messages are involved. I haven't been able to capture a useful backtrace yet though.

**Comment by majn** [comment]
Closing duplicate
