### ISSUE TITLE
Stickers don't show up in chats when used with conversation colors plugin

### ISSUE THREAD

**Issue by ShinzJr** [majn/telegram-purple#108]
I can receive stickers, but the sticker doesn't show up in chats

**Comment by majn** [comment]
What do you mean bis "can receive"?

**Comment by ShinzJr** [comment]
i received blank 
![screenshot from 2015-09-01 15 16 47](https://cloud.githubusercontent.com/assets/7479638/9599257/922478fa-50bc-11e5-97cc-5f39d8629686.png)

**Comment by ShinzJr** [comment]
stickers show up as blank when the conversation colors plugin is active
![screenshot from 2015-09-01 16 13 54](https://cloud.githubusercontent.com/assets/7479638/9600321/bea1ee28-50c4-11e5-8cf6-f76dd45728e5.png)
![screenshot from 2015-09-01 16 15 10](https://cloud.githubusercontent.com/assets/7479638/9600323/bec9c13c-50c4-11e5-9a77-f61adba52579.png)

**Comment by majn** [comment]
There's an option in Conversationcolors called "ignore incoming format" which will strip any HTML formatting from incoming messages and swallow the <img>-Tags too. https://github.com/rosedu/Pidgin/blob/master/pidgin/plugins/convcolors.c#L140
