### ISSUE TITLE
The rpm package don't build correct debug packages.

### ISSUE THREAD

**Issue by tuxmaster** [majn/telegram-purple#109]
Because of wrong file permissions in in the install section on the spec file, the debug package is always empty.
See the patch for the solution:
diff -Nur purple-telegram-1.2.0.org/rpm/purple-telegram.spec purple-telegram-1.2.0/rpm/purple-telegram.spec
--- purple-telegram-1.2.0.org/rpm/purple-telegram.spec  2015-08-31 11:25:21.202416417 +0200
+++ purple-telegram-1.2.0/rpm/purple-telegram.spec      2015-08-31 11:40:32.326400494 +0200
@@ -1,6 +1,6 @@
 Name:          purple-telegram
 Version:       1.2.0
-Release:       1%{?dist}
+Release:       2%{?dist}
 Summary:       Adds support for Telegram to Pidgin, Adium, Finch and other Libpurple based messengers.
 Group:         Internet/Messaging
 License:       GPLv2+
@@ -21,6 +21,7 @@
 
 %install
 %make_install
+chmod 755 %{buildroot}/%{_libdir}/purple-2/telegram-purple.so
 
 %files
 %doc
@@ -31,3 +32,5 @@
 %{_datadir}/pixmaps/pidgin/protocols/48/telegram.png
 
 %changelog
+* Mon Aug 31 2015 Frank <frank@familie-büttner.de> 1.2.0-2

**Comment by majn** [comment]
Included it, thanks
