### ISSUE TITLE
Pidgin crashes when a message sent

### ISSUE THREAD

**Issue by Sesivany** [majn/telegram-purple#113]
Sometimes (not very often, once in a few days) when I send a message, Pidgin crashes. The message still gets sent, so Pidgin crashes right after that. I haven't found any pattern what kind of message can trigger that. The backtrace is:

{   "signal": 6
,   "executable": "/usr/bin/pidgin"
,   "stacktrace":
      [ {   "crash_thread": true
        ,   "frames":
              [ {   "address": 267011705496
                ,   "build_id": "5b6342ea1dbd25b194e8cb60e7b0133466598b24"
                ,   "build_id_offset": 215704
                ,   "function_name": "raise"
                ,   "file_name": "/lib64/libc.so.6"
                }
              , {   "address": 267011712810
                ,   "build_id": "5b6342ea1dbd25b194e8cb60e7b0133466598b24"
                ,   "build_id_offset": 223018
                ,   "function_name": "abort"
                ,   "file_name": "/lib64/libc.so.6"
                }
              , {   "address": 267011674695
                ,   "build_id": "5b6342ea1dbd25b194e8cb60e7b0133466598b24"
                ,   "build_id_offset": 184903
                ,   "function_name": "__assert_fail_base"
                ,   "file_name": "/lib64/libc.so.6"
                }
              , {   "address": 267011674866
                ,   "build_id": "5b6342ea1dbd25b194e8cb60e7b0133466598b24"
                ,   "build_id_offset": 185074
                ,   "file_name": "/lib64/libc.so.6"
                }
              , {   "address": 140177654547417
                ,   "build_id": "0475592214df07bdca50fcca2777eeb3d29d7b67"
                ,   "build_id_offset": 549849
                ,   "function_name": "tglq_query_result"
                ,   "file_name": "/usr/lib64/purple-2/telegram-purple.so"
                }
              , {   "address": 140177654514967
                ,   "build_id": "0475592214df07bdca50fcca2777eeb3d29d7b67"
                ,   "build_id_offset": 517399
                ,   "function_name": "rpc_execute"
                ,   "file_name": "/usr/lib64/purple-2/telegram-purple.so"
                }
              , {   "address": 140177654420896
                ,   "build_id": "0475592214df07bdca50fcca2777eeb3d29d7b67"
                ,   "build_id_offset": 423328
                ,   "function_name": "conn_try_read"
                ,   "file_name": "/usr/lib64/purple-2/telegram-purple.so"
                }
              , {   "address": 4624942
                ,   "build_id": "97949ba9d8c746ec8b303badd7541ba9831293cb"
                ,   "build_id_offset": 430638
                ,   "function_name": "pidgin_io_invoke"
                ,   "file_name": "/usr/bin/pidgin"
                }
              , {   "address": 272961411722
                ,   "build_id": "7c936c01704440a7500d25147101437483bf8624"
                ,   "build_id_offset": 301706
                ,   "function_name": "g_main_context_dispatch"
                ,   "file_name": "/lib64/libglib-2.0.so.0"
                }
              , {   "address": 272961412640
                ,   "build_id": "7c936c01704440a7500d25147101437483bf8624"
                ,   "build_id_offset": 302624
                ,   "function_name": "g_main_context_iterate.isra.29"
                ,   "file_name": "/lib64/libglib-2.0.so.0"
                }
              , {   "address": 272961413442
                ,   "build_id": "7c936c01704440a7500d25147101437483bf8624"
                ,   "build_id_offset": 303426
                ,   "function_name": "g_main_loop_run"
                ,   "file_name": "/lib64/libglib-2.0.so.0"
                }
              , {   "address": 220187610935
                ,   "build_id": "1290da723674791fe8d7768578038080bba8e49e"
                ,   "build_id_offset": 1330999
                ,   "function_name": "gtk_main"
                ,   "file_name": "/lib64/libgtk-x11-2.0.so.0"
                }
              , {   "address": 4397337
                ,   "build_id": "97949ba9d8c746ec8b303badd7541ba9831293cb"
                ,   "build_id_offset": 203033
                ,   "function_name": "main"
                ,   "file_name": "/usr/bin/pidgin"
                } ]
        }
      , {   "frames":
              [ {   "address": 267012499053
                ,   "build_id": "5b6342ea1dbd25b194e8cb60e7b0133466598b24"
                ,   "build_id_offset": 1009261
                ,   "function_name": "poll"
                ,   "file_name": "/lib64/libc.so.6"
                }
              , {   "address": 272961412540
                ,   "build_id": "7c936c01704440a7500d25147101437483bf8624"
                ,   "build_id_offset": 302524
                ,   "function_name": "g_main_context_iterate.isra.29"
                ,   "file_name": "/lib64/libglib-2.0.so.0"
                }
              , {   "address": 272961413442
                ,   "build_id": "7c936c01704440a7500d25147101437483bf8624"
                ,   "build_id_offset": 303426
                ,   "function_name": "g_main_loop_run"
                ,   "file_name": "/lib64/libglib-2.0.so.0"
                }
              , {   "address": 270950856342
                ,   "build_id": "e9a8673bb7b333b564c5ce800ee82affcf44d1ac"
                ,   "build_id_offset": 915094
                ,   "function_name": "gdbus_shared_thread_func"
                ,   "file_name": "/lib64/libgio-2.0.so.0"
                }
              , {   "address": 272961573029
                ,   "build_id": "7c936c01704440a7500d25147101437483bf8624"
                ,   "build_id_offset": 463013
                ,   "function_name": "g_thread_proxy"
                ,   "file_name": "/lib64/libglib-2.0.so.0"
                }
              , {   "address": 267007325525
                ,   "build_id": "d515e7040be962bd98df45bbd27f5b80518dff25"
                ,   "build_id_offset": 30037
                ,   "function_name": "start_thread"
                ,   "file_name": "/lib64/libpthread.so.0"
                }
              , {   "address": 267012546365
                ,   "build_id": "5b6342ea1dbd25b194e8cb60e7b0133466598b24"
                ,   "build_id_offset": 1056573
                ,   "function_name": "__clone"
                ,   "file_name": "/lib64/libc.so.6"
                } ]
        }
      , {   "frames":
              [ {   "address": 267012499053
                ,   "build_id": "5b6342ea1dbd25b194e8cb60e7b0133466598b24"
                ,   "build_id_offset": 1009261
                ,   "function_name": "poll"
                ,   "file_name": "/lib64/libc.so.6"
                }
              , {   "address": 272961412540
                ,   "build_id": "7c936c01704440a7500d25147101437483bf8624"
                ,   "build_id_offset": 302524
                ,   "function_name": "g_main_context_iterate.isra.29"
                ,   "file_name": "/lib64/libglib-2.0.so.0"
                }
              , {   "address": 272961412812
                ,   "build_id": "7c936c01704440a7500d25147101437483bf8624"
                ,   "build_id_offset": 302796
                ,   "function_name": "g_main_context_iteration"
                ,   "file_name": "/lib64/libglib-2.0.so.0"
                }
              , {   "address": 272961412873
                ,   "build_id": "7c936c01704440a7500d25147101437483bf8624"
                ,   "build_id_offset": 302857
                ,   "function_name": "glib_worker_main"
                ,   "file_name": "/lib64/libglib-2.0.so.0"
                }
              , {   "address": 272961573029
                ,   "build_id": "7c936c01704440a7500d25147101437483bf8624"
                ,   "build_id_offset": 463013
                ,   "function_name": "g_thread_proxy"
                ,   "file_name": "/lib64/libglib-2.0.so.0"
                }
              , {   "address": 267007325525
                ,   "build_id": "d515e7040be962bd98df45bbd27f5b80518dff25"
                ,   "build_id_offset": 30037
                ,   "function_name": "start_thread"
                ,   "file_name": "/lib64/libpthread.so.0"
                }
              , {   "address": 267012546365
                ,   "build_id": "5b6342ea1dbd25b194e8cb60e7b0133466598b24"
                ,   "build_id_offset": 1056573
                ,   "function_name": "__clone"
                ,   "file_name": "/lib64/libc.so.6"
                } ]
        } ]
}

I can also provide a codedump if necessary (it has >200MB).
I'm using Pidgin 2.10.11 and telegram-purple beta 3 in Fedora 22.

**Comment by majn** [comment]
Sending the core dumb won't be necessary, but can you please try to get some additional inform from the coredump?

    dnf install pidgin-debuginfo

    gdb pidgin ./coredump
    run
    bt full

Then try to find the frame number of "tglq_query_result" and print the local variables.

    frame <frame-number-of-tglq_query_result>
    info locals

If that doens't work, please just the full backtrace.

**Comment by Sesivany** [comment]
I'm posting the full backtrace:
#0  0x0000003e2b234a98 in __GI___libc_sigaction (sig=3487, act=0xd9f, oact=0x6) at ../sysdeps/unix/sysv/linux/x86_64/sigaction.c:54
        result = <optimized out>
        kact = 
              {k_sa_handler = 0x5, sa_flags = 267012029278, sa_restorer = 0x7f7d00000000, sa_mask = {__val = {0, 24834120, 267012529185, 18446744073709551615, 0, 48162608, 140177605095424, 140177656220856, 394, 140177656233168, 27513216, 140177675506916, 267011712810, 32, 0, 0}}}
        koact = {k_sa_handler = 0x0, sa_flags = 0, sa_restorer = 0x0, sa_mask = {__val = {0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 140724629847056, 22971274, 140724629847136, 47244640288, 140177605095424, 140177656220856}}}
#1  0x0000000001a3d180 in  ()
#2  0x00007f7da88dd4e4 in  () at /usr/lib64/purple-2/telegram-purple.so
#3  0x0000003e2b283e9c in __GI___libc_free (ptr=0x7f7da7678cc8, str=0x3e2b38a808 "munmap_chunk(): invalid pointer", action=-1537511424) at malloc.c:4973
        buf = "мg\247}\177\000\000G\322\"+>\000\000\000"
        cp = <optimized out>
        p = 0x7f7da7678cb8
        size = <optimized out>
        block = <optimized out>
        total_size = <optimized out>
        ar_ptr = <optimized out>
        p = 0x7f7da7678cb8
        hook = <optimized out>
#4  0x0000003e2b283e9c in __GI___libc_free (p=0x7f7da7678cb8) at malloc.c:2823
        p = 0x7f7da7678cb8
        size = <optimized out>
        block = <optimized out>
        total_size = <optimized out>
        ar_ptr = <optimized out>
        p = 0x7f7da7678cb8
        hook = <optimized out>
#5  0x0000003e2b283e9c in __GI___libc_free (mem=0x7f7da7678cc8) at malloc.c:2948
        ar_ptr = <optimized out>
        p = 0x7f7da7678cb8
        hook = <optimized out>
#6  0x0000003e2b22d2f2 in iscntrl (c=3487) at ctype.c:28
#7  0x0000000001a3d180 in  ()
#8  0x0000000002d46aa0 in  ()
#9  0x00007f7db1270030 in  ()
#10 0x00007f7db1270038 in  ()
#11 0x0000000000000000 in  ()

Here is a crash report in ABRT: https://retrace.fedoraproject.org/faf/reports/726722/ Apparently, I was experiencing the crash already a month ago, so it's not something new introduced with beta 3.

**Comment by majn** [comment]
This crashing on outgoing messages was already fixed in a hotfix for 1.2.2, closing now to clean up.
