### ISSUE TITLE
Segmentation fault in tgp_msg_send_done()

### ISSUE THREAD

**Issue by LPoppe** [majn/telegram-purple#115]
Hi,

A segmentation fault occasionally occurs in tgp_msg_send_done(). Although it happens fairly often, I've yet to figure out a pattern. I've tested this on two machines  (Ubuntu 15.04, latest git revision) and both seem to behave the same. So anyway, here's the trace from gdb:

```
(21:12:40) pidgin-libnotify: Sender: (XXXXXXXX) ID (im:prpl-telegram:%2BXXXXXXXX:XXXXXXXX) 
(21:12:40) pidgin-libnotify: notify(), new: title: 'Linda', body: 'ok :P', buddy: 'XXXXXXXX'
(21:12:40) pidgin-libnotify: notify(), has a buddy icon.
(21:12:40) pidgin-libnotify: Conversation Updated (TYPING)
(21:12:40) pidgin-libnotify: Conversation Updated (UNSEEN)
(21:12:40) pidgin-libnotify: Conversation Updated (OTHER)
(21:12:40) prpl-telegram: sending notifications: 1
(21:12:40) prpl-telegram: send all pending ack
(21:12:40) prpl-telegram: tgl_do_mark_read (XXXXXXXX)
(21:12:40) blist: Updating buddy status for XXXXXXXX (Telegram)
(21:12:40) Gdk: gdk_window_set_icon_list: icons too large
(21:12:40) prpl-telegram: Hole in pts (pts = 185558, count = 1, cur_pts = 185556)
[New Thread 0x7fffc9323700 (LWP 5999)]
[New Thread 0x7fffdb4e9700 (LWP 5947)]
[New Thread 0x7fffea267700 (LWP 5946)]
[New Thread 0x7fffeaa68700 (LWP 5945)]

Program received signal SIGSEGV, Segmentation fault.
tgp_msg_send_done (TLS=0x555555bbc790, callback_extra=0x0, success=1, M=0x0) at tgp-msg.c:149
149	  } else if (tgl_get_peer_type(M->to_id) == TGL_PEER_ENCR_CHAT) {
(gdb) 
```

So clearly, it crashes while dereferencing M which is NULL. The thing is: I don't think I sent a message while it crashed (which explains why M is NULL). I'm not sure why `tgp_msg_send_done()` would be called then, though..

The following diff seems to fix it:

```diff
diff --git a/tgp-msg.c b/tgp-msg.c
index 3691788..e12f5fe 100644
--- a/tgp-msg.c
+++ b/tgp-msg.c
@@ -146,7 +146,7 @@ static void tgp_msg_send_done (struct tgl_state *TLS, void *callback_extra, int
     warning (err);
     tgp_msg_err_out (TLS, err, M->to_id);
     g_free (err);
-  } else if (tgl_get_peer_type(M->to_id) == TGL_PEER_ENCR_CHAT) {
+  } else if (M != NULL && tgl_get_peer_type(M->to_id) == TGL_PEER_ENCR_CHAT) {
     debug ("SUCCESS write_secret_chat_file ...");
     write_secret_chat_file (TLS);
   }
```

This doesn't strike me as a particularly good solution, as M might (or might not?) still be null in the lines above (in the !success block). Thoughts?

**Comment by majn** [comment]
That error never happened to me. I can easily fix the segfault, but it would be interesting to know why that callback is executed while not sending a message. If it happens again or you still got the core-file, can you try to get the full function trace? 

Simply use "bt" when in gdb and the crash happened.

**Comment by BenWiederhake** [comment]
Ran into the same bug. Here's a "bt full": http://pastebin.com/zgLrzywi (I hope this doesn't contain any sensitive information!)

**Comment by LPoppe** [comment]
@BenWiederhake Are you using OTR (https://otr.cypherpunks.ca/) by any chance?

**Comment by BenWiederhake** [comment]
The plugin is installed, but is completely inactive in the moment. At the time of fault, I did receive an incoming message via Telegram; it was not especially encrypted or anything, just a bog-standard line of text.

As the crash seems to boil down to `queries.c#778`, I assume there is something race-condition-y going on. However, I don't understand anything of tgl at all, this is just a wild guess after 10 minutes of digging into the code.

**Comment by LPoppe** [comment]
Logs from most recent crash:

http://pastebin.com/raw.php?i=8qi80gj6
http://pastebin.com/raw.php?i=0kv4RKB6

**Comment by majn** [comment]
Fixed the symptons 66a1536d4b66e67a36fde6f56f6be9a6a13d868d probably going to report this one upstream.

**Comment by BenWiederhake** [comment]
Had another crash *without the Pidgin OTR plugin*, so these are definitely not correlated.
Log: http://pastebin.com/JWhzmZSp

**Comment by majn** [comment]
Did you guys test the patch yet?

**Comment by BenWiederhake** [comment]
All crashes I reported before this line are for the tag "v1.2.0-beta3" (sorry for not updating right away).

I just updated to 66a1536d4b66e67a36fde6f56f6be9a6a13d868d (current master). Let's see if it works.

**Comment by LPoppe** [comment]
Seems to be fixed for me :). Thanks!
