### ISSUE TITLE
Pidgin sends XML entities and HTML markup

### ISSUE THREAD

**Issue by 0nse** [majn/telegram-purple#12]
Pidgin will send HTML markup which won't be parsed by mobile Telegram clients on iOS and Android. Given the following message:
```HTML
<&
>"
```
It will be displayed as:
```XML
&lt;&amp;<br>&gt;&quot;
```
Strangely, the predefined apostrophe entity `'` won't be escaped as `&apos;`.

**Comment by Lazek** [comment]
Yes, confirmed in web version and Telegram Desktop.

And after send text:

Text

Text

In Telegram Desktop:
Text<br>Text

**Comment by Lazek** [comment]
Ops..

Text< br >Text

without spaces.

**Comment by franciscod** [comment]
@Lazek you can try to escape the `<br>`s with this (ignore the `\`s)
```
\```
 <br>
\```
```

**Comment by psamim** [comment]
I am not sure if it is related or not, but when I send a message in Persian language which is a RTL language, Pidgin sends the below HTML markup which is not parsed by the mobile clients; so HTML tags are shown as is.
```html
<SPAN style="direction:rtl;text-align:right;">سلام</SPAN>
```
Therefore the plugin is not usable in Persian at all as all messages are sent as HTML markups.

**Comment by majn** [comment]
Should be fixed now.

@psamim Can you confirm if Persian is usable now? I just copy-pasted سلام into the text field and there was no html markup in the message anymore.

**Comment by psamim** [comment]
@majn Thanks! Yes it seems that there is no html markup anymore.

**Comment by aia832003** [comment]
Not sure if this is related as I've just moved to Telegram, and using the purple protocol on Fedora Linux, but I'm seeing the apostrophe (&apos;) occasionally when using contractions like "can't". It seems to only happen with the first instance of using an apostrophe in the chat session though.  For instance, if I open a chat session and use "can't" in the first message I see the html markup for the apostrophe, but if I follow with other messages with "won't" it shows the text correctly.
