### ISSUE TITLE
Chats don't seem to use usernames in display.

### ISSUE THREAD

**Issue by BenWiederhake** [majn/telegram-purple#121]
I can identify myself using something different than my user ID "1156..."

Ideally, one should see the same handle ("$Firstname $Lastname"?) as when using web.telegram.org.

**Comment by tuxmaster** [comment]
Can you look at  #120.
It looks like it is the same as yours.

**Comment by majn** [comment]
Do you use 1.2.1?

**Comment by BenWiederhake** [comment]
@majn: Sorry, I was still using 66a1536d4b66e67a36fde6f56f6be9a6a13d868d, and this issue was already fixed in 644416aa89a5aaccfdc41acc865ecfec19318257 .

@tuxmaster: No, this doesn't look similar.

But there is no 1.2.1 tag?

**Comment by majn** [comment]
@BenWiederhake I usually add a tag once I add the release zip, but I didn't have time to build the Adium bundle yet. Its done now.
