### ISSUE TITLE
All new messages have a date stamp

### ISSUE THREAD

**Issue by BenWiederhake** [majn/telegram-purple#123]
It looks like:

    (26.09.2015 13:42:16) A: something
    (26.09.2015 13:43:31) B: something else
    (26.09.2015 13:43:49) A: Whatever

It should look like:

    (26.09.2015 13:42:16) A: something
    (13:43:31) B: something else
    (13:43:49) A: Whatever

This is how all other protocols work, so it should adhere to that.

**Comment by majn** [comment]
Works for me, what pidgin version do you run?

**Comment by BenWiederhake** [comment]
Still happening.

Steps to reproduce (why didn't I write this earlier?):

- Close pidgin completely
- Talk with someone using a different client
- Open pidgin. All previous messages are fetched and are stamped with a full date-time-stamp

**Comment by EionRobb** [comment]
Pidgin will display historic messages with a date

**Comment by BenWiederhake** [comment]
Can't this be disabled/prevented in some way?

**Comment by EionRobb** [comment]
You could try using the Messaging Timestamps plugin to customise what you're seeing (but not in the way you want), but Pidgin has the following code in gtkconv.c:
```
	/* Show the date on the first message in a new day, or if the message is
	 * older than 20 minutes. */
	show_date = (mtime >= gtkconv->newday) || (time(NULL) > mtime + 20*60);
```
The only way to override this is with a UI plugin.

**Comment by BenWiederhake** [comment]
Dangit. Ohh well, at least I know. Thanks for explaining.
