### ISSUE TITLE
Port to windows one day?

### ISSUE THREAD

**Issue by BenWiederhake** [majn/telegram-purple#128]
Just to keep track of the most obvious issues involved when porting to windows:

- using `<unistd.h>` and `<fctnl.h>` is portable across Unices, but no further. Should have used `<stdio.h>` instead.
- The case configuration path contains "+49176...". NTFS doesn't allow `+` in paths, I believe. Pidgin logs are stored in a "%29176..." folder, I think this should be viable for telegram-purple itself, too.
- Don't rely on /dev/urandom (and stop treating /dev/random like it's a better source! >_<)

**Comment by majn** [comment]
https://github.com/majn/telegram-purple/issues/52

**Comment by BenWiederhake** [comment]
Because it should be recorded here, I copied this post https://github.com/majn/telegram-purple/pull/149#issuecomment-150338190

- headers are fine (mingw probably spoof those)
- paths are fine on NTFS (dafuq?)
- /dev/urandom ... uhh ...
