### ISSUE TITLE
pre-1.2.2 errors build

### ISSUE THREAD

**Issue by SergeyDjam** [majn/telegram-purple#138]
telegram-purple-1.2.2]$ make
make -C tgl
make[1]: вход в каталог «/home/admin/rpmbuild/BUILD/telegram-purple-1.2.2/tgl»
cat scheme.tl encrypted_scheme.tl binlog.tl mtproto.tl append.tl > auto/scheme.tl
gcc -I. -I. -O2 -Wa,--compress-debug-sections -gdwarf-4 -fvar-tracking-assignments -frecord-gcc-switches -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -ffat-lto-objects -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 -fPIC -I/usr/include/libpurple -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -DHAVE_CONFIG_H -DENABLE_NLS -DLOCALEDIR='"/usr/share/locale"' -Wall -Wextra -Wno-deprecated-declarations -Wno-unused-parameter -I. -I. -fno-strict-aliasing -fPIC  -I/usr/local/include -I/usr/include -I/usr/include  -DHAVE_CONFIG_H -Wall -Wextra -Werror -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -iquote ./tl-parser -c -MP -MD -MF dep/tl-parser.d -MQ objs/tl-parser.o -o objs/tl-parser.o tl-parser/tl-parser.c
gcc -I. -I. -O2 -Wa,--compress-debug-sections -gdwarf-4 -fvar-tracking-assignments -frecord-gcc-switches -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -ffat-lto-objects -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 -fPIC -I/usr/include/libpurple -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -DHAVE_CONFIG_H -DENABLE_NLS -DLOCALEDIR='"/usr/share/locale"' -Wall -Wextra -Wno-deprecated-declarations -Wno-unused-parameter -I. -I. -fno-strict-aliasing -fPIC  -I/usr/local/include -I/usr/include -I/usr/include  -DHAVE_CONFIG_H -Wall -Wextra -Werror -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -iquote ./tl-parser -c -MP -MD -MF dep/tlc.d -MQ objs/tlc.o -o objs/tlc.o tl-parser/tlc.c
make[1]: *** Нет правила для сборки цели «tl-parser/crc32.c», требуемой для «objs/crc32.o».  Останов.
make[1]: выход из каталога «/home/admin/rpmbuild/BUILD/telegram-purple-1.2.2/tgl»
Makefile:59: ошибка выполнения рецепта для цели «tgl/libs/libtgl.a»
make: *** [tgl/libs/libtgl.a] Ошибка 2

**Comment by SergeyDjam** [comment]
tgl]$ make
make: *** Нет правила для сборки цели «tl-parser/crc32.c», требуемой для «objs/crc32.o».  Останов.

**Comment by SergeyDjam** [comment]
cat Makefile.tl-parser 
TL_PARSER_OBJECTS=${OBJ}/tl-parser.o ${OBJ}/tlc.o ${OBJ}/crc32.o

${TL_PARSER_OBJECTS}: ${OBJ}/%.o: ${srcdir}/tl-parser/%.c | create_dirs
        ${CC} ${INCLUDE} ${COMPILE_FLAGS} -iquote ${srcdir}/tl-parser -c -MP -MD -MF ${DEP}/$*.d -MQ ${OBJ}/$*.o -o $@ $<

${EXE}/tl-parser: ${TL_PARSER_OBJECTS}
        ${CC} $^ ${LINK_FLAGS} -o $@

**Comment by majn** [comment]
what does git status say? 

    export LANG=en
    git status
    cd tgl
    git status

**Comment by SergeyDjam** [comment]
this packet download as .zip

**Comment by majn** [comment]
Unfortunately you cannot use the github tarballs, since github doesn't include the source of the submodules. If you want to download tag v1.2.2 you need to clone it recursively to do:

      git clone --recursive -b v1.2.2 https://github.com/majn/telegram-purple

**Comment by SergeyDjam** [comment]
i download packages
https://github.com/vysheng/tl-parser/archive/master.zip
https://github.com/majn/tgl/archive/master.zip
https://github.com/majn/telegram-purple/archive/v1.2.2.tar.gz 

git clone in rpm package what?

**Comment by majn** [comment]
The package is just called "git", so probably

   yum install git

**Comment by SergeyDjam** [comment]
no-no, i am build rpm package from ROSA Fresh. In .spec d'nt worked git

**Comment by SergeyDjam** [comment]
my spec:

%global         oname telegram-purple

Name:           pidgin-plugin-telegram
Version:        1.2.2
Release:        1
Summary:        Telegram protocol plugin for libpurple
Group:          Networking/Instant messaging
License:        GPLv2+
URL:            https://github.com/majn/telegram-purple
#Source0:       https://codeload.github.com/majn/telegram-purple/tar.gz/v{version}.tar.gz
Source0:        %{oname}-%{version}.tar.gz
Source1:        tgl-master.zip
Source2:        tl-parser-master.zip
BuildRequires:  pkgconfig(openssl)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(purple)
BuildRequires:  pkgconfig(libwebp)
Requires:       openssl
Requires:       pidgin
Requires:       %{_lib}webp4

%description
Telegram-purple is a Libpurple plugin that adds
support for the Telegram messenger

%prep
%setup -q -n %{oname}-%{version}
find . -type  f \( -name "*.c" -or -name "*.h" \)|xargs chmod -x 2>/dev/null
rm -rf telegram-adium
unzip -qq -jo %{SOURCE1} -d $RPM_BUILD_DIR/%{oname}-%{version}/tgl
unzip -qq -jo %{SOURCE2} -d $RPM_BUILD_DIR/%{oname}-%{version}/tgl/tl-parser

%build
%configure --disable-openssl
%make

%install
%make_install

%files
%doc README.md
%{_libdir}/purple-2/telegram-purple.so
%{_sysconfdir}/telegram-purple/*
%{_datadir}/pixmaps/pidgin/protocols/16/telegram.png
%{_datadir}/pixmaps/pidgin/protocols/22/telegram.png
%{_datadir}/pixmaps/pidgin/protocols/48/telegram.png

%changelog

**Comment by majn** [comment]
I'll look at it later

**Comment by majn** [comment]
FIY, the 1.2.2pre-release tag is only for translation anyway, if you don't need it for translation you probably don't want to package it anyway.

**Comment by SergeyDjam** [comment]
oh, i think 1.2.2pre is new... Ok. Translate this and package later

**Comment by majn** [comment]
FIY: I deleted the tag to avoid further confusion.
