### ISSUE TITLE
Beta4 compile fails on tgl doing the link process.

### ISSUE THREAD

**Issue by tuxmaster** [majn/telegram-purple#142]
It fails on F21,F22,F23 with:
gcc objs/tl-parser.o objs/tlc.o -Wl,-z,relro  -L/usr/lib -L/usr/lib -lpurple -lglib-2.0  -lwebp -lz -lgcrypt -lrt  -rdynamic -ggdb -L/usr/local/lib -L/usr/lib -L/usr/lib  -rdynamic -ggdb -lz -lgcrypt    -o bin/tl-parser
objs/tl-parser.o: In function `tl_count_combinator_name':
/builddir/build/BUILD/purple-telegram-1.2.1/tgl/tl-parser/tl-parser.c:1409: undefined reference to `compute_crc32'
collect2: error: ld returned 1 exit status
Makefile.tl-parser:7: recipe for target 'bin/tl-parser' failed
make[1]: *** [bin/tl-parser] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/builddir/build/BUILD/purple-telegram-1.2.1/tgl'
Makefile:59: recipe for target 'tgl/libs/libtgl.a' failed
make: *** [tgl/libs/libtgl.a] Error 2

packages used for build:
DEBUG util.py:393:  ============================================================================================================================================================================
DEBUG util.py:393:   Package                                              Arch                            Version                                         Repository                       Size
DEBUG util.py:393:  ============================================================================================================================================================================
DEBUG util.py:393:  Installing:
DEBUG util.py:393:   gettext                                              x86_64                          0.19.6-1.fc23                                   fedora                          1.0 M
DEBUG util.py:393:   libgcrypt-devel                                      x86_64                          1.6.4-1.fc23                                    fedora                          139 k
DEBUG util.py:393:   libpurple-devel                                      x86_64                          2.10.11-14.fc23                                 fedora                          210 k
DEBUG util.py:393:   libwebp-devel                                        x86_64                          0.4.3-3.fc23                                    fedora                           32 k
DEBUG util.py:393:   zlib-devel                                           x86_64                          1.2.8-9.fc23                                    fedora                           55 k
DEBUG util.py:393:  Installing for dependencies:
DEBUG util.py:393:   acl                                                  x86_64                          2.2.52-10.fc23                                  fedora                           77 k
DEBUG util.py:393:   alsa-lib                                             x86_64                          1.0.29-2.fc23                                   fedora                          388 k
DEBUG util.py:393:   avahi-glib                                           x86_64                          0.6.31-43.fc23                                  fedora                           15 k
DEBUG util.py:393:   avahi-libs                                           x86_64                          0.6.31-43.fc23                                  fedora                           61 k
DEBUG util.py:393:   cairo                                                x86_64                          1.14.2-2.fc23                                   fedora                          720 k
DEBUG util.py:393:   cdparanoia-libs                                      x86_64                          10.2-20.fc23                                    fedora                           57 k
DEBUG util.py:393:   cryptsetup-libs                                      x86_64                          1.6.8-2.fc23                                    fedora                          210 k
DEBUG util.py:393:   cyrus-sasl-md5                                       x86_64                          2.1.26-25.2.fc23                                fedora                           61 k
DEBUG util.py:393:   cyrus-sasl-plain                                     x86_64                          2.1.26-25.2.fc23                                fedora                           43 k
DEBUG util.py:393:   cyrus-sasl-scram                                     x86_64                          2.1.26-25.2.fc23                                fedora                           47 k
DEBUG util.py:393:   dbus                                                 x86_64                          1:1.10.0-1.fc23                                 fedora                          246 k
DEBUG util.py:393:   dbus-devel                                           x86_64                          1:1.10.0-1.fc23                                 fedora                           59 k
DEBUG util.py:393:   dbus-glib                                            x86_64                          0.104-3.fc23                                    fedora                          121 k
DEBUG util.py:393:   dbus-glib-devel                                      x86_64                          0.104-3.fc23                                    fedora                           76 k
DEBUG util.py:393:   dbus-libs                                            x86_64                          1:1.10.0-1.fc23                                 fedora                          173 k
DEBUG util.py:393:   device-mapper                                        x86_64                          1.02.107-1.fc23                                 fedora                          289 k
DEBUG util.py:393:   device-mapper-libs                                   x86_64                          1.02.107-1.fc23                                 fedora                          344 k
DEBUG util.py:393:   farstream02                                          x86_64                          0.2.7-2.fc23                                    fedora                          242 k
DEBUG util.py:393:   flac-libs                                            x86_64                          1.3.1-5.fc23                                    fedora                          216 k
DEBUG util.py:393:   fontconfig                                           x86_64                          2.11.94-4.fc23                                  fedora                          241 k
DEBUG util.py:393:   fontpackages-filesystem                              noarch                          1.44-14.fc23                                    fedora                           15 k
DEBUG util.py:393:   freetype                                             x86_64                          2.6.0-3.fc23                                    fedora                          410 k
DEBUG util.py:393:   gdk-pixbuf2                                          x86_64                          2.32.1-1.fc23                                   fedora                          443 k
DEBUG util.py:393:   gettext-libs                                         x86_64                          0.19.6-1.fc23                                   fedora                          484 k
DEBUG util.py:393:   glib-networking                                      x86_64                          2.46.0-1.fc23                                   fedora                          133 k
DEBUG util.py:393:   glib2-devel                                          x86_64                          2.46.0-1.fc23                                   fedora                          436 k
DEBUG util.py:393:   graphite2                                            x86_64                          1.2.4-5.fc23                                    fedora                           89 k
DEBUG util.py:393:   gsettings-desktop-schemas                            x86_64                          3.18.0-1.fc23                                   fedora                          520 k
DEBUG util.py:393:   gsm                                                  x86_64                          1.0.13-13.fc23                                  fedora                           34 k
DEBUG util.py:393:   gssdp                                                x86_64                          0.14.11-2.fc23                                  fedora                           53 k
DEBUG util.py:393:   gstreamer1                                           x86_64                          1.6.0-2.fc23                                    fedora                          1.1 M
DEBUG util.py:393:   gstreamer1-plugins-bad-free                          x86_64                          1.6.0-1.fc23                                    fedora                          1.7 M
DEBUG util.py:393:   gstreamer1-plugins-base                              x86_64                          1.6.0-1.fc23                                    fedora                          1.3 M
DEBUG util.py:393:   gstreamer1-plugins-good                              x86_64                          1.6.0-1.fc23                                    fedora                          2.0 M
DEBUG util.py:393:   gupnp                                                x86_64                          0.20.14-3.fc23                                  fedora                           98 k
DEBUG util.py:393:   gupnp-igd                                            x86_64                          0.2.3-5.fc23                                    fedora                           33 k
DEBUG util.py:393:   harfbuzz                                             x86_64                          1.0.4-1.fc23                                    fedora                          175 k
DEBUG util.py:393:   hwdata                                               noarch                          0.281-1.fc23                                    fedora                          1.4 M
DEBUG util.py:393:   iptables                                             x86_64                          1.4.21-15.fc23                                  fedora                          426 k
DEBUG util.py:393:   iso-codes                                            noarch                          3.62-1.fc23                                     fedora                          3.0 M
DEBUG util.py:393:   json-c                                               x86_64                          0.12-6.fc23                                     fedora                           29 k
DEBUG util.py:393:   kmod                                                 x86_64                          21-3.fc23                                       fedora                          112 k
DEBUG util.py:393:   kmod-libs                                            x86_64                          21-3.fc23                                       fedora                           61 k
DEBUG util.py:393:   libICE                                               x86_64                          1.0.9-3.fc23                                    fedora                           70 k
DEBUG util.py:393:   libSM                                                x86_64                          1.2.2-3.fc23                                    fedora                           43 k
DEBUG util.py:393:   libX11                                               x86_64                          1.6.3-2.fc23                                    fedora                          608 k
DEBUG util.py:393:   libX11-common                                        noarch                          1.6.3-2.fc23                                    fedora                          166 k
DEBUG util.py:393:   libXau                                               x86_64                          1.0.8-5.fc23                                    fedora                           33 k
DEBUG util.py:393:   libXdamage                                           x86_64                          1.1.4-7.fc23                                    fedora                           25 k
DEBUG util.py:393:   libXext                                              x86_64                          1.3.3-3.fc23                                    fedora                           42 k
DEBUG util.py:393:   libXfixes                                            x86_64                          5.0.1-5.fc23                                    fedora                           22 k
DEBUG util.py:393:   libXft                                               x86_64                          2.3.2-3.fc23                                    fedora                           63 k
DEBUG util.py:393:   libXi                                                x86_64                          1.7.4-3.fc23                                    fedora                           43 k
DEBUG util.py:393:   libXrender                                           x86_64                          0.9.9-2.fc23                                    fedora                           30 k
DEBUG util.py:393:   libXtst                                              x86_64                          1.2.2-5.fc23                                    fedora                           24 k
DEBUG util.py:393:   libXv                                                x86_64                          1.0.10-3.fc23                                   fedora                           22 k
DEBUG util.py:393:   libXxf86vm                                           x86_64                          1.1.4-2.fc23                                    fedora                           22 k
DEBUG util.py:393:   libasyncns                                           x86_64                          0.8-9.fc23                                      fedora                           31 k
DEBUG util.py:393:   libavc1394                                           x86_64                          0.5.3-18.fc23                                   fedora                           55 k
DEBUG util.py:393:   libcroco                                             x86_64                          0.6.8-7.fc23                                    fedora                          107 k
DEBUG util.py:393:   libdatrie                                            x86_64                          0.2.8-6.fc23                                    fedora                           31 k
DEBUG util.py:393:   libdrm                                               x86_64                          2.4.65-1.fc23                                   fedora                          140 k
DEBUG util.py:393:   libdv                                                x86_64                          1.0.0-20.fc23                                   fedora                           83 k
DEBUG util.py:393:   libdvdnav                                            x86_64                          5.0.3-2.fc23                                    fedora                           59 k
DEBUG util.py:393:   libdvdread                                           x86_64                          5.0.2-2.fc23                                    fedora                           94 k
DEBUG util.py:393:   libgadu                                              x86_64                          1.12.1-2.fc23                                   fedora                          107 k
DEBUG util.py:393:   libgpg-error-devel                                   x86_64                          1.20-1.fc23                                     fedora                           43 k
DEBUG util.py:393:   libgudev                                             x86_64                          230-2.fc23                                      fedora                           31 k
DEBUG util.py:393:   libiec61883                                          x86_64                          1.2.0-13.fc23                                   fedora                           41 k
DEBUG util.py:393:   libjpeg-turbo                                        x86_64                          1.4.1-2.fc23                                    fedora                          147 k
DEBUG util.py:393:   libmnl                                               x86_64                          1.0.3-10.fc23                                   fedora                           28 k
DEBUG util.py:393:   libmodman                                            x86_64                          2.0.1-11.fc23                                   fedora                           33 k
DEBUG util.py:393:   libnetfilter_conntrack                               x86_64                          1.0.4-5.fc23                                    fedora                           56 k
DEBUG util.py:393:   libnfnetlink                                         x86_64                          1.0.1-7.fc23                                    fedora                           30 k
DEBUG util.py:393:   libnice                                              x86_64                          0.1.13-2.fc23                                   fedora                          172 k
DEBUG util.py:393:   libnice-gstreamer1                                   x86_64                          0.1.13-2.fc23                                   fedora                           21 k
DEBUG util.py:393:   libogg                                               x86_64                          2:1.3.2-4.fc23                                  fedora                           28 k
DEBUG util.py:393:   libpciaccess                                         x86_64                          0.13.4-2.fc23                                   fedora                           30 k
DEBUG util.py:393:   libpng                                               x86_64                          2:1.6.17-2.fc23                                 fedora                          119 k
DEBUG util.py:393:   libproxy                                             x86_64                          0.4.11-12.fc23                                  fedora                           69 k
DEBUG util.py:393:   libpurple                                            x86_64                          2.10.11-14.fc23                                 fedora                          5.8 M
DEBUG util.py:393:   libraw1394                                           x86_64                          2.1.0-6.fc23                                    fedora                           68 k
DEBUG util.py:393:   librsvg2                                             x86_64                          2.40.10-1.fc23                                  fedora                          132 k
DEBUG util.py:393:   libshout                                             x86_64                          2.2.2-13.fc23                                   fedora                           47 k
DEBUG util.py:393:   libsilc                                              x86_64                          1.1.10-14.fc23                                  fedora                          531 k
DEBUG util.py:393:   libsndfile                                           x86_64                          1.0.25-16.fc23                                  fedora                          155 k
DEBUG util.py:393:   libsoup                                              x86_64                          2.52.0-1.fc23                                   fedora                          384 k
DEBUG util.py:393:   libsrtp                                              x86_64                          1.5.0-3.fc23                                    fedora                          329 k
DEBUG util.py:393:   libthai                                              x86_64                          0.1.21-2.fc23                                   fedora                          192 k
DEBUG util.py:393:   libtheora                                            x86_64                          1:1.1.1-13.fc23                                 fedora                          191 k
DEBUG util.py:393:   libusbx                                              x86_64                          1.0.20-1.fc23                                   fedora                           66 k
DEBUG util.py:393:   libv4l                                               x86_64                          1.6.2-3.fc23                                    fedora                          172 k
DEBUG util.py:393:   libvdpau                                             x86_64                          1.1.1-2.fc23                                    fedora                           37 k
DEBUG util.py:393:   libvisual                                            x86_64                          1:0.4.0-18.fc23                                 fedora                          141 k
DEBUG util.py:393:   libvorbis                                            x86_64                          1:1.3.4-5.fc23                                  fedora                          191 k
DEBUG util.py:393:   libvpx                                               x86_64                          1.4.0-5.fc23                                    fedora                          618 k
DEBUG util.py:393:   libwayland-client                                    x86_64                          1.9.0-1.fc23                                    fedora                           32 k
DEBUG util.py:393:   libwayland-server                                    x86_64                          1.9.0-1.fc23                                    fedora                           37 k
DEBUG util.py:393:   libwebp                                              x86_64                          0.4.3-3.fc23                                    fedora                          225 k
DEBUG util.py:393:   libxcb                                               x86_64                          1.11-8.fc23                                     fedora                          192 k
DEBUG util.py:393:   libxkbcommon                                         x86_64                          0.5.0-2.fc23                                    fedora                          112 k
DEBUG util.py:393:   libxshmfence                                         x86_64                          1.2-2.fc23                                      fedora                           11 k
DEBUG util.py:393:   meanwhile                                            x86_64                          1.1.0-18.fc23                                   fedora                           98 k
DEBUG util.py:393:   mesa-libEGL                                          x86_64                          11.0.3-1.20151012.fc23                          fedora                           99 k
DEBUG util.py:393:   mesa-libGL                                           x86_64                          11.0.3-1.20151012.fc23                          fedora                          193 k
DEBUG util.py:393:   mesa-libgbm                                          x86_64                          11.0.3-1.20151012.fc23                          fedora                           56 k
DEBUG util.py:393:   mesa-libglapi                                        x86_64                          11.0.3-1.20151012.fc23                          fedora                           62 k
DEBUG util.py:393:   opus                                                 x86_64                          1.1.1-0.3.beta.fc23                             fedora                          181 k
DEBUG util.py:393:   orc                                                  x86_64                          0.4.24-1.fc23                                   fedora                          170 k
DEBUG util.py:393:   pango                                                x86_64                          1.38.0-1.fc23                                   fedora                          281 k
DEBUG util.py:393:   pixman                                               x86_64                          0.33.2-1.fc23                                   fedora                          255 k
DEBUG util.py:393:   protobuf                                             x86_64                          2.6.1-2.fc23                                    fedora                          371 k
DEBUG util.py:393:   protobuf-c                                           x86_64                          1.1.1-2.fc23                                    fedora                          108 k
DEBUG util.py:393:   protobuf-compiler                                    x86_64                          2.6.1-2.fc23                                    fedora                          306 k
DEBUG util.py:393:   pulseaudio-libs                                      x86_64                          7.0-1.fc23                                      fedora                          586 k
DEBUG util.py:393:   python                                               x86_64                          2.7.10-8.fc23                                   fedora                           94 k
DEBUG util.py:393:   python-libs                                          x86_64                          2.7.10-8.fc23                                   fedora                          5.8 M
DEBUG util.py:393:   python-pip                                           noarch                          7.1.0-1.fc23                                    fedora                          1.5 M
DEBUG util.py:393:   python-setuptools                                    noarch                          18.0.1-2.fc23                                   fedora                          425 k
DEBUG util.py:393:   python3-dbus                                         x86_64                          1.2.0-8.fc23                                    fedora                          124 k
DEBUG util.py:393:   qrencode-libs                                        x86_64                          3.4.2-5.fc23                                    fedora                           55 k
DEBUG util.py:393:   soundtouch                                           x86_64                          1.4.0-13.fc23                                   fedora                           58 k
DEBUG util.py:393:   speex                                                x86_64                          1.2-0.24.rc2.fc23                               fedora                           66 k
DEBUG util.py:393:   systemd                                              x86_64                          222-7.fc23                                      fedora                          6.3 M
DEBUG util.py:393:   taglib                                               x86_64                          1.9.1-10.fc23                                   fedora                          314 k
DEBUG util.py:393:   tcp_wrappers-libs                                    x86_64                          7.6-81.fc23                                     fedora                           71 k
DEBUG util.py:393:   wavpack                                              x86_64                          4.70.0-5.fc23                                   fedora                          147 k
DEBUG util.py:393:   xkeyboard-config                                     noarch                          2.15-2.fc23                                     fedora                          760 k
DEBUG util.py:393:   xml-common                                           noarch                          0.6.3-43.fc23                                   fedora                           31 k
DEBUG util.py:393:   zvbi-fonts                                           noarch                          0.2.33-19.fc23                                  fedora                          120 k

**Comment by BenWiederhake** [comment]
That is (if at all!) a bug in the build system, which is incomplete anyway. Please run `make clean && git submodule update --recursive && ./configure -q && make -j4` to rebuild.

Note that the `--recursive` argument to git-submodule is very important: It cares about actually checking out the things onto your disk.

If it still fails, please send us the output of the following two commands:

    git status
    git rev-parse HEAD

Thanks!

**Comment by tuxmaster** [comment]
Yes:
submodule update --recursive was it :(
