### ISSUE TITLE
Show name of author of forwarded message

### ISSUE THREAD

**Issue by imustafin** [majn/telegram-purple#144]
Currently, only the name of the user who forwarded the message is shown.

It would be great to at least prepend the original author's name to the forwarded message.

**Comment by pcworld** [comment]
Or at least indicate that the message is a quote at all. This can be quite confusing currently.

**Comment by BenWiederhake** [comment]
Closing this, as 1.3.0 should do this for forwards and responses.  If there are any issues, please open a new issue.

**Comment by majn** [comment]
It doesn't work in all cases yet, sometimes there is no way to get the name of the forwarder, in that case it will be omitted.

**Comment by BenWiederhake** [comment]
Ah, right.  Let me spell it out so that I don't forget it again:
If the final receiver doesn't "know" the original author, then there's no way to resolve the user ID (due to lack of an accesstoken).

**Comment by BenWiederhake** [comment]
This is already implemented in [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
Of course, Pull Requests are still very much welcome!

(In case you're wondering: tdlib-purple just displays "Unknown user" in that scenario.)
