### ISSUE TITLE
No read-receipts for system messages

### ISSUE THREAD

**Issue by BenWiederhake** [majn/telegram-purple#147]
Steps to reproduce:
- Be in a chatroom
- Someone leaves
- See that message (and *only* that message in pidgin)

Expected result: Telegram thinks I *have* read that message.

Actual result: Telegram thinks I have **not** read that message.

![proofno-read-receipt](https://cloud.githubusercontent.com/assets/2690845/10616123/d69709da-7763-11e5-9039-71c80a93bad0.png)

**Comment by majn** [comment]
Fixed in test branch
