### ISSUE TITLE
Something something double free

### ISSUE THREAD

**Issue by BenWiederhake** [majn/telegram-purple#148]
Sigh.

    (22:21:41) prpl-telegram: tgprpl_close()
    *** Error in `pidgin': double free or corruption (!prev): 0x00005562d491f4e0 ***
    Aborted

**Comment by majn** [comment]
beta4?

**Comment by BenWiederhake** [comment]
Yup.

**Comment by majn** [comment]
Fixed, apparently libtgl changed how tgl_free_all works in test branch, which now frees the passed pointer to TLS too.
