### ISSUE TITLE
Crash on name change

### ISSUE THREAD

**Issue by BenWiederhake** [majn/telegram-purple#150]
(affects only development version)

When I changed my name in the web version, telegram-purple crashed.

	(16:39:47) prpl-telegram: update 0xa7332b73 (check=0)
	pidgin: tgp-blist.c:37: tgp_blist_peer_add_purple_name:
	 Zusicherung »g_hash_table_lookup (tg_get_data (TLS)->id_to_purple_name,
	 ((gpointer) (glong) (tgl_get_peer_id (id)))) == ((void *)0)« nicht erfüllt.
	(16:39:50) prpl-telegram: update 0xa7332b73 (check=0)
	Aborted

I guess this has to do with the new name handling, since I changed my "addressbook name".

**Comment by BenWiederhake** [comment]
Just verified with a friend: This doesn't affect master

**Comment by majn** [comment]
Fixed in test branch
