### ISSUE TITLE
Support entities in messages

### ISSUE THREAD

**Issue by 0nse** [majn/telegram-purple#153]
Since Telegram [implemented bots](https://core.telegram.org/bots) basic markdown has also been supported. Bots can send `**bold** and _italic_ text, as well as use [links](http://ddg.gg) or use backticks for code snippets`.

Both, the official Android and Web client (Webogram) can display it. As Pidgin supports HTML-formatted messages, it could be considered, whether Pidgin should also visualise markdown syntax.

Moreover, it would be fantastic to be able to send markdown syntax that is interpreted. Currently, when using backticks in Webogram, the receiver will see text in a typewriter font. However, doing the same with telegram-purple will show the text  surrounded with backticks. Thus, it seems that the conversion happens client side.

**Comment by 0nse** [comment]
I accidentally linked to the wrong page. The [API description](https://core.telegram.org/bots/api#using-markdown)  explains that for sending markdown formatted messages, the `parse_mode` parameter has to be set to `Markdown` in `sendMessage`.

**Comment by powerman** [comment]
Here is support implemented in web.telegram.org: https://github.com/zhukov/webogram/blob/master/app/js/lib/ng_utils.js#L1819

See also https://github.com/telegramdesktop/tdesktop/issues/2847

Right now only three backquotes works when sending from Pidgin, and even these doesn't work when placed on their own lines (to surround multiline text in clean manner), only if they placed right before/after text on same line. And no formatting works when receiving messages in Pidgin. :(

**Comment by BenWiederhake** [comment]
This is already implemented in [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
Of course, Pull Requests are still very much welcome!
