### ISSUE TITLE
Gettext optional

### ISSUE THREAD

**Issue by majn** [majn/telegram-purple#155]
To allow compiling without gettext in case someone doesn't want a translation

**Comment by EionRobb** [comment]
Or at the very least, it would be great if the path to msgfmt could be configured

**Comment by BenWiederhake** [comment]
Fixed in 1.3.0.  (I forgot to mention this issue in the commit message.)

When invoking `./configure`, simply use the flag `--disable-translation`, like this: https://travis-ci.org/majn/telegram-purple/jobs/150904023
