### ISSUE TITLE
Wishlist: git state in compiled plugin

### ISSUE THREAD

**Issue by BenWiederhake** [majn/telegram-purple#164]
When troubleshooting, it's nice to know the exact version of the plugin that was faulty. Ideally, we would have the following info:

- Version (e.g. "1.2.2")
- Git commit (e.g. 18a4d51b9462c48e993fbc6393425b513bc86011 in dev)
- Git commit of submodules
- whether there are any changed files (and, ideally, which ones)

Next, where to display this information? Obviously, the user is only interested in the "1.2.2" part, so this should be visible only on explicit request. I suggest "/version", "/versionfull", or both.

Is that an okay idea?

If so, I already know how to do this: phony target in Makefile that generates a small .c file, which provides a string constant. This would guarantee to be regenerated with every single build, is 100% reproducible (which is interesting for other purposes), and has virtually no overhead.

**Comment by EionRobb** [comment]
I think pidgin does it with a -D in the Makefile that pulls through the current hg revision. You can view all the version information in pidgin through Help->Build Information (so no custom slash-command is necessary)

**Comment by BenWiederhake** [comment]
That one doesn't work, but if you meant "Help -> Plugin-Info" then, yeah, here we can find

	Telegram
		Author: Matthias Jentsch <mtthsjntsch@gmail.com>, Vitaly Valtman, Christopher Althaus <althaus.christopher@gmail.com>, Markus Endres <endresma45241@th-nuernberg.de>. Based on libtgl by Vitaly Valtman.
		Version: 1.2.2 libtgl: 2.1.0
		Website: https://github.com/majn/telegram-purple
		ID String: prpl-telegram
		Loadable: Yes
		Loaded: Yes

However, that doesn't contain the git commit, which would be interesting when people clone the dev branch and we don't know which commit they saw when they did. Also, it doesn't allow me to quadruple-check whether I really *really* **really** ***really*** am running and testing the exact version combination I intended to.

A -D doesn't guarantee a rebuild on every make invokation. For that, you need a phony target. And if you have that, then you can just as well pipe `git status; git rev-parse HEAD; git submodule status` or similar into a file (via xxd) and call it a string.

**Comment by majn** [comment]
I think the only way to solve this in a proper way (without having to needlessly rebuild things) is using git hooks

**Comment by BenWiederhake** [comment]
Why? I literally wrote up a way how to do it so that only one very small c file is recompiled every time, and linking is lightning fast anyway.

**Comment by majn** [comment]
Don't bother I already found a clean way.

**Comment by majn** [comment]
Sorry if you already had effort :(

**Comment by majn** [comment]
In case you are interested: https://github.com/majn/telegram-purple/commit/7d5722462f2fe3885a06019605a7977191d69651

1. Autodepent automatically tracks all changes to commit.h and recompiles all including files
2. Theres phony target for commit.h that executes a script that will change the content of commit.h only if it contains a commit different to the current one

This ensures that nothing will be compiled unless its actually necessary, but also assures that the commit is always matches.
