### ISSUE TITLE
Per-message notices of receipt

### ISSUE THREAD

**Issue by alindt** [majn/telegram-purple#165]
Would it be difficult to display notices of receipt "in-line" for each message?
It would be even nicer if it were an icon of some sort to mark the message as "not yet read/seen", like in the official Telegram client, and not the "Message marked as read." text for read/seen messages.

**Comment by majn** [comment]
Basically its not possible. You cant change the messages in the history in a libpurple plugin, its immutable.

There are a few Pidgin plugins that display red lines to indicate read/unread messages in conversations, but they are basically Pidgin specific and doing so would break for anything that uses libpurple and isn't Pidgin.
