### ISSUE TITLE
Chatting with someone should add as buddy

### ISSUE THREAD

**Issue by BenWiederhake** [majn/telegram-purple#168]
Alternative title: `Withlist: "More > Start secret chat with ..." for non-buddy people`

In chat, someone asked to start a secret chat with them.
Context menu didn't contain an option for that, so I had to:
- Start a new chat with them, which marks them as my buddy
- restart pidgin so that the "buddy"-status is acknowledged
- Finally click "Conversation Menu > More > Start secret chat with ..."

That's awkward, and may cause other confusion for users.

**Comment by majn** [comment]
It actually does (once you restart it will be in the dialogue list)

**Comment by BenWiederhake** [comment]
Yeah, once I restart. That's too late.

**Comment by majn** [comment]
I agree that it would be nice to add the user right away when sending a message, but the restart isn't necessary since you can add buddies manually.

**Comment by BenWiederhake** [comment]
Ditto for chats: Creating a chat in some other client lets the group show up in telegram-purple. However, I can't create the invite link from within pidgin without restarting. So: Same issue, different flavor.

**Comment by majn** [comment]
You need to add the chat to the buddy list before you can perform any actions.

**Comment by BenWiederhake** [comment]
How do you mean? The chat already exists in the global buddy list. What else would I need to "add"?

**Comment by majn** [comment]
What do you mean by "global" buddy list? 

If a buddy/chat is in the pidgin buddy list, actions will be available. In all other cases they won't, which is how pidgin handles it. If there is another way to add actions to buddies, I haven't found it yet.

**Comment by BenWiederhake** [comment]
The reasoning is: the user should only need to keep track of *one* concept, namely "list of contacts".

However, currently, there's "list of all contacts (with or without telephone number) according to Telegram", and "list of buddies according to pidgin". The former overwrites the later on restart anyway, so ideally these two concepts should be the same.

By "global" buddy list I meant the former, the "list of all contacts (with or without telephone number) according to Telegram". Bad name, I know. That's one of the reasons why there shouldn't be multiple different concepts :P

**Comment by majn** [comment]
Your suggestion makes sense, it should behave the same.

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
Of course, Pull Requests are still very much welcome!

(Note that tdlib-purple doesn't implement secret chats yet.)
