### ISSUE TITLE
Crash when "double new secret"

### ISSUE THREAD

**Issue by BenWiederhake** [majn/telegram-purple#169]
Steps to reproduce:

- Try to start a secret chat with someone. The other one should NOT do anything, just leave it pending. Don't decline, don't accept.
- Try to start another secret chat with the same person.

Result is a crash. Output of `make run`:

	(21:40:26) prpl-telegram: tgl_do_mark_read (67305174)
	(21:40:26) prpl-telegram: wrote state file: wpts=29783 wqts=11171332 wseq=1111 wdate=1449002373
	(21:40:26) prpl-telegram: wrote secret chat file: 0 chats written.
	(21:40:27) prpl-telegram: tgprpl_blist_node_menu()
	(21:40:30) prpl-telegram: Sent query #6223418048304454656 of size 12 to DC 2
	pidgin: structures.c:83: tree_insert_peer_by_name: Zusicherung »c« nicht erfüllt.
	Aborted

Output of `gdb pidgin -d`:

	(21:45:08) prpl-telegram: Sent query #6223419244006510592 of size 12 to DC 2
	(21:45:08) GLib: Source ID 4166 was not found when attempting to remove it
	pidgin: structures.c:83: tree_insert_peer_by_name: Zusicherung »c« nicht erfüllt.

	Program received signal SIGABRT, Aborted.
	0x00007ffff4924107 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
	56	../nptl/sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
	(gdb) bt full 13
	#0  0x00007ffff4924107 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
			resultvar = 0
			pid = 28742
			selftid = 28742
	#1  0x00007ffff49254e8 in __GI_abort () at abort.c:89
			save_stage = 2
			act = 
			  {__sigaction_handler = {sa_handler = 0x7fffffffe597, sa_sigaction = 0x7fffffffe597}, sa_mask = {__val = {140737297842625, 140736760447688, 83, 4, 140737488336624, 47258480400, 140737488336544, 0, 0, 0, 0, 21474836480, 140737297842151, 140737488336776, 140736683126784, 140737352830846}}, sa_flags = -727912787, sa_restorer = 0x7fffd49d0b10 <__PRETTY_FUNCTION__.11766>}
			sigs = {__val = {32, 0 <repeats 15 times>}}
	#2  0x00007ffff491d226 in __assert_fail_base (fmt=0x7ffff7ec0f7e "%s%s%s:%u: %s%sZusicherung »%s« nicht erfüllt.\n%n", assertion=assertion@entry=0x7fffd49ceead "c", file=file@entry=0x7fffd49d02c8 "structures.c", line=line@entry=83, function=function@entry=0x7fffd49d0b10 <__PRETTY_FUNCTION__.11766> "tree_insert_peer_by_name") at assert.c:92
			str = 0x17e7710 ""
			total = 4096
	#3  0x00007ffff491d2d2 in __GI___assert_fail (assertion=assertion@entry=0x7fffd49ceead "c", file=file@entry=0x7fffd49d02c8 "structures.c", line=line@entry=83, function=function@entry=0x7fffd49d0b10 <__PRETTY_FUNCTION__.11766> "tree_insert_peer_by_name") at assert.c:101
	#4  0x00007fffd494904c in tree_insert_peer_by_name (T=0x15d3070, x=x@entry=0x178a610, y=y@entry=464151818) at structures.c:83
			c = <optimized out>
			__PRETTY_FUNCTION__ = "tree_insert_peer_by_name"
	#5  0x00007fffd4948fee in tree_insert_peer_by_name (T=0x14dfa50, x=x@entry=0x178a610, y=y@entry=464151818) at structures.c:83
			c = <optimized out>
			__PRETTY_FUNCTION__ = "tree_insert_peer_by_name"
	#6  0x00007fffd4948fee in tree_insert_peer_by_name (T=0x1659830, x=x@entry=0x178a610, y=y@entry=464151818) at structures.c:83
			c = <optimized out>
			__PRETTY_FUNCTION__ = "tree_insert_peer_by_name"
	#7  0x00007fffd4948fee in tree_insert_peer_by_name (T=0x17c2400, x=x@entry=0x178a610, y=y@entry=464151818) at structures.c:83
			c = <optimized out>
			__PRETTY_FUNCTION__ = "tree_insert_peer_by_name"
	#8  0x00007fffd4948fee in tree_insert_peer_by_name (T=0x17ba1e0, x=x@entry=0x178a610, y=464151818) at structures.c:83
			c = <optimized out>
			__PRETTY_FUNCTION__ = "tree_insert_peer_by_name"
	#9  0x00007fffd494d6c3 in tglp_peer_insert_name (TLS=TLS@entry=0x14d7fa0, P=P@entry=0x178a610) at structures.c:2334
	#10 0x00007fffd4953b8d in bl_do_encr_chat (TLS=0x14d7fa0, id=469134036, access_hash=<optimized out>, date=<optimized out>, admin=0x7fffffffbaac, user_id=0x7fffffffbaa4, key=0x1f07800, g_key=0x0, first_key_id=0x0, state=0x7fffffffbaa8, ttl=0x0, layer=0x0, in_seq_no=0x0, last_in_seq_no=0x0, out_seq_no=0x0, key_fingerprint=0x0, flags=<optimized out>, print_name=0x0, print_name_len=0) at binlog.c:856
			_U = 0x178a610
			updates = 1
			__PRETTY_FUNCTION__ = "bl_do_encr_chat"
			U = 0x178a610
			Us = <optimized out>
	---Type <return> to continue, or q <return> to quit---
	#11 0x00007fffd49380dd in tgl_do_send_create_encr_chat (TLS=0x14d7fa0, x=<optimized out>, random=0x1f07800 "G\017\241^\267\217v{3I<\231bߊ\301 \206OU0c\215:G^\323x\017", callback=0x7fffd49294b0 <create_secret_chat_done>, callback_extra=0x0)
		at queries-encrypted.c:683
			user_id = 67305174
			i = <optimized out>
			random_here = "\247\301\346qhy\247\302\217\224\342\354\234\031\016ҥO\325\020ܷ\257\061!\306\066\bڮ\003\030\370\301\032\270\337\021\362\067\b\240a<R\362\067\330'\275bז<\343\306\034\260stb\267\061\n8M\031(\235\337ؤ\336\361\027\235\222\204\311\031\222d\032\306H\252Jk\205&-7D\"2\213X\354ER\260Z'\346\001,M]\272\003`\273\025C,\346\203GRv\347\nu{\r\377\237ʍ\000\254z\247\273\031:\335\000\017R\234\177\345\027\272-\244\360\253\177\003\256\"\222\375]\277\026u\243\034hbvu\234\276\375\022sQ\257\037]-\270\243\025\232\310\374)\264\351\b\375\212\307s\257\367\337\376\037\210K\322RU\036\033\032\317D\200\273"...
			a = <optimized out>
			p = 0x1478b88
			g = 0x15db708
			r = 0x16332d8
			g_a = "JT.vH#;\336\023\313`\342\001\257K\203\246\310\063Ĕ\f\365|D\342\344ʴ\000\240Z\271ё^\227\062.\244\201\251i\311V\347\017\225k@shF\024\200.\223\327\071\346\067\207x\330*\023t8®\235ͧ\257\306ޚA\f\273\361\317~g\364\351O;\224ޒ\000\215\266ҡ]S\234\301\346\216%\030\003\246\030\022D\276\210H\335\v-@\227\254\233.y\b\220\252o\361_\220\266\317Z\003\364%Y\261\256D\360\006\200\065L\241\f\025\033i {J^\232\323\"\356\066E6F\224v\235\001:5Ѯ\030\362\314\352\376\254M\267L\271\324\020p\245\004\223\310\334l\222P\177\216R\373\313X\001S\t\017\225(\230\276\305f\273wc"...
			t = 469134036
			state = 1
			our_id = 115630664
			_E = <optimized out>
			__PRETTY_FUNCTION__ = "tgl_do_send_create_encr_chat"
			E = <optimized out>
			U = <optimized out>
	#12 0x00007fffd4936877 in get_dh_config_on_answer (TLS=0x14d7fa0, q=0x17b4f10, D=<optimized out>) at queries-encrypted.c:725
			x = 0x15e21f0
			DS_MDC = <optimized out>
			__PRETTY_FUNCTION__ = "get_dh_config_on_answer"
			random = 0x1f07800 "G\017\241^\267\217v{3I<\231bߊ\301 \206OU0c\215:G^\323x\017"
	#13 0x00007fffd493b38f in tglq_query_result (TLS=TLS@entry=0x14d7fa0, id=<optimized out>) at queries.c:479
			save = <optimized out>
			DS = 0x17eff40
			end = 0x0
			eend = 0x0
			q = 0x17b4f10
			__PRETTY_FUNCTION__ = "tglq_query_result"

Btw: I don't understand something about secret chats. Say I have a laptop and a computer (two endpoints), and my friend thus has two secret chats with me. How to display that difference to "my friend"?

**Comment by BenWiederhake** [comment]
I'm not sure whether this is a bug in tgl, so I'm posting this here, first.

**Comment by majn** [comment]
This might be an issue only in the test branch, update to at least (https://github.com/majn/telegram-purple/commit/202772ed78c96cbd30e22cf139e781125f0178c8) and reproduce

**Comment by BenWiederhake** [comment]
Yup, with this version it works. Sorry, it seems I was using an outdated version back then.
