### ISSUE TITLE
Regression: Bad behaviour on reconnect

### ISSUE THREAD

**Issue by BenWiederhake** [majn/telegram-purple#173]
Until "recently" (unknown versions, sorry), it was perfectly fine to restart internet connection (due to the 24h IP change) with pidgin open.

Now, telegram-purple displays all buddies, but behaves as if all buddies are offline, and doesn't let me write anything in any chat / buddy.

The console spits out a lot of repetitive messages:

	(02:27:12) prpl-telegram: Sent query #6931705913315636 of size 120 to DC 2
	(02:27:12) proxy: Attempting connection to 149.154.167.51
	(02:27:12) proxy: Connecting to 149.154.167.51:443 with no proxy
	(02:27:12) proxy: Connection in progress
	(02:27:17) prpl-telegram: restart_connection()
	(02:27:17) proxy: Attempting connection to 149.154.167.51
	(02:27:17) proxy: Connecting to 149.154.167.51:443 with no proxy
	(02:27:17) proxy: Connection in progress
	(02:27:18) prpl-telegram: Alarm query 6931705913315636 (type 'get difference')
	(02:27:18) prpl-telegram: Resent query #6931705913315636 as #6931734787856300 of size 120 to DC 2
	(02:27:21) proxy: Connecting to 149.154.167.51:443.
	(02:27:21) proxy: Error connecting to 149.154.167.51:443 (Keine Route zum Zielrechner).
	(02:27:21) proxy: Connection attempt failed: Keine Route zum Zielrechner
	(02:27:21) prpl-telegram: Connection not possible, either your network or a Telegram data center is down, or the Telegram network configuration has changed.
	(02:27:24) prpl-telegram: Alarm query 6931734787856300 (type 'get difference')
	(02:27:24) prpl-telegram: Resent query #6931734787856300 as #6931760559657644 of size 120 to DC 2
	(02:27:30) prpl-telegram: Alarm query 6931760559657644 (type 'get difference')
	(02:27:30) prpl-telegram: Resent query #6931760559657644 as #6931786344605916 of size 120 to DC 2
	(02:27:36) prpl-telegram: Alarm query 6931786344605916 (type 'get difference')
	(02:27:36) prpl-telegram: Resent query #6931786344605916 as #6931812124317572 of size 120 to DC 2
	(02:27:42) prpl-telegram: Alarm query 6931812124317572 (type 'get difference')
	(02:27:42) prpl-telegram: Resent query #6931812124317572 as #6931837879255156 of size 120 to DC 2
	(02:27:48) prpl-telegram: Alarm query 6931837879255156 (type 'get difference')
	(02:27:48) prpl-telegram: Resent query #6931837879255156 as #6931863648438848 of size 120 to DC 2
	(02:27:54) prpl-telegram: Alarm query 6931863648438848 (type 'get difference')

The last two lines repeat (with changing query IDs) every 6 seconds for the next 5 hours, ongoing.

"Disable account, Enable account" fixes the problem, so this is a short-term solution.

**Comment by majn** [comment]
Whishlist: the whole log ;)

**Comment by BenWiederhake** [comment]
That ... was essentially it. Do you mean without the `grep` part due to make run? I can provide that only tomorrow, if you need.

If you just want the whole output of "make run", here's everything that could be remotely interesting: http://pastebin.com/ZpqjdAnf

**Comment by majn** [comment]
I'm interested in the whole log of the disconnect. If the router reconnects, that means that the connections to *all* data centers were restarted. Your log only contains the connection attempts to DC 2.

**Comment by BenWiederhake** [comment]
That *is* the whole log around the disconnect and then reconnect.

All else is due to one of these:

- Nothing interesting happens (all the "ping" messages before and afterwards; the repeated "resent query" thing; no further things were truncated because of this entry)
- filtered out by the `grep` part (I launched it via `make run`)
- It doesn't show in the log because it didn't happen

To make sure the next log is complete, I restarted `pidgin -d | tee /tmp/pidgin_-d.txt` and will send that file to you, tomorrow.

**Comment by BenWiederhake** [comment]
I just sent the full log to you via private mail.
(I intentionally don't publish it here, as there's quite a lot of sensitive data in there, e.g. a lot of private contacts and metadata.)
