### ISSUE TITLE
Wishlist: Send to deleted but still available buddy

### ISSUE THREAD

**Issue by BenWiederhake** [majn/telegram-purple#174]
I accidentally deleted a contact from the buddy list in pidgin, but still had a conversation window open. So I just wrote something there, expecting the buddy to be either restored, or the chat still somehow working.

    (13:20:17) Nachricht konnte nicht gesendet werden.

(Translation: Message couldn't be sent)

My request is to change behaviour for this case, to one of the following:

- Change that to a more helpful message. I don't know if that's possible.
- Avoid that and restore the buddy

As a temporary workaround: Since the contact is still available from all other clients, I just restarted pidgin and contacted him again using web.telegram.org.

**Comment by majn** [comment]
Fixed on dev-1.2.3
