### ISSUE TITLE
Find a way to handle muted chats

### ISSUE THREAD

**Issue by majn** [majn/telegram-purple#176]

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
Of course, Pull Requests are still very much welcome!

(Aw man, I was alwways hoping someone would do that.)
