### ISSUE TITLE
Reconnect with chatrooms on network reconnect

### ISSUE THREAD

**Issue by BenWiederhake** [majn/telegram-purple#179]
Sometimes, when my network reconnects, Telegram chats become "disconnected", and it says:

    (01:56:25) Das Konto wurde getrennt und Sie sind nicht mehr in diesem Chat. Sie werden den Chat automatisch wieder betreten, wenn das Konto wieder verbunden ist.

or, roughly, in English: "The account was disconnected and you are no longer in this chat. You will automatically re-join the chat on reconnect."

This happens regardlessly whether "Automatisch Beitreten" (i.e., "Automatically join") and "Persistent" are selected.

Any hints where I could look? Is this maybe "normal" for purple/pidgin?

**Comment by majn** [comment]
It attempts a reconnect, but unfortunately this function is called directly after a successful connection, when I don't have the chat-objects yet, and therefore the api call is not possible.

I can't set the online status later, cause that would cause really bad interferences with notification plugin, therefore I wont be able to fix this issue.

Its not that bad either, cause when you attempt to send a message or receive one, it will reconnect the chat anyways.

**Comment by EionRobb** [comment]
Can't it queue up which rooms want to be rejoined until you have enough info to be able to rejoin?

**Comment by majn** [comment]
Done
