### ISSUE TITLE
Wishlist: Handle Windows newline properly

### ISSUE THREAD

**Issue by BenWiederhake** [majn/telegram-purple#182]
Steps to reproduce:
1. Use Telegram on Windows. I used Windows 7 with Chrome with web.telegram.org
2. Send a multi-line message (Type "hello", then shift+return, then "world", then click on "send")
3. Observe telegram-purple's reaction

Expected results:
The same like with any other client sending multi-line messages. When doing this with "Linux+Chrome+web.telegram.org", then telegram-purple can display it fine.

Actual results:
Pidgin doesn't notice that there are linebreaks _at all_. This is bad, especially when it's many lines (e.g. a "table").

**Comment by budkin** [comment]
this isn't only a windows issue, I'm having it on linux using bitlbee

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple), which might already have this enhancement. For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
Of course, Pull Requests are still very much welcome!
