### ISSUE TITLE
no libgcrypt >= 1.60 found 

### ISSUE THREAD

**Issue by githubtefo** [majn/telegram-purple#184]
Hello!
I can't update to the last version because Ubuntu 12.04 uses the package libgcrypt11-dev (Version: 1.5.0-3ubuntu0.4).
Is there any alternative to install it on this context?
Thanks!
St.-

**Comment by BenWiederhake** [comment]
Doesn't Ubuntu have the concept of backports? libgcrypt11 is pretty old by now. Just use an appropriate version from the backports repository.

If that doesn't work, I'm sorry, since your use-case is a corner case: there aren't many people who desire to use an ancient OS version (12.04 is nearly 4 years old!) together with bleeding-edge programs (telegram-purple didn't even exist then! As far as I can tell, development didn't start until way after 2013-10!).

---

Still here? You really REALLY want to do this combination? Are you aware that this is usually a bad idea?
Well, there's no strict need for >=libgcrypt16, if you have OpenSSL available and don't mind the licensing issue. (If you're using Ubuntu, you already made that choice.)
You're going to have to change `Makefile.in`, the line with the `(cd tgl && ./configure --disable-openssl $BLAH)` in it, and remove the `--disable-openssl` part. Then you can use OpenSSL instead of libgcrypt.
You may need to make further changes, though, since recent (and future!) development didn't care about OpenSSL interop.

Please tell me if you run into any issues that you can't resolve on your own.

**Comment by mcepl** [comment]
> there aren't many people who desire to use an ancient OS version

RHEL-7 (the latest RHEL) has only ``libgcrypt-1.5.3``. IMHO, it breaks [spectrum](http://spectrum.im) on all RHELs.

**Comment by majn** [comment]
There have been *lots* of breaking changes between libgcrypt1.5.4 and libgcrypt1.6.0, most of which seem to concern the bignum functions that we use to implement most of the crypto. I haven't gone through every single change, but at a first glance it doesn't really seem possible to make it backwards-compatible.

![bildschirmfoto 2015-12-14 um 12 22 46](https://cloud.githubusercontent.com/assets/2327132/11779798/a88d3c1a-a25d-11e5-85dd-5234ec898080.png)

**Comment by mcepl** [comment]
OK, then I would either respectfully ask for maintenance of the OpenSSL option, or I am out of Telegram (which is not a big loss for me, so I won't complain too much).

**Comment by BenWiederhake** [comment]
Like I already suggested, here's a pretty good deal of "maintenance": Try it out (edit `telegram-purple/Makefile.in` and remove the `--disable-openssl` option), and report any problems. As far as I know, there shouldn't be any.

"Out of Telegram"? Why that? There's lots of other clients out there. This one is the plugin for pidgin.

**Comment by mcepl** [comment]
> "Out of Telegram"? Why that? There's lots of other clients out there. This one is the plugin for pidgin.

Sorry, I meant for Spectrum. I don’t feel like Telegram is valuable enough for me to install another client on my phone (Conversations is enough for everything else).

**Comment by mcepl** [comment]
So, OK, actually it doesn't work even with the workaround described above:
[build.log.txt](https://github.com/majn/telegram-purple/files/61529/build.log.txt)
Unsubscribing from this ticket and giving up on Telegram.

**Comment by BenWiederhake** [comment]
Hah! Talk about rage-quit.

For future reference: His build failed because of an `#include <gcrypt.h>` in `telegram-base.c`, which is only used for `gcry_md_hash_buffer (GCRY_MD_SHA1, sha, (void *)key, 256);`

One can immediately see that this can be replaced by an appropriate function in `#include <openssl/sha.h>`. So the drop-in replacement is `SHA1 ((void *)key, 256, sha);`

Since this is the ONLY place where a gcrypt function is used in telegram-purple, it's very likely to build now right away.

Closing, because @mcepl didn't, but obviously intended to.

**Comment by mcepl** [comment]
> Hah! Talk about rage-quit.

I know rage-quits, did bunch of them myself, but this wasn't it. Just cold consideration that fixing this build would cost me more than I expect from Telegram working, which is not much.

**Comment by mcepl** [comment]
OK, with https://gitlab.com/mcepl/pkg-telegram-purple/blob/0fb67cc285/telegram-purple-build.patch it builds on EPEL-7 https://copr.fedoraproject.org/coprs/mcepl/spectrum2/build/147822/ No further testing has been done.

**Comment by mcepl** [comment]
Hmm, weird. libpurple backend still fails with:
```
==> /var/log/spectrum2/telegram.cepl.eu/backends/backend-1.log <==
9181: 2015-12-14 16:56:30,958 INFO  backend: +420604893825: Invalid protocol 'prpl-telegram'
```

**Comment by EionRobb** [comment]
You could change telegram-base.c to not need openssl or gcrypt by using libpurple's own sha1 impl (and then it'd leave libtgl to pick between the two)

**Comment by majn** [comment]
I'm not really too enthusiastic about the thought of supporting two different crypto libraries, but as there's obviously a need for it and its hardly any effort I'll think about just adding the option.

**Comment by EionRobb** [comment]
Don't forget #1

**Comment by majn** [comment]
If I understand correctly, this shouldn't be an issue as long as its not packaged with openssl (which I won't).

**Comment by EionRobb** [comment]
As long as it's not distributed with links to openssl, right

**Comment by githubtefo** [comment]
Guys! Thanks for your attention and help!
I tried to compile and install the fork of @EionRobb but again I obtained the "no libgcrypt >= 1.60 found" message when I execute ./configure. I also removed the --disable-openssl part from this parch but with the same result. Am I doing something wrong?
Regarding Ubuntu 12.04, I'm still using it because it has support and I've got an old PC, may be the best option should be migrate to an Arch distro with a lightweight desktop environment like I've already done with my Asus EEE 701 netbook.
Thanks again!
St.-

**Comment by BenWiederhake** [comment]
Oh, right, you also need to remove the following lines from `configure.ac`:

	AC_CHECK_LIB([gcrypt], [gcry_mpi_snatch], [], [
	  echo "no libgcrypt >= 1.60 found"
	  exit -1
	])

We'll think of a way how to automate that more cleverly. Until then, sorry for the trouble.

**Comment by githubtefo** [comment]
Thanks @BenWiederhake for your answer, please It's not a trouble for me.
Well, I removed the lines from configure.ac, but again I obtained the "no libgcrypt >= 1.60 found" message during the execution of ./configure.
Is there any chance that another files are still checking the libgcrypt version?
St.-

**Comment by mcepl** [comment]
You have to regenerate your ``configure`` first. Remove it and run ``./autogen.sh`` and only then ``./configure``.

**Comment by githubtefo** [comment]
Oops, another package version problem when I execute ./autogen.sh:
```
configure.ac:4: error: Autoconf version 2.69 or higher is required
configure.ac:4: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: /usr/bin/autom4te failed with exit status: 63
autoreconf: aclocal failed with exit status: 63
bootstrapping translation files ...
```
So I manually removed the "exit" line from the configure file:
```
#define HAVE_LIBGCRYPT 1
_ACEOF

  LIBS="-lgcrypt $LIBS"

else

  echo "no libgcrypt >= 1.60 found"

fi
```
Now I can create the make file, but when I executing I've got another error message:
```
make -C tgl
make[1]: se ingresa al directorio «/home/.../telegram-purple/tgl»
gcc -I. -I. -g -O2  -I/usr/local/include -I/usr/include -I/usr/include   -DHAVE_CONFIG_H -Wall -Wextra -Werror -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -c -MP -MD -MF dep/queries.d -MQ objs/queries.o -o objs/queries.o queries.c
queries.c:3295:6: error: tipos en conflicto para ‘tgl_do_send_extf’
tgl.h:601:6: nota: la declaración previa de ‘tgl_do_send_extf’ estaba aquí
make[1]: *** [objs/queries.o] Error 1
make[1]: se sale del directorio «/home/.../telegram-purple/tgl»
make: *** [tgl/libs/libtgl.a] Error 2
```
Previously what I've done was:

1) git clone --recursive https://github.com/EionRobb/telegram-purple.git
2) download the .zip "telegram-purple-patch-1" and replace all the changed files on telegram-purple
3) Apply all the lines changes that you mentioned.
4) ./configure

**Comment by BenWiederhake** [comment]
This sounds like a combination of a known, already fixed bug; outdated build artifacts; and some misconfiguration.

I introduced a new switch `--disable-gcrypt` that should do all the magic.
Please try the following, starting again *from scratch*:

    git clone --recursive --branch dev-1.2.3 https://github.com/BenWiederhake/telegram-purple.git
    cd telegram-purple
    LC_ALL=C ./configure --disable-gcrypt
    LC_ALL=C make

Please tell us if you run into any further problems. The `LC_ALL=C` in front of a command has the effect that all errors are in English, which allows us to read them. If that causes problems, try again without it.

**Comment by BenWiederhake** [comment]
Sorry, off by one whitespace,

In case you cloned in the last 2 hours, please make sure that you are at commit `eab5515b0d1d836bd6c9b7849a27e7e66874be13`

**Comment by githubtefo** [comment]
Again the error of the opened issue, guys.
Here the output:
````
username@hostname:~/Escritorio$ git clone --recursive --branch dev-1.2.3 https://github.com/BenWiederhake/telegram-purple.git
Cloning into 'telegram-purple'...
remote: Counting objects: 8693, done.
remote: Total 8693 (delta 0), reused 0 (delta 0), pack-reused 8693
Receiving objects: 100% (8693/8693), 13.85 MiB | 1.77 MiB/s, done.
Resolving deltas: 100% (5622/5622), done.
Submodule 'tgl' (https://github.com/vysheng/tgl) registered for path 'tgl'
Cloning into 'tgl'...
remote: Counting objects: 1488, done.
remote: Total 1488 (delta 0), reused 0 (delta 0), pack-reused 1488
Receiving objects: 100% (1488/1488), 1.00 MiB | 435 KiB/s, done.
Resolving deltas: 100% (1085/1085), done.
Submodule path 'tgl': checked out '380e4f90e376b0769db4b5f84f8092524a8ef4a4'
Submodule 'tl-parser' (https://github.com/vysheng/tl-parser) registered for path 'tl-parser'
Cloning into 'tl-parser'...
remote: Counting objects: 65, done.
remote: Total 65 (delta 0), reused 0 (delta 0), pack-reused 65
Unpacking objects: 100% (65/65), done.
Submodule path 'tl-parser': checked out '36bf1902ff3476c75d0b1f42b34a91e944123b3c'
username@hostname:~/Escritorio$ cd telegram-purple/
username@hostname:~/Escritorio/telegram-purple$ LC_ALL=C ./configure --disable-gcrypt
configure: WARNING: unrecognized options: --disable-gcrypt
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking for clock_gettime in -lrt... yes
checking for gcry_mpi_snatch in -lgcrypt... no
no libgcrypt >= 1.60 found
username@hostname:~/Escritorio/telegram-purple$ ./configure --disable-gcrypt
configure: WARNING: unrecognized options: --disable-gcrypt
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking for clock_gettime in -lrt... yes
checking for gcry_mpi_snatch in -lgcrypt... no
no libgcrypt >= 1.60 found
```

In the worst scenario I could continue using an outdated pidgin-telegram version in case it has not security issues until next year when I'll buy a new laptop.

**Comment by BenWiederhake** [comment]
I can't believe it. I'm sorry, I simply forgot to push eab5515b0d1d836bd6c9b7849a27e7e66874be13. I'm an idiot, sorry for the wasted time.

Please don't give up! I really want to see it working on your laptop, becaue I'm sure you're not alone with this issue. Please try again.

**Comment by BenWiederhake** [comment]
For the record, what happened is this, in the following order:

- I became convinced that the current state must be correct, since it works on my machine
- it made it into master
- @majn and several others notices that it doesn't work on OS X, Ubuntu 14.04, and probably several other OSes.
- @majn reverted it, because I broke the build (sorry!), and master should NEVER be broken.

So now I'm working on:

1. Finding out what causes the difference, and a way to fix this finally
2. Reading about how docker, github, and all these work, so this won't happen again.

**Comment by majn** [comment]
Those issues should now be fixed, the current master seems to compile with openssl if you specify --disable-gcrypt. If it doesn't work, just reopen the issue.

**Comment by mcepl** [comment]
Thanks, now it builds in RHEL-7 as well. https://copr.fedoraproject.org/coprs/mcepl/spectrum2/build/150998/

**Comment by EionRobb** [comment]
@mcepl distributing those builds with openssl built in is a violation of the gpl. Please take them down.

**Comment by mcepl** [comment]
With pleasure, I just wanted to help the project as I don't use (mostly useless here in Europe) Telegram anymore.

**Comment by BenWiederhake** [comment]
Why mostly useless in Europe? Most people I know use Telegram.

**Comment by mcepl** [comment]
Let's not go there ... such silly useless projects as RHEL have been kicked out from here, so I don't care anymore.

**Comment by BenWiederhake** [comment]
Since RHEL usually ignores the OpenSSL-GPL conflict (every distro except Debian does), I'm going to assume that you'll be mostly fine. So check back with a higher-up within RHEL. Also, why is RHEL a "silly useless project"?

**Comment by githubtefo** [comment]
I've done!
Compiling from the main repository with the "--disable-gcrypt" option.
Thanks to all!
