### ISSUE TITLE
Cleverly clean build artifacts when configure options change

### ISSUE THREAD

**Issue by BenWiederhake** [majn/telegram-purple#188]
Currently, we have quite a bunch of `./configure`-options with very sensitive behaviour:

- `--disable-gcrypt` (If we do #184 like I suggested there)
- `--disable-libwebp`
- `--disable-icons` (Since #100 -- come to think of it, this shouldn't be a `./configure`-option, but rather a different `make`-target …)
- `--disable-translation` (See https://github.com/majn/telegram-purple/commit/0bb5b0121d086a8528f8393ba5beb7cf1f82bfb7 on branch `dev-1.3.0`)
- The breaking change towards `tgl/configure --disable-extf`, when updating to f53f13592acd14891e2ccba6496335c10eb4b8f4
- Possibly more in the future.

Flipping any of these switches means that the user (i.e., the developer who flipped the switch and now wishes to re-build) has to do a `make -C tgl clean && rm tgl/Makefile`. Note that just `rm tgl/makefile` doesn't suffice, since there may be old build artifacts that are now incompatible.

This behaviour isn't documented. This behaviour isn't obvious. Forgetting either of the two "cleanup" steps can cause a lot of confusion, and potentially heavy breakage. Sometimes it will be even necessary to `make clean` telegram-purple itself, sometimes not.

This issue is a single plea: "OH GOD MAKE IT STOP!"
Ideally, there is no sequence of commands the user can issue that could possibly result in an inconsistent state. There's two ways I can see to resolve this:

- `./configure` automatically cleans tgl and telegram-purple, if the build flags are different from last `./configure` invocation.
- `Makefile.in` should do some intelligent things. Maybe let all build files depend on `Makefile`?

Actually, how do other projects do this?

**Comment by majn** [comment]
tgl/configure--disable-extf should just be called from within configure. Make clean already removes content in tgl. 

>Actually, how do other projects do this?
Well, tg didn't use a recursive makefile, but kept a copy of Makefile.tgl and Makefile.tl-parser inside of the directory, and always did all build steps from those central makefiles. This is how it used to work in telegram-purple too before we streamlined the build process ;)

**Comment by BenWiederhake** [comment]
Yeah, but the "one Makefile" approach sadly doesn't work here too well :P 

configure calling tgl/configure? Hmm. That only solves part of the problem, since the call to make clean is still necessary.

configure could instead delete tgl/Makefile. That would be a much less intrusive change with the exact same effect.

**Comment by majn** [comment]
I'm pretty sure that the call to make clean is necessary for any other project too, thats just how make and configure works. I just tested with libwebp, it will not automatically call clean when you configure.

Sure, some people don't know how make works, but this is why providing working packages should be highest priority at this point.

**Comment by BenWiederhake** [comment]
Okay, so I'll do the following changes:

- configure deletes tgl/Makefile
- expect the user to call `make clean` by himself

**Comment by majn** [comment]
Why wouldn't we just move ./tgl/configure --whatever into ./configure? That way we wouldn't need code in the makefile and in autotools.

**Comment by BenWiederhake** [comment]
That would involve a lot of work that just duplicates the efforts of tgl/configure. Keeping it in sync would be a pain. Manual re-configuration would become neigh-impossible and most definitely broken. What for?

**Comment by majn** [comment]
Maybe you know something I don't know, but shouldn't adding this line in configure ac be enough?

  cd tgl && ./configure -q --disable-openssl --disable-extf CFLAGS="$CFLAGS@" LDFLAGS="$CFLAGS"

What exactly do you need to keep "in sync"? Why would it break manual re-configuration?

**Comment by BenWiederhake** [comment]
Ohhh, I misunderstood you.

What you meant: Move the literal line that invokes tgl/configure into our configure.ac. That's a good idea. I like that.

What I understood: Move the entire content of tgl/configure.ac into our configure.ac. That would be a pain.

**Comment by BenWiederhake** [comment]
Oh, and add parenthesis around the expression, so we have a subshell.

**Comment by BenWiederhake** [comment]
Already done in 1.2.5, maybe earlier.
