### ISSUE TITLE
Mass message "Nachricht als gelesen markiert." aka "Message read"

### ISSUE THREAD

**Issue by tuxmaster** [majn/telegram-purple#189]
This will happens without any reasons(Or I cant' see it).
I write an message then I get one "message read" and in the time between I send the next I see sometimes 5-10 times the message "messages read".
The blue was my text an red of my buddy.
I use the last 1.2.2 version.
![bildschirmfoto von 2015-12-19 19-58-49](https://cloud.githubusercontent.com/assets/6240474/11914839/471f7556-a68b-11e5-96af-217617d8b9bb.png)

**Comment by majn** [comment]
This should be fixed in the current master.

FIY: what you see in that screenshot are actually the read recipes you sent from other devices, I wasn't aware those will be forwarded, but now it is handled properly.
