### ISSUE TITLE
Improve interop with "hide left/joined" chat messages pidgin plugin

### ISSUE THREAD

**Issue by majn** [majn/telegram-purple#190]

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
Of course, Pull Requests are still very much welcome!
