### ISSUE TITLE
No longer syncs

### ISSUE THREAD

**Issue by Silent-Hunter** [majn/telegram-purple#192]
My Pidgin no longer syncs with the Telegram messages on other devices. So if I have a conversation from my phone, it doesn't show up when I open Pidgin. It used to not too long ago.

I just cloned and built less than 5 minutes ago, still not working.

**Comment by Silent-Hunter** [comment]
Nevermind, it has fixed itself.

**Comment by BenWiederhake** [comment]
For the record (no really, ignore this), someone posted a similar issue earlier. Maybe say "downloading messages ..." or something if that's the issue. If we actually lose messages, that would be a critical bug.
