### ISSUE TITLE
Logs of secret chats shouldn't be saved to disk

### ISSUE THREAD

**Issue by BenWiederhake** [majn/telegram-purple#196]
Current: Logs of secret chats are always written to disk, with no way of avoiding that.

However, at least in some cases, it may be desirable to _not_ have these kinds of traces. Just imagine you're Edward Snowden.

Ideally, there should be _all_ of the following:
- A option to disable logging at all, either via libpurple's `NO_LOG` or system messages.
- A warning on top, like `This chat is end-to-end-encrypted, but still saved to your disk in cleartext. If you don't want that, uncheck the option "Save logs of secret chats".`
- When the option is switched, there should appear a message in _all_ secret chats (opened and closed), to prevent someone from "tweaking" your client.
- Lots of manual testing to make sure that in all cases, `NO_LOG` is respected.

**Comment by EionRobb** [comment]
OTR does something similar with ```purple_conversation_set_logging(conv, FALSE);```:
https://bugs.otr.im/projects/pidgin-otr/repository/revisions/master/entry/otr-plugin.c#L931

With warnings about logging being enabled at https://bugs.otr.im/projects/pidgin-otr/repository/revisions/master/entry/gtk-dialog.c#L1524

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.

(Note that tdlib-purple doesn't implement secret chats to begin with.)
