### ISSUE TITLE
Last git version incomplete?

### ISSUE THREAD

**Issue by tuxmaster** [majn/telegram-purple#197]
Checking out  with git clone --recursive https://github.com/majn/telegram-purple and build result in:
config.status: creating Makefile
config.status: creating config.h
configure: WARNING: unrecognized options: --disable-dependency-tracking
+ make -j2
tgl/Makefile.in not found. Maybe you need to 'git submodule update --init --recursive' ?
Makefile:77: recipe for target 'tgl/Makefile.in' failed
make: *** [tgl/Makefile.in] Error 1

**Comment by majn** [comment]
Does tgl/Makefile.in exist? It should, see the commit that's referenced as a submodule: https://github.com/vysheng/tgl/blob/380e4f90e376b0769db4b5f84f8092524a8ef4a4/Makefile.in

**Comment by tuxmaster** [comment]
Sorry my mistake, I package the wrong directory. :(

**Comment by majn** [comment]
never mind, there's apparently another bug in the repo. Please wait until you package it.

**Comment by BenWiederhake** [comment]
For the record: The message `Maybe you need to 'git submodule update --init --recursive' ?` is only displayed if a file that should be in git suddenly isn't there. That's why I phrased the message like that.

As @tuxmaster closed this issue, I'm going to assume that was the cause. Otherwise, feel free to re-open this issue.

**Comment by andpaz** [comment]
hallo, i'm trying to install telegram plugin for pidgin, i get no error from ./configure an the Makefile.in exists but when i type make, i get the following error:

tgl/Makefile.in not found. Maybe you need to 'git submodule update --init --recursive' ?
Makefile:75: set di istruzioni per l'obiettivo "tgl/Makefile.in" non riuscito
make: *** [tgl/Makefile.in] Errore 1

**Comment by BenWiederhake** [comment]
Maybe you need to 'git submodule update --init --recursive' then.

Sorry for being unhelpful, but you cloned the repo in a wrong way, and the error message literally tells **you** what to do, so ... please try that! :D

**Comment by andpaz** [comment]
i tried with no success. i get  

fatal: Not a git repository (or any of the parent directories): .git

i'm stuck here, i don't know exactly what is git and how it works

**Comment by BenWiederhake** [comment]
Ah, now I see why you're stuck.

Of course there's a "simple" way to recover from here, but I guess you haven't changed much in the source code, and aren't interested in learning git, and that's fine.

Quick and dirty: delete telegram-purple, and start from scratch with this: `git clone --recursive https://github.com/majn/telegram-purple.git` , and then it should work just like you expected (`./configure` and so on)

**Comment by andpaz** [comment]
i let you know tomorrow, thank you very much
