### ISSUE TITLE
Retrieve past pictures

### ISSUE THREAD

**Issue by nomeata** [majn/telegram-purple#204]
Hi,

I was delighted to see that pidgin would display pictures sent over telegram just fine (good job!), but it seems I am not able to retrieve them later again, from the chat history (Ctrl-H). It would be nice if that worked.

Thanks,
Joachim

**Comment by marhkb** [comment]
+1
That is a feature I am really missing

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
Of course, Pull Requests are still very much welcome!

(If you mean the "History" window in pidgin: That's something the frontend does, and pidgin simply doesn't support it for some reason. So your first step should be to implement support for that feature in pidgin, or whatever frontend you use. With that, it should work automatically.)
