### ISSUE TITLE
Rename "Username" field to "Registered Phone Number" in account setup

### ISSUE THREAD

**Issue by meersjo** [majn/telegram-purple#205]
Hey,

A minor usability thing: In the (android) app, "username" is used for your display name. It's counterintuitive to ask for the username in the account setup screen when you really want the phone number.

I didn't even (consciously) realise that Telegram used my phone number for registration, so the "invalid phone number" error was doubly confusing until I read the readme. I can only assume that it's even more so for random users who aren't used to third-party software.

Thanks for a great plugin!

/Johan

**Comment by majn** [comment]
I can't change the caption "username", this is hardcoded, but I can include a hint message inside of the label.

**Comment by BenWiederhake** [comment]
(implemented as function `tgprpl_get_account_text_table`)

**Comment by BenWiederhake** [comment]
Added in 1.3.1 or even earlier.  Feel free to reopen if there's any issue.
