### ISSUE TITLE
Pidgin crashes when retrieving new telegram gif/bot types

### ISSUE THREAD

**Issue by alindt** [majn/telegram-purple#207]
Pidgin started crashing when trying to retrieve history containing messages with the official client's "new" gif/bot format(?).

https://telegram.org/blog/gif-revolution
https://telegram.org/blog/inline-bots

Package: telegram-purple
State: installed
Version: 1.2.2~beta+git20151124~webupd8~trusty0

```sh
$ pidgin -d 
[...]
(21:15:29) cap: Executing: insert into cap_status (buddy, account, protocol, status, event_time) values(XXX, +XXX, prpl-telegram, mobile, now());
(21:15:29) prpl-telegram: bad_msg_notification: msg_id = 6236013035975612416, seq = 2, error = 64
(21:15:29) prpl-telegram: bad_msg_notification: msg_id = 6236013035975612416, seq = 2, error = 64
(21:15:29) prpl-telegram: failing session -6305426259086759416
(21:15:29) prpl-telegram: bad_msg_notification: msg_id = 6236013035975626752, seq = 2, error = 64
(21:15:29) prpl-telegram: bad_msg_notification: msg_id = 6236013035975626752, seq = 2, error = 64
(21:15:29) prpl-telegram: failing session -4693334409191503329
[...]
pidgin: structures.c:1205: tglf_fetch_message_media: Assertion `0' failed.
dns[25447]: Oops, father has gone, wait for me, wait...!
Aborted
```

**Comment by BenWiederhake** [comment]
This may be due to the recent issue found in tgl. Please try the new version with the "unsupported support"

**Comment by alindt** [comment]
What new version? What does "unsupported support" mean?

The issue reported here started a few hours ago right after updating the official android client (just as the new version hit the Play Store) and sending a "gif bot" message - the last commit in this repo is "Latest commit 0f10389  2 days ago"

**Comment by majn** [comment]
Just pushed a fix to the master.
