### ISSUE TITLE
Pidgin crashes when trying to load message with gif

### ISSUE THREAD

**Issue by grimpy** [majn/telegram-purple#210]
I wanted to try out https://telegram.org/blog/inline-bots
And tried to send a @gif to a friend (from my phone) afterwards pidgin immeditaly crashes when trying to load this message

```
pidgin
pidgin: structures.c:1205: tglf_fetch_message_media: Assertion `0' failed.
[1]    25040 abort (core dumped)  pidgin
```

**Comment by majn** [comment]
see https://github.com/majn/telegram-purple/issues/207
