### ISSUE TITLE
Pidgin crash with active Telegram account

### ISSUE THREAD

**Issue by sewi-cpan** [majn/telegram-purple#212]
Pidgin started crashing yesterday evening whenever I enable my Telegram account.
pidgin -d doesn't look helpful, it ends with:
(08:24:27) prpl-telegram: 3952xxxx: when=0
(08:24:27) prpl-telegram: mobile
(08:24:27) blist: Updating buddy status for 3952xxxx (Telegram)
(08:24:27) cap: Executing: insert into cap_status (buddy, account, protocol, status, event_time) values(3952xxxx, +491633xxxxxx, prpl-telegram, mobile, now());
pidgin: tgl/structures.c:999: tglf_fetch_message_media_new: Zusicherung »0« nicht erfüllt.
Abgebrochen (Speicherabzug geschrieben)

Last two messages translated would be:
Assertion »0« failed
(Core dump)

Any chance to fix this or get more debug information?

**Comment by BenWiederhake** [comment]
Oops, this may be my fault, at least partially. I disabled building the `extf` queries of tgl, since they are not used by telegram-purple.

No active branch contains that symbol at all. What version are you using? Could you please do `git status && git describe` and send the output?

**Comment by sewi-cpan** [comment]
Currently using the official released package from the PPA repository:
$ apt-cache show telegram-purple
Package: telegram-purple
Status: install ok installed
Priority: extra
Section: net
Installed-Size: 2500
Maintainer: Alin Andrei <webupd8@gmail.com>
Architecture: amd64
Version: 1.2.1~beta+git20150923~webupd8~vivid1

Did apt-get update && apt-get upgrade before creating the issue, but everything is up to date. Maybe Telegram changed something yesterday? I didn't do any updates yesterday (sitting on the train with bad internet when Pidgin started failing).

**Comment by meersjo** [comment]
Reporting same problem, using almost the same version: 1.2.2~beta+git20151124~webupd8~trusty0 on Linux Mint 17/x64.

**Comment by BenWiederhake** [comment]
Hmm, that version is slightly outdated by now. (We recently released 1.2.4)

I'd like to ask you *both* to build from the latest master and check whether the problem still occurs:

    git clone https://github.com/majn/telegram-purple.git
    cd telegram-purple
    ./configure
    make

This should work as-is for @meersjo.

@sewi-cpan: If you have Ubuntu 12.04, please configure with `./configure --disable-gcrypt`

**Comment by meersjo** [comment]
Will do. How come the launchpad PPA doesn't refresh automatically? :-p

**Comment by meersjo** [comment]
Built the deb off the debian-master branch, which generated telegram-purple_1.2.3-1_amd64.deb. Not the latest version (or maybe just numbering not updated?), but that appears to work for me.

Thank you for the quick response!

**Comment by majn** [comment]
This issue is already fixed and pushed to master: https://github.com/majn/telegram-purple/issues/207

I don't control the launchpad PPA, its maintained by Webupd8 (see maintainer entry of the PPA), I've already contacted him two days ago about this issue. I'll remove the PPA from the README until the issue is resolved, build it from source until then.

**Comment by BenWiederhake** [comment]
PLEASE UNINSTALL THE OUTDATED DEBIAN VERSION! It contains a critical bug that was fixed in 1.2.4.

I just pushed a new version, so it won't be as bad if someone does the same mistake as you did. Please note that we recommend installing from source, unless you really need the Debian package itself. Currently the branches "master", "dev-1.3.0" should be strongly preferred over debian-master.

**Comment by sewi-cpan** [comment]
Confirmed: Building current master fixed the problem.

You should update the Debian package.

**Comment by meersjo** [comment]
@BenWiederhake Thanks for that information. I'll just build a .deb with the master branch, so it updates automatically when webupd8 gets moving :-)

**Comment by meersjo** [comment]
Hm, debian-master branch was updated 20 hours ago and now claims 1.2.4-2. Wonder why I didn't get that in my initial pull this morning, then...

**Comment by BenWiederhake** [comment]
Well, when I wrote `I just pushed a new version` I really meant that, so 1.2.4-2 simply wasn't available before I pushed :P

webupd8 probably doesn't get moving, and there's a good chance that we'll get this into the Ubuntu main repository. Maybe. Or not. Let's see.
