### ISSUE TITLE
Pidgin crashes if somone sends a GIF (windows and linux)

### ISSUE THREAD

**Issue by TomTheDragon** [majn/telegram-purple#217]
Someone of my buddies wanted to test the new GIF feature and now my Pidgin keeps crashing as soon i load the plugin.

This is from the crash log:
pidgin: structures.c:1205: tglf_fetch_message_media: Zusicherung »0« nicht erfüllt.

I have tested this in Windows 8.1 x64 and on LinuxMint 17.3 x64, its the same in both of them.

**Comment by EionRobb** [comment]
Known issue in 1.2.3 of the plugin, grab a 1.2.4 from http://eion.robbmob.com/telegram/

**Comment by BenWiederhake** [comment]
Closing this as duplicate. Feel free to re-open if the problem persists.
