### ISSUE TITLE
Metacontacs issue?

### ISSUE THREAD

**Issue by Megachip** [majn/telegram-purple#219]
After upgrading the adium Plugin from version ??? (see issue #209) to 1.2.4, all contacts are unlinked. Didn't know if it has something to do thats contacts now stored/shown with name instead of uid?

**Comment by majn** [comment]
If by Metacontacts you mean merged contacts, yes this was caused by the change to human-readable user names. Your contact merges were one victim of that (unfortunately really necessary) switch.
