### ISSUE TITLE
No old messages shown

### ISSUE THREAD

**Issue by Airon90** [majn/telegram-purple#227]
Hi. I just installed telegram-purple but it doesn't show old messages of all conversations.
Is it a bug, is it wanted or do I have to set something up?
Thank you

**Comment by majn** [comment]
Its a limitation of Pidgin / libpurple. 

The only option would be to fetch the whole message history at once on first login, which would be awfully slow in most cases and freeze the client for minutes till everything is loaded.

**Comment by Airon90** [comment]
Thank you for your answers!
