### ISSUE TITLE
No group shown

### ISSUE THREAD

**Issue by Airon90** [majn/telegram-purple#228]
Hi. I just installed telegram-purple but it doesn't show groups I take part.
Is it a bug, is it wanted or do I have to set something up, as it is the first time I use Empathy?
Thank you

**Comment by majn** [comment]
Empathy doesn't support libpurple plugins natively, telepathy-haze can be used for loading them but many features will not work. Use a some native Empathy plugin like telepathy-morse.

In Pidgin you can join chat rooms as described in the FAQ: https://developer.pidgin.im/wiki/Using%20Pidgin#HowdoIjoinanexistingchatroom

**Comment by Airon90** [comment]
Thank you for your answer!

**Comment by EionRobb** [comment]
Telepathy haze doesn't support libpurple group chats, it only works with one to one IMs
