### ISSUE TITLE
combined contacts priority doesn't work

### ISSUE THREAD

**Issue by powerman** [majn/telegram-purple#232]
When several contacts of same person with different protocols are combines in single entry in contact list it's usually possible to choose which protocol will be used by default (it's icon shown aside of that contact and conversation using that protocol opens on click on that contact) by re-ordering protocols inside that contact entry (after "expand"-ing it).

This works for all protocols except Telegram - even if contact with telegram protocol is first one in expanded contacts list I still see some other protocol (skype, for example) icon aside of collapsed contact and that other protocol opens when I click on that contact.

**Comment by BenWiederhake** [comment]
Can you "unfold" a combined contact and send us a screenshot?

I believe this is some kind of interference with the fallback system, i.e., if the other human is offline in the top-priority protocol, but online in the other, then pidgin will (of course) choose the "other". So my guess is that your friend is "Online (Mobile)" in Telegram, but "Online" (without any restrictions) in the other protocol.

**Comment by powerman** [comment]
![contact](https://cloud.githubusercontent.com/assets/1354301/13167918/732f050a-d6e0-11e5-9f06-6832d6188f19.png)

**Comment by EionRobb** [comment]
Buddies marked as 'mobile' will display with a lower priority in a combined contact than any other buddy, in Pidgin.

**Comment by majn** [comment]
@EionRobb interesting, your libpurple background knowledge is always helpful and appreciated.

In that case I think that the current behavior is perfectly fine. When someone is online in Skype or any other IM it usually means that he is using this device right now. If he is "mobile" in Telegram it means that the message would reach the phone which might be in stand-by in the pocket . If someone is using Telegram on the desktop application, or has the application open right now, the user should be marked as online and it behaves exactly like any IM.

I wouldn't know how to change this behavior anyways, so I will close this issue now. If you have any "objections" feel free to reopen it.
