### ISSUE TITLE
Feature request: Mark people as away when they are not active

### ISSUE THREAD

**Issue by Phoenix616** [majn/telegram-purple#234]
Currently it is very difficult to distinguish people who are actually online/have been active from those which haven't been active in a while. 

Maybe people which haven't been active in the last X minutes (not sure if this should be configurable or directly read out the idle time you have set for yourself personally) could be set to being away?

**Comment by majn** [comment]
>Currently it is very difficult to distinguish people who are actually online
People that are currently online are marked as online, all others have the state "mobile".

**Comment by Phoenix616** [comment]
Yeah, I noticed that but I find that it is hard to differentiate between active (purple) telegram users and the ones that just check it once a day. This enhancement is also somewhat related to my other issue #235 is it's extremely noticeable when you have contacts that both use this plugin and other protocols simultaneously.

**Comment by BenWiederhake** [comment]
This is already implemented in [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
Of course, Pull Requests are still very much welcome!

**Comment by Phoenix616** [comment]
Why close them though? Then nobody will easily see what could potentially
be implemented even if they wanted to PR...

**Comment by BenWiederhake** [comment]
https://github.com/majn/telegram-purple/issues?q=label%3Aenhancement+is%3Aclosed
https://github.com/majn/telegram-purple/issues?q=label%3A%22help+wanted%22

They are only "closed", not deleted.

**Comment by Phoenix616** [comment]
> They are only "closed", not deleted.

Well usually tickets that are closed are considered "finished" or
"rejected". I highly doubt having to click through every closed ticket just
to find the ones that aren't actually resolved will easily incentive people
to work on stuff.
