### ISSUE TITLE
Pidgin crashes on exit (SIGSEGV)

### ISSUE THREAD

**Issue by spaeps** [majn/telegram-purple#238]
Probably referenced to a **bug** previously reported by @majn ([here](https://github.com/vysheng/tgl/issues/42))

Pidgin crashes while exiting ([here](https://gist.github.com/anonymous/f81a4b8ecd5058f7f080) is a gdb dump).

**M->photo** in function **tgls_free_message_media()** may be **NULL**
while calling **tgls_free_photo(TLS, M->photo)** at [line 1969](https://github.com/majn/tgl/blob/test/structures.c#L1969).

A simple null-checking on **M->photo** before calling **tgls_free_photo()**,
solves. ([here](https://gist.github.com/anonymous/4c6742d1d4af44837c78) is the **patch**).

**Comment by BenWiederhake** [comment]
Wow! This is a nice bug report, thanks :D

I'll first wait a few days on @majn, and if he seems busy, I'll push this directly.

**Comment by ramin65** [comment]
tnk you :D

**Comment by majn** [comment]
Thats actually a bug in libtgl, someone needs to do a pull request with the patch. I'll do it if I find the time.

**Comment by majn** [comment]
Fix is pushed on master
