### ISSUE TITLE
Group chat invite hash expired

### ISSUE THREAD

**Issue by SwooshyCueb** [majn/telegram-purple#243]
The invite hash in the link in the readme for the group chat is expired.

**Comment by BenWiederhake** [comment]
Doesn't look like it to me.

What precisely does the error message say?

**Comment by SwooshyCueb** [comment]
https://paste.weasyldev.com/show/UpOzE5S3NaoguMEXv9nc/

**Comment by majn** [comment]
Fixes, thanks
