### ISSUE TITLE
Group chats join error

### ISSUE THREAD

**Issue by Myppomeu** [majn/telegram-purple#247]
Debian 8 x64, 3.16.0-4-amd64, libpurple 2.10.11-1, pidgin 2.10.11-1, telegram-purple df29bbc from git.

Trying to join group chat by inserting invite link:

> (15:39:34) prpl-telegram: tgprpl_chat_join()
> (15:39:34) prpl-telegram: Sent query #6254805449431075840 of size 40 to DC 2
> (15:39:34) prpl-telegram: error for query #6254805449431075840: #420 FLOOD_WAIT_60 (HANDLED)
> (15:39:38) prpl-telegram: update 0x1bfbd823 (check=0)

Trying to join chat by clicking on it in roster:

> (15:37:59) g_log: purple_find_conversation_with_account: assertion 'name != NULL' failed
> (15:37:59) prpl-telegram: tgprpl_chat_join()
> (15:37:59) prpl-telegram: Sent query #6254805042260855808 of size 40 to DC 2
> (15:37:59) prpl-telegram: error for query #6254805042260855808: #420 FLOOD_WAIT_155 (HANDLED)
> (15:38:00) GLib: Source ID 1780 was not found when attempting to remove it

In both cases pidgin does not joining group chat.

**Comment by majn** [comment]
FLOOD_WAIT means you made too many requests and the server wont accept messages from you for a certain amount of seconds.

**Comment by Myppomeu** [comment]
Tried again.
Join with tg:// link:

> (16:22:24) prpl-telegram: tgprpl_chat_join()
> (16:22:24) prpl-telegram: Sent query #6254816483471760384 of size 40 to DC 2
> (16:22:24) prpl-telegram: error for query 'forward messages' #6254816483471760384: #400 INVITE_HASH_INVALID
> (16:22:24) prpl-telegram: 71: RPC_CALL_FAIL 400: INVITE_HASH_INVALID

Join with https://telegram.me/joinchat/ link:

> (16:23:02) prpl-telegram: tgprpl_chat_join()
> (16:23:02) prpl-telegram: Sent query #6254816647001874432 of size 28 to DC 2
> (16:23:02) prpl-telegram: error for query 'forward messages' #6254816647001874432: #400 USER_ALREADY_PARTICIPANT
> (16:23:02) prpl-telegram: 71: RPC_CALL_FAIL 400: USER_ALREADY_PARTICIPANT

Chat appears in android telegram client. I leave it and add chat in pidgin and open it:

> (16:28:58) prpl-telegram: tgprpl_chat_info_defaults()
> (16:29:07) GLib: g_markup_escape_text: assertion 'text != NULL' failed
> (16:29:10) g_log: purple_find_conversation_with_account: assertion 'name != NULL' failed
> (16:29:10) GLib: g_markup_escape_text: assertion 'text != NULL' failed
> (16:29:10) GLib: g_markup_escape_text: assertion 'text != NULL' failed
> (16:29:10) GLib: g_markup_escape_text: assertion 'text != NULL' failed
> (16:29:11) GLib: g_markup_escape_text: assertion 'text != NULL' failed
> (16:29:11) util: Writing file blist.xml to directory /home/ilia/.purple
> (16:29:11) util: Writing file /home/ilia/.purple/blist.xml
> (16:29:12) g_log: purple_find_conversation_with_account: assertion 'name != NULL' failed
> (16:29:12) prpl-telegram: tgprpl_chat_join()
> (16:29:12) prpl-telegram: Sent query #6254818235671138304 of size 28 to DC 2
> (16:29:12) prpl-telegram: update 0x4e90bfd6 (check=0)
> (16:29:12) prpl-telegram: update 0xb6d45656 (check=0)
> (16:29:12) prpl-telegram: update 0x4214f37f (check=0)
> (16:29:12) prpl-telegram: update 0x1bfbd823 (check=0)
> (16:29:17) GLib: Source ID 2575 was not found when attempting to remove it

Chat appears again in android telegram client. I leave it again and tried to join with https://telegram.me/joinchat/ link again:

> (16:31:05) prpl-telegram: tgprpl_chat_info_defaults()
> (16:31:10) prpl-telegram: tgprpl_chat_join()
> (16:31:10) prpl-telegram: Sent query #6254818742906355712 of size 28 to DC 2
> (16:31:10) prpl-telegram: update 0x4e90bfd6 (check=0)
> (16:31:10) prpl-telegram: update 0xb6d45656 (check=0)
> (16:31:10) prpl-telegram: update 0x4214f37f (check=0)

In every case I was not able to join chat with pidgin.

**Comment by majn** [comment]
Is the chat a channel / supergroup?

**Comment by Myppomeu** [comment]
It is exactly not a channel. How can I discover is that a supergroup? [Link of the group](https://telegram.me/joinchat/CUN0cz1SiYlFhpft1dRZ9g).

**Comment by majn** [comment]
It has to be one, there are more than 200 users. Supergroups aren't supported, in 1.2.5, which is why they don't show up, but you are already member.

**Comment by Myppomeu** [comment]
Does implementation in roadmap?
And is there a way to join groupchats in any xmpp-client (Gajim, for example), if telegram-purple acts like a transport backend for xmpp-server (ejabberd, for example)?

**Comment by majn** [comment]
> Does implementation in roadmap?

yes https://github.com/majn/telegram-purple/issues?q=is%3Aissue+is%3Aopen+label%3Ain-pipeline

**Comment by majn** [comment]
>And is there a way to join groupchats in any xmpp-client (Gajim, for example), if telegram-purple acts like a transport backend for xmpp-server (ejabberd, for example)?

I lack the XMPP knowledge to answer that question, AFAIK you can use tgp as libpurple module with Spectrum2 but I never tested it myself.

**Comment by Myppomeu** [comment]
Thanks for the answers!

> AFAIK you can use tgp as libpurple module with Spectrum2 but I never tested it myself

Yes, I connected telegram-purple as a module of libpurple and configured Spetrum2 (and it works for simple chats), but can't find a way wich I can use groupchats

**Comment by james2390** [comment]
Suggestions for good crypto/bitcoin groups & chats. Follow the link below to subscribe for my telegram channel for free daily trade tips and more  https://t.me/james_etradingsolution 🙏
