### ISSUE TITLE
make error in debian wheezy

### ISSUE THREAD

**Issue by susobaco** [majn/telegram-purple#25]
This is the error in the "make"

make
make: **\* No hay ninguna regla para construir el objetivo `tgl/scheme.tl', necesario para`auto/scheme.tl'.  Alto.

There is no rule to build the target `tgl/scheme.tl' necessary for`auto/scheme.tl'.  Stop

**Comment by oscarmlage** [comment]
@susobaco have you been able to make a debian wheezy .deb? trying to compile it says to me that  libgcrypt >= 1.60 is needed and afaik it's not available for wheezy, am I wrong? thank you in advance.

**Comment by majn** [comment]
@oscarmlage https://launchpad.net/debian/wheezy/+source/libgcrypt20

>trying to compile it says to me that libgcrypt >= 1.60 is needed and afaik it's not available for wheezy, am I wrong
yes, that seems to be the case. We definitely need libgcrypt20, due to the many ABI changes that happened compared to earlier versions http://upstream.rosalinux.ru/versions/libgcrypt.html
