### ISSUE TITLE
The pictures don't appear

### ISSUE THREAD

**Issue by perayknox** [majn/telegram-purple#252]
Is it for everyone or just for me?

(Please look up to first line. You can see the white space. Actually, there is an image when I'm looked up from Telegram.)

![tt](https://cloud.githubusercontent.com/assets/13890542/13750878/19ecc2dc-ea10-11e5-8748-2f871b74b64e.png)

**Comment by majn** [comment]
Disable the "conversation colors" plugin. If its not enabled there might be some other plugin messing up inline html.

**Comment by perayknox** [comment]
It worked. Is there any way to use them together? And thanks for that great plugin.

**Comment by majn** [comment]
Unfortunately no, since the plugin will simply strip all HTML from messages. Also please read the FAQ next time.
