### ISSUE TITLE
Adium crashes at startup

### ISSUE THREAD

**Issue by Phosphor303** [majn/telegram-purple#26]
Yesterday Adium crashed without any apparent reason. I was not chatting with any Telegram contact, but with other contacts. Since then Adium crashes directly at restarting the application as long as the Telegram plugin is installed.

Here is the crash report from the latest try to start Adium with the plugin installed: https://gist.github.com/Phosphor303/11b8fd35fda9ceeca8cc

**Comment by BenWiederhake** [comment]
Doesn't look active anymore, most likely already fixed.
