### ISSUE TITLE
MPEG4 animation support

### ISSUE THREAD

**Issue by TomTheDragon** [majn/telegram-purple#263]
I was just wondering if GIF support is planned to implement into the plugin or is it impossible because of the Pidgin side?

**Comment by majn** [comment]
Gif used to be supported. mpeg4 however, to which Telegram now converts all gifs on server side isnt supported by Pidgin.

**Comment by BenWiederhake** [comment]
Ironically, this would resolve itself once libpurple3 lands ( #366 ) with support for gstreamer 1.0.

**Comment by BenWiederhake** [comment]
This is already implemented in [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
Of course, Pull Requests are still very much welcome!
