### ISSUE TITLE
Bots with keyboards

### ISSUE THREAD

**Issue by Phyks** [majn/telegram-purple#270]
Hi,

I am using telegram-purple in Bitlbee, and am using some bots which are using a custom keyboard with buttons to interact with them. Such keyboard is not replicated in bitlbee (of course), and then the bot is really hard to use, as we have to guess which input it is expected.

Is there something that could be done to improve this user experience?

Thanks!

**Comment by majn** [comment]
What do you mean with custom keyboard? The command-list to choose from?

**Comment by Phyks** [comment]
Yes, the command list to choose from (buttons at the bottom of the screen in Telegram). Check out the bot from https://laprimaire.org/ for instance (sorry in French, and with my poor connection at the moment, I cannot take and send any screenshot…).

Let me know if you need more infos, if I needed I will update this issue whenever I recover a decent connection.

Thanks

**Comment by BenWiederhake** [comment]
Closing in favor of #355, since I think it has a better description of the problem.  We're still interested in having a nice UI for that, though!
