### ISSUE TITLE
Create a Chocolatey purple-telegram package

### ISSUE THREAD

**Issue by nkrepo** [majn/telegram-purple#271]
It would be very useful for delivering updates to create a Chocolatey purple-telegram package.

**Comment by BenWiederhake** [comment]
Sounds interesting, although Ihaven't heard of this project yet. It sounds a bit more comfortable than pulling the `.exe` from [Robb's prebuilt files](http://eion.robbmob.com/telegram/).

**Comment by majn** [comment]
I won't do it myself cause I lack the knowledge about this issue, but if anyone is interested: go for it.

**Comment by nkrepo** [comment]
It is better that the software author creates and publishes the package.
There already the purple-facebook plugin you can take a look there how the package is build.
https://chocolatey.org/packages/purple-facebook.
https://github.com/dequis/purple-facebook

It seems that for zip only packages it reduces, to a couple powershell scripts and xml files.
https://github.com/chocolatey/choco/wiki/CreatePackages
A probably outdated tutorial
https://www.topbug.net/blog/2012/07/02/a-simple-tutorial-create-and-publish-chocolatey-packages/

**Comment by EionRobb** [comment]
Although the purple-facebook chocolately package isn't created or published by the purple-facebook plugin author's ;)

**Comment by nkrepo** [comment]
Indeed, but that way, it is easier to eventually elevate to a "Trusted Package"
https://github.com/chocolatey/choco/wiki/ChocolateyFAQs#what-is-a-trusted-package

**Comment by majn** [comment]
Well I don't have the resources to do it myself, I usually try to keep the packaging effort away from me, so I can implement more features :)

**Comment by BenWiederhake** [comment]
@nkrepo: It should be possible to create the package and then make a PR, *hint hint*

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
