### ISSUE TITLE
Extremely high CPU usage when switching tabs

### ISSUE THREAD

**Issue by notnsane** [majn/telegram-purple#273]
Just switching tabs between Telegram users raises Pidgin CPU usage up to 25%.
If I have "Buddy Details" enabled, usage is even higher.
This issues doesn't happen with Group Chat users.

I've made a video of this issue, watch it here: https://a.pomf.cat/kndglr.mp4

Version: telegram-purple v 1.2.6
Where: http://eion.robbmob.com/telegram/
Pidgin: 2.10.12, Portable
OS: Windows 10 x64 latest stable (Threshold 2)

**Comment by majn** [comment]
Does that happen with other protocols too?

Seems like more of a general Pidgin issue and nothing caused by a protocol plugin.

**Comment by BenWiederhake** [comment]
Apparently it's not important, not reproducible, not due to telegram-purple, or a combination of these.
