### ISSUE TITLE
WHAT does this mean?

### ISSUE THREAD

**Issue by thundergreen** [majn/telegram-purple#275]
21547: 2016-05-12 22:56:30,648 INFO  libpurple: prpl-telegram:work_new_session_created: msg_id = 6283909057931430913, dc = 2
21547: 2016-05-12 22:56:30,658 INFO  libpurple: prpl-telegram:adjusting CLOCK_MONOTONIC delta to -56.995280
21547: 2016-05-12 22:56:30,658 INFO  libpurple: prpl-telegram:work_new_session_created: msg_id = 6283909058003942401, dc = 4
21547: 2016-05-12 22:56:30,672 INFO  libpurple: prpl-telegram:DC1 '' update: 2001:0b28:f23d:f001:0000:0000:0000:000a:443
21547: 2016-05-12 22:56:30,672 INFO  libpurple: prpl-telegram:DC2 '' update: 2001:067c:04e8:f002:0000:0000:0000:000a:443
21547: 2016-05-12 22:56:30,672 INFO  libpurple: prpl-telegram:DC3 '' update: 2001:0b28:f23d:f003:0000:0000:0000:000a:443
21547: 2016-05-12 22:56:30,672 INFO  libpurple: prpl-telegram:DC4 '' update: 2001:067c:04e8:f004:0000:0000:0000:000a:443
21547: 2016-05-12 22:56:30,672 INFO  libpurple: prpl-telegram:DC4 '' update: 149.154.165.120:443
21547: 2016-05-12 22:56:30,672 INFO  libpurple: prpl-telegram:DC5 '' update: 91.108.56.165:443
21547: 2016-05-12 22:56:30,672 INFO  libpurple: prpl-telegram:DC5 '' update: 2001:0b28:f23f:f005:0000:0000:0000:000a:443
21700: 2016-05-12 22:57:53,976 INFO  backend: Setting libpurple plugins directory to: ./plugins
21700: 2016-05-12 22:57:53,977 INFO  backend: Setting libpurple cacerts directory to: ./ca-certs
21700: 2016-05-12 22:57:53,977 INFO  backend: Setting libpurple user directory to: /var/lib/spectrum2/telegram.emevth.no-ip.biz
21700: 2016-05-12 22:57:53,977 INFO  backend: Will use glib based event loop
21700: 2016-05-12 22:57:53,978 INFO  libpurple: prefs:Reading /var/lib/spectrum2/telegram.emevth.no-ip.biz/prefs.xml
21700: 2016-05-12 22:57:53,979 INFO  libpurple: prefs:Finished reading /var/lib/spectrum2/telegram.emevth.no-ip.biz/prefs.xml
21700: 2016-05-12 22:57:53,980 INFO  libpurple: dbus:Failed to get connection: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
21700: 2016-05-12 22:57:53,980 INFO  libpurple: plugins:probing /usr/lib/purple-2/libzephyr.so
21700: 2016-05-12 22:57:53,984 INFO  libpurple: plugins:probing /usr/lib/purple-2/libmsn.so
21700: 2016-05-12 22:57:53,990 INFO  libpurple: plugins:probing /usr/lib/purple-2/liboscar.so
21700: 2016-05-12 22:57:53,994 INFO  libpurple: plugins:/usr/lib/purple-2/liboscar.so is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INIT_PLUGIN() macro?
21700: 2016-05-12 22:57:53,994 INFO  libpurple: plugins:probing /usr/lib/purple-2/libaim.so
21700: 2016-05-12 22:57:53,999 INFO  libpurple: plugins:probing /usr/lib/purple-2/dbus-example.so
21700: 2016-05-12 22:57:54,001 INFO  libpurple: plugins:probing /usr/lib/purple-2/libwhatsapp.so
21700: 2016-05-12 22:57:54,084 INFO  libpurple: plugins:probing /usr/lib/purple-2/joinpart.so
21700: 2016-05-12 22:57:54,086 INFO  libpurple: plugins:probing /usr/lib/purple-2/tcl.so
21700: 2016-05-12 22:57:54,135 INFO  libpurple: plugins:probing /usr/lib/purple-2/libxmpp.so
21700: 2016-05-12 22:57:54,144 INFO  libpurple: plugins:probing /usr/lib/purple-2/libskypeweb.so
21700: 2016-05-12 22:57:54,148 INFO  libpurple: plugins:probing /usr/lib/purple-2/perl.so
21700: 2016-05-12 22:57:54,165 INFO  libpurple: plugins:probing /usr/lib/purple-2/libyahoo.so
21700: 2016-05-12 22:57:54,169 INFO  libpurple: plugins:probing /usr/lib/purple-2/libbonjour.so
21700: 2016-05-12 22:57:54,176 INFO  libpurple: plugins:probing /usr/lib/purple-2/libirc.so
21700: 2016-05-12 22:57:54,179 INFO  libpurple: plugins:probing /usr/lib/purple-2/libymsg.so
21700: 2016-05-12 22:57:54,180 INFO  libpurple: plugins:/usr/lib/purple-2/libymsg.so is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INIT_PLUGIN() macro?
21700: 2016-05-12 22:57:54,180 INFO  libpurple: plugins:probing /usr/lib/purple-2/log_reader.so
21700: 2016-05-12 22:57:54,182 INFO  libpurple: plugins:probing /usr/lib/purple-2/libsimple.so
21700: 2016-05-12 22:57:54,184 INFO  libpurple: plugins:probing /usr/lib/purple-2/libnovell.so
21700: 2016-05-12 22:57:54,187 INFO  libpurple: plugins:probing /usr/lib/purple-2/libyahoojp.so
21700: 2016-05-12 22:57:54,189 INFO  libpurple: plugins:probing /usr/lib/purple-2/libicq.so
21700: 2016-05-12 22:57:54,191 INFO  libpurple: plugins:probing /usr/lib/purple-2/nss-prefs.so
21700: 2016-05-12 22:57:54,215 INFO  libpurple: plugins:probing /usr/lib/purple-2/libsametime.so
21700: 2016-05-12 22:57:54,221 INFO  libpurple: plugins:/usr/lib/purple-2/libsametime.so has a prefs_info, but is a prpl. This is no longer supported.
21700: 2016-05-12 22:57:54,221 INFO  libpurple: plugins:probing /usr/lib/purple-2/libmxit.so
21700: 2016-05-12 22:57:54,225 INFO  libpurple: prpl-loubserp-mxit:Loading MXit libPurple plugin...
21700: 2016-05-12 22:57:54,225 INFO  libpurple: plugins:probing /usr/lib/purple-2/ssl.so
21700: 2016-05-12 22:57:54,226 INFO  libpurple: plugins:probing /usr/lib/purple-2/autoaccept.so
21700: 2016-05-12 22:57:54,228 INFO  libpurple: plugins:probing /usr/lib/purple-2/telegram-purple.so
21700: 2016-05-12 22:57:54,256 INFO  libpurple: plugins:probing /usr/lib/purple-2/libmyspace.so
21700: 2016-05-12 22:57:54,258 INFO  libpurple: plugins:probing /usr/lib/purple-2/libjabber.so
21700: 2016-05-12 22:57:54,259 INFO  libpurple: plugins:/usr/lib/purple-2/libjabber.so is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INIT_PLUGIN() macro?
21700: 2016-05-12 22:57:54,260 INFO  libpurple: plugins:probing /usr/lib/purple-2/offlinemsg.so
21700: 2016-05-12 22:57:54,261 INFO  libpurple: plugins:probing /usr/lib/purple-2/ssl-nss.so
21700: 2016-05-12 22:57:54,265 INFO  libpurple: plugins:probing /usr/lib/purple-2/newline.so
21700: 2016-05-12 22:57:54,266 INFO  libpurple: plugins:probing /usr/lib/purple-2/statenotify.so
21700: 2016-05-12 22:57:54,268 INFO  libpurple: plugins:probing /usr/lib/purple-2/libfacebook.so
21700: 2016-05-12 22:57:54,273 INFO  libpurple: plugins:probing /usr/lib/purple-2/libgg.so
21700: 2016-05-12 22:57:54,276 INFO  libpurple: plugins:probing /usr/lib/purple-2/buddynote.so
21700: 2016-05-12 22:57:54,277 INFO  libpurple: plugins:probing /usr/lib/purple-2/idle.so
21700: 2016-05-12 22:57:54,278 INFO  libpurple: plugins:probing /usr/lib/purple-2/psychic.so
21700: 2016-05-12 22:57:54,333 INFO  libpurple: util:Reading file xmpp-caps.xml from directory /var/lib/spectrum2/telegram.emevth.no-ip.biz
21700: 2016-05-12 22:57:54,333 INFO  libpurple: util:File /var/lib/spectrum2/telegram.emevth.no-ip.biz/xmpp-caps.xml does not exist (this is not necessarily an error)
21700: 2016-05-12 22:57:54,333 INFO  libpurple: jabber:creating hash tables for data objects
21700: 2016-05-12 22:57:54,335 INFO  libpurple: gg:Loading Gadu-Gadu protocol plugin with libgadu 1.12.0...
21700: 2016-05-12 22:57:54,335 INFO  libpurple: prefs:/purple/status/scores/offline changed, scheduling save.
21700: 2016-05-12 22:57:54,335 INFO  libpurple: prefs:/purple/status/scores/available changed, scheduling save.
21700: 2016-05-12 22:57:54,335 INFO  libpurple: prefs:/purple/status/scores/invisible changed, scheduling save.
21700: 2016-05-12 22:57:54,335 INFO  libpurple: prefs:/purple/status/scores/away changed, scheduling save.
21700: 2016-05-12 22:57:54,335 INFO  libpurple: prefs:/purple/status/scores/extended_away changed, scheduling save.
21700: 2016-05-12 22:57:54,335 INFO  libpurple: prefs:/purple/status/scores/idle changed, scheduling save.
21700: 2016-05-12 22:57:54,335 INFO  libpurple: prefs:/purple/status/scores/offline_msg changed, scheduling save.
21700: 2016-05-12 22:57:54,335 INFO  libpurple: util:Reading file accounts.xml from directory /var/lib/spectrum2/telegram.emevth.no-ip.biz
21700: 2016-05-12 22:57:54,335 INFO  libpurple: util:File /var/lib/spectrum2/telegram.emevth.no-ip.biz/accounts.xml does not exist (this is not necessarily an error)
21700: 2016-05-12 22:57:54,336 INFO  libpurple: util:Reading file status.xml from directory /var/lib/spectrum2/telegram.emevth.no-ip.biz
21700: 2016-05-12 22:57:54,336 INFO  libpurple: util:File /var/lib/spectrum2/telegram.emevth.no-ip.biz/status.xml does not exist (this is not necessarily an error)
21700: 2016-05-12 22:57:54,336 INFO  libpurple: certificate:CertificateVerifier x509, singleuse requested but not found.
21700: 2016-05-12 22:57:54,336 INFO  libpurple: certificate:CertificateVerifier singleuse registered
21700: 2016-05-12 22:57:54,336 INFO  libpurple: certificate:CertificatePool x509, ca requested but not found.
21700: 2016-05-12 22:57:54,336 INFO  libpurple: certificate:CertificateScheme x509 requested but not found.
21700: 2016-05-12 22:57:54,336 INFO  libpurple: certificate/x509/ca:Lazy init failed because an X.509 Scheme is not yet registered. Maybe it will be better later.
21700: 2016-05-12 22:57:54,336 INFO  libpurple: certificate/x509/ca:Init failed, probably because a dependency is not yet registered. It has been deferred to later.
21700: 2016-05-12 22:57:54,336 INFO  libpurple: certificate:CertificatePool ca registered
21700: 2016-05-12 22:57:54,336 INFO  libpurple: certificate:CertificatePool x509, tls_peers requested but not found.
21700: 2016-05-12 22:57:54,336 INFO  libpurple: certificate:CertificatePool tls_peers registered
21700: 2016-05-12 22:57:54,336 INFO  libpurple: certificate:CertificateVerifier x509, tls_cached requested but not found.
21700: 2016-05-12 22:57:54,336 INFO  libpurple: certificate:CertificateVerifier tls_cached registered
21700: 2016-05-12 22:57:54,337 INFO  libpurple: prefs:/purple/logging/format changed, scheduling save.
21700: 2016-05-12 22:57:54,337 INFO  libpurple: prefs:/purple/logging/format changed, scheduling save.
21700: 2016-05-12 22:57:54,344 INFO  libpurple: prefs:/purple/proxy/type changed, scheduling save.
21700: 2016-05-12 22:57:54,344 INFO  libpurple: prefs:/purple/proxy/host changed, scheduling save.
21700: 2016-05-12 22:57:54,344 INFO  libpurple: prefs:/purple/proxy/port changed, scheduling save.
21700: 2016-05-12 22:57:54,344 INFO  libpurple: prefs:/purple/proxy/username changed, scheduling save.
21700: 2016-05-12 22:57:54,345 INFO  libpurple: prefs:/purple/proxy/password changed, scheduling save.
21700: 2016-05-12 22:57:54,356 INFO  libpurple: nss:Cipher - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256: Enabled
21700: 2016-05-12 22:57:54,356 INFO  libpurple: nss:Cipher - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256: Enabled
21700: 2016-05-12 22:57:54,356 INFO  libpurple: nss:Cipher - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA: Enabled
21700: 2016-05-12 22:57:54,356 INFO  libpurple: nss:Cipher - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA: Enabled
21700: 2016-05-12 22:57:54,356 INFO  libpurple: nss:Cipher - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA: Enabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256: Disabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256: Enabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA: Enabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_ECDHE_ECDSA_WITH_RC4_128_SHA: Enabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_ECDHE_RSA_WITH_RC4_128_SHA: Enabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_DHE_RSA_WITH_AES_128_GCM_SHA256: Enabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_DHE_RSA_WITH_AES_128_CBC_SHA: Enabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_DHE_DSS_WITH_AES_128_CBC_SHA: Enabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_DHE_RSA_WITH_AES_128_CBC_SHA256: Enabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_DHE_RSA_WITH_AES_256_CBC_SHA: Enabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_DHE_DSS_WITH_AES_256_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_DHE_RSA_WITH_AES_256_CBC_SHA256: Enabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_DHE_DSS_WITH_RC4_128_SHA: Disabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,357 INFO  libpurple: nss:Cipher - TLS_ECDH_RSA_WITH_AES_128_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - TLS_ECDH_RSA_WITH_AES_256_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - TLS_ECDH_ECDSA_WITH_RC4_128_SHA: Disabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - TLS_ECDH_RSA_WITH_RC4_128_SHA: Disabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_AES_128_GCM_SHA256: Disabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_AES_128_CBC_SHA: Enabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_AES_128_CBC_SHA256: Disabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_CAMELLIA_128_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_AES_256_CBC_SHA: Enabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_AES_256_CBC_SHA256: Disabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_CAMELLIA_256_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_SEED_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - SSL_RSA_FIPS_WITH_3DES_EDE_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_3DES_EDE_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_RC4_128_SHA: Disabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_RC4_128_MD5: Disabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - TLS_DHE_RSA_WITH_DES_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - TLS_DHE_DSS_WITH_DES_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - SSL_RSA_FIPS_WITH_DES_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,358 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_DES_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,359 INFO  libpurple: nss:Cipher - TLS_RSA_EXPORT1024_WITH_RC4_56_SHA: Disabled
21700: 2016-05-12 22:57:54,359 INFO  libpurple: nss:Cipher - TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA: Disabled
21700: 2016-05-12 22:57:54,359 INFO  libpurple: nss:Cipher - TLS_RSA_EXPORT_WITH_RC4_40_MD5: Disabled
21700: 2016-05-12 22:57:54,359 INFO  libpurple: nss:Cipher - TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5: Disabled
21700: 2016-05-12 22:57:54,359 INFO  libpurple: nss:Cipher - TLS_ECDHE_ECDSA_WITH_NULL_SHA: Disabled
21700: 2016-05-12 22:57:54,359 INFO  libpurple: nss:Cipher - TLS_ECDHE_RSA_WITH_NULL_SHA: Disabled
21700: 2016-05-12 22:57:54,359 INFO  libpurple: nss:Cipher - TLS_ECDH_RSA_WITH_NULL_SHA: Disabled
21700: 2016-05-12 22:57:54,359 INFO  libpurple: nss:Cipher - TLS_ECDH_ECDSA_WITH_NULL_SHA: Disabled
21700: 2016-05-12 22:57:54,359 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_NULL_SHA: Disabled
21700: 2016-05-12 22:57:54,359 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_NULL_SHA256: Disabled
21700: 2016-05-12 22:57:54,359 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_NULL_MD5: Disabled
21700: 2016-05-12 22:57:54,359 INFO  libpurple: nss:Cipher - SSL_CK_RC4_128_WITH_MD5: Disabled
21700: 2016-05-12 22:57:54,359 INFO  libpurple: nss:Cipher - SSL_CK_RC2_128_CBC_WITH_MD5: Disabled
21700: 2016-05-12 22:57:54,359 INFO  libpurple: nss:Cipher - SSL_CK_DES_192_EDE3_CBC_WITH_MD5: Disabled
21700: 2016-05-12 22:57:54,359 INFO  libpurple: nss:Cipher - SSL_CK_DES_64_CBC_WITH_MD5: Disabled
21700: 2016-05-12 22:57:54,359 INFO  libpurple: nss:Cipher - SSL_CK_RC4_128_EXPORT40_WITH_MD5: Disabled
21700: 2016-05-12 22:57:54,359 INFO  libpurple: nss:Cipher - SSL_CK_RC2_128_CBC_EXPORT40_WITH_MD5: Disabled
21700: 2016-05-12 22:57:54,359 INFO  libpurple: nss:TLS supported versions: 0x0300 through 0x0303
21700: 2016-05-12 22:57:54,359 INFO  libpurple: nss:TLS versions allowed by default: 0x0300 through 0x0301
21700: 2016-05-12 22:57:54,359 INFO  libpurple: nss:Changed allowed TLS versions to 0x0300 through 0x0303
21700: 2016-05-12 22:57:54,360 INFO  libpurple: certificate:CertificateScheme x509 requested but not found.
21700: 2016-05-12 22:57:54,360 INFO  libpurple: certificate:CertificateScheme x509 registered
21700: 2016-05-12 22:57:54,360 INFO  libpurple: util:Reading file smileys.xml from directory /var/lib/spectrum2/telegram.emevth.no-ip.biz
21700: 2016-05-12 22:57:54,360 INFO  libpurple: util:File /var/lib/spectrum2/telegram.emevth.no-ip.biz/smileys.xml does not exist (this is not necessarily an error)
21700: 2016-05-12 22:57:54,360 INFO  libpurple: stun:using server 
21700: 2016-05-12 22:57:54,360 INFO  libpurple: util:Reading file blist.xml from directory /var/lib/spectrum2/telegram.emevth.no-ip.biz
21700: 2016-05-12 22:57:54,361 INFO  libpurple: util:File /var/lib/spectrum2/telegram.emevth.no-ip.biz/blist.xml does not exist (this is not necessarily an error)
21700: 2016-05-12 22:57:54,361 INFO  libpurple: prefs:Reading /var/lib/spectrum2/telegram.emevth.no-ip.biz/prefs.xml
21700: 2016-05-12 22:57:54,362 INFO  libpurple: prefs:/plugins/core/nss_prefs/cipher_list changed, scheduling save.
21700: 2016-05-12 22:57:54,362 INFO  libpurple: prefs:Finished reading /var/lib/spectrum2/telegram.emevth.no-ip.biz/prefs.xml
21700: 2016-05-12 22:57:54,373 INFO  backend: Creating account with name '+33781852856' and protocol 'prpl-telegram'
21700: 2016-05-12 22:57:54,373 INFO  libpurple: prpl-telegram:tgprpl_status_types()
21700: 2016-05-12 22:57:54,374 INFO  libpurple: account:Connecting to account +33781852856.
21700: 2016-05-12 22:57:54,374 INFO  libpurple: connection:Connecting. gc = 0x6b45d0
21700: 2016-05-12 22:57:54,374 INFO  libpurple: prpl-telegram:tgprpl_login(): Purple is telling the prpl to connect the account
21700: 2016-05-12 22:57:54,374 INFO  libpurple: prpl-telegram:base configuration path: '/var/lib/spectrum2/telegram.emevth.no-ip.biz/telegram-purple/+33781852856'
21700: 2016-05-12 22:57:54,374 INFO  libpurple: prpl-telegram:trying global pubkey at /etc/telegram-purple/server.tglpub
21700: 2016-05-12 22:57:54,375 INFO  libpurple: prpl-telegram:read pubkey file: n_len=256 e=65537
21700: 2016-05-12 22:57:54,375 INFO  libpurple: prpl-telegram:using global pubkey
21700: 2016-05-12 22:57:54,376 INFO  libpurple: prpl-telegram:'direct' public key loaded successfully
21700: 2016-05-12 22:57:54,376 INFO  libpurple: prpl-telegram:initializing empty auth file
21700: 2016-05-12 22:57:54,376 INFO  libpurple: prpl-telegram:DC1 '' update: 149.154.175.50:443
21700: 2016-05-12 22:57:54,376 INFO  libpurple: prpl-telegram:DC2 '' update: 149.154.167.51:443
21700: 2016-05-12 22:57:54,376 INFO  libpurple: prpl-telegram:DC3 '' update: 149.154.175.100:443
21700: 2016-05-12 22:57:54,376 INFO  libpurple: prpl-telegram:DC4 '' update: 149.154.167.91:443
21700: 2016-05-12 22:57:54,376 INFO  libpurple: prpl-telegram:DC5 '' update: 149.154.171.5:443
21700: 2016-05-12 22:57:54,478 INFO  libpurple: dnsquery:Performing DNS lookup for 149.154.175.50
21700: 2016-05-12 22:57:54,478 INFO  libpurple: dnsquery:Performing DNS lookup for 149.154.167.51
21700: 2016-05-12 22:57:54,479 INFO  libpurple: dnsquery:Performing DNS lookup for 149.154.175.100
21700: 2016-05-12 22:57:54,479 INFO  libpurple: dnsquery:Performing DNS lookup for 149.154.167.91
21700: 2016-05-12 22:57:54,479 INFO  libpurple: dnsquery:Performing DNS lookup for 149.154.171.5
21700: 2016-05-12 22:57:54,479 INFO  libpurple: dnsquery:IP resolved for 149.154.175.50
21700: 2016-05-12 22:57:54,479 INFO  libpurple: proxy:Attempting connection to 149.154.175.50
21700: 2016-05-12 22:57:54,479 INFO  libpurple: proxy:Connecting to 149.154.175.50:443 with no proxy
21700: 2016-05-12 22:57:54,479 INFO  libpurple: proxy:Connection in progress
21700: 2016-05-12 22:57:54,479 INFO  libpurple: dnsquery:IP resolved for 149.154.167.51
21700: 2016-05-12 22:57:54,479 INFO  libpurple: proxy:Attempting connection to 149.154.167.51
21700: 2016-05-12 22:57:54,479 INFO  libpurple: proxy:Connecting to 149.154.167.51:443 with no proxy
21700: 2016-05-12 22:57:54,480 INFO  libpurple: proxy:Connection in progress
21700: 2016-05-12 22:57:54,480 INFO  libpurple: dnsquery:IP resolved for 149.154.175.100
21700: 2016-05-12 22:57:54,480 INFO  libpurple: proxy:Attempting connection to 149.154.175.100
21700: 2016-05-12 22:57:54,480 INFO  libpurple: proxy:Connecting to 149.154.175.100:443 with no proxy
21700: 2016-05-12 22:57:54,480 INFO  libpurple: proxy:Connection in progress
21700: 2016-05-12 22:57:54,480 INFO  libpurple: dnsquery:IP resolved for 149.154.167.91
21700: 2016-05-12 22:57:54,480 INFO  libpurple: proxy:Attempting connection to 149.154.167.91
21700: 2016-05-12 22:57:54,480 INFO  libpurple: proxy:Connecting to 149.154.167.91:443 with no proxy
21700: 2016-05-12 22:57:54,480 INFO  libpurple: proxy:Connection in progress
21700: 2016-05-12 22:57:54,480 INFO  libpurple: dnsquery:IP resolved for 149.154.171.5
21700: 2016-05-12 22:57:54,480 INFO  libpurple: proxy:Attempting connection to 149.154.171.5
21700: 2016-05-12 22:57:54,480 INFO  libpurple: proxy:Connecting to 149.154.171.5:443 with no proxy
21700: 2016-05-12 22:57:54,480 INFO  libpurple: proxy:Connection in progress
21700: 2016-05-12 22:57:54,519 INFO  libpurple: proxy:Connecting to 149.154.167.51:443.
21700: 2016-05-12 22:57:54,519 INFO  libpurple: proxy:Connected to 149.154.167.51:443.
21700: 2016-05-12 22:57:54,521 INFO  libpurple: prpl-telegram:outbound rpc connection from dc #2 becomed ready
21700: 2016-05-12 22:57:54,524 INFO  libpurple: proxy:Connecting to 149.154.167.91:443.
21700: 2016-05-12 22:57:54,524 INFO  libpurple: proxy:Connected to 149.154.167.91:443.
21700: 2016-05-12 22:57:54,526 INFO  libpurple: prpl-telegram:outbound rpc connection from dc #4 becomed ready
21700: 2016-05-12 22:57:54,633 INFO  libpurple: proxy:Connecting to 149.154.175.50:443.
21700: 2016-05-12 22:57:54,633 INFO  libpurple: proxy:Connected to 149.154.175.50:443.
21700: 2016-05-12 22:57:54,635 INFO  libpurple: proxy:Connecting to 149.154.175.100:443.
21700: 2016-05-12 22:57:54,635 INFO  libpurple: proxy:Connected to 149.154.175.100:443.
21700: 2016-05-12 22:57:54,936 INFO  libpurple: proxy:Connecting to 149.154.171.5:443.
21700: 2016-05-12 22:57:54,936 INFO  libpurple: proxy:Connected to 149.154.171.5:443.
21700: 2016-05-12 22:57:54,938 INFO  libpurple: prpl-telegram:outbound rpc connection from dc #1 becomed ready
21700: 2016-05-12 22:57:54,939 INFO  libpurple: prpl-telegram:outbound rpc connection from dc #3 becomed ready
21700: 2016-05-12 22:57:54,940 INFO  libpurple: prpl-telegram:outbound rpc connection from dc #5 becomed ready
^C

I dont see any error message. i just found:

server error 404

**Comment by BenWiederhake** [comment]
Where does the error message appear, and what was the program trying to do at the time?

**Comment by thundergreen** [comment]
Libpurple error with spectrum2 transport

Thorsten Fröhlich
Am 13.05.2016 07:34 schrieb "Ben Wiederhake" <notifications@github.com>:
