### ISSUE TITLE
Unable to join a group: 71: RPC_CALL_FAIL 400: USER_ALREADY_PARTICIPANT

### ISSUE THREAD

**Issue by kradan** [majn/telegram-purple#277]
What is the proper usage to add a telegram group chat to pidgin via purple-telegram?

When I try to add a telegram chat group via invite link I get the message:

71: RPC_CALL_FAIL 400: USER_ALREADY_PARTICIPANT

Nothing else happens.

Expected behaviour: a tab with the group chat opens and the conversation history is loaded.

Alternatively adding the group by name brings up a window to enter three participant's names, After clicking ok, a new group is created.

Expected behaviour: the existing group with that name is joined.

**Comment by BenWiederhake** [comment]
Thanks for reporting!

Sounds like a duplicate of #122

**Comment by BenWiederhake** [comment]
So, I guess it really *is* a duplicate.
