### ISSUE TITLE
Copy message from other channel

### ISSUE THREAD

**Issue by ashkufaraz** [majn/telegram-purple#278]
Hi
Sorry,I have a question about your project(telegram).
Can I get the message channels that I'm not their admin?
I want write a script that read message from other chanel and write to
my chanel.
I can do it?
best regards
thanks

**Comment by BenWiederhake** [comment]
I see that you have also asked this question on tgl.

You seem to be writing a script.  However, telegram-purple is a plugin for libpurple, which is a really bad idea for scripts.  Your choice of tgl as a starting point is good.  Also look into tg-cli, which is used by some other bot-writers.  I'll close this issue as it is unrelated to telegram-purple.

Of course you can do it with libtgl.  However, I have no idea how to do that, so I won't respond to the other issue or to your private mail (btw: don't send unsolicited direct mails, that's rude).
