### ISSUE TITLE
Display edited messages

### ISSUE THREAD

**Issue by nomeata** [majn/telegram-purple#281]
I expect this to be tricky as a pidgin plugin, but it seems that message edits ([new feature](https://telegram.org/blog/edit) since may) are ignored by telegram-purple. It would be nice if they are handled in some way, even if inelegant.

**Comment by BenWiederhake** [comment]
"Vanilla" libpurple offers no interface to edit existing entries, as far as I know.
Re-displaying the "new" message might be nice, though.

**Comment by EionRobb** [comment]
@BenWiederhake correct, history is immutable in libpurple.  I've struck a balance in other plugins that let you edit content (mainly Skype) with a system message saying "xyz has edited the last message to say foobarwibble"

**Comment by majn** [comment]
There has been a very recent update on editing and deletion features.
libtgl just swallows those at the moment cause it hasn't been updated since july 2016

**Comment by vn971** [comment]
From a UI perspective, I think it would be cool to display the new edited message content then. Would be even better than the behavior of the "stock" client, for some people.

**Comment by ochilan** [comment]
Any updates on this issue? I would like to add that pidgin repeats the last message of the other user for some reason once I send a message and the other user has edited his or her message since. However, I never see the edited version of the message.

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple), which might already have this enhancement. For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
Of course, Pull Requests are still very much welcome!
