### ISSUE TITLE
Crash on image decoding: pointer being freed was not allocated

### ISSUE THREAD

**Issue by ddska** [majn/telegram-purple#284]
Adium with telegram-purple plugin crashed after I received a photo and tried to view it.
Here is the detailed report:
http://pastebin.com/0KyJv0Xr

**Comment by BenWiederhake** [comment]
The crash doesn't seem to be directly related to the incoming image:

```
0   libsystem_kernel.dylib          0x00007fff8e843f06 __pthread_kill + 10
1   libsystem_pthread.dylib         0x00007fff8a9a44ec pthread_kill + 90
2   libsystem_c.dylib               0x00007fff978736e7 abort + 129
3   libsystem_malloc.dylib          0x00007fff8ef31041 free + 425
4   org.telegram-purple.telegram-adium  0x000000010b54ca59 tgl_free_release + 73
5   org.telegram-purple.telegram-adium  0x000000010b53ac02 tgls_free_message + 98
6   org.telegram-purple.telegram-adium  0x000000010b53d328 tgls_free_message_gw + 40
7   org.telegram-purple.telegram-adium  0x000000010b53bbfd 0x10b4f6000 + 285693
8   org.telegram-purple.telegram-adium  0x000000010b53d3e7 tgl_free_all + 183
```

This is likely to be the same issue as [this](https://github.com/majn/telegram-purple/issues/283#issuecomment-228131203).  Please try this patch out ([minimal version](https://github.com/majn/tgl/pull/7)) and *report back* whether this works or not.

**Comment by ddska** [comment]
I can't reproduce this, it happened just once.
Any idea how I can check it if it's fixed or not?

**Comment by BenWiederhake** [comment]
I already know how to check whether the "message double free" patch works, that's why I'm sure it fixes *that* issue.
However, I have no idea how to trigger any weird behavior with images.

So, I'll just this of this as "fixed", and please *do* complain/reopen if there's any further issue.
