### ISSUE TITLE
Adding group chats to the contact list

### ISSUE THREAD

**Issue by kaptoxic** [majn/telegram-purple#287]
I am not sure if I am missing something, but the issue is that I can only use group chats once there is a new message in the chat and the chat window automatically pops out for me. Thus, I did not find a way to send messages to a group chat from pidgin (except if the chat window is not already open).

**Comment by EionRobb** [comment]
Did you try the "Add all group chats to buddy list" option in the advanced account settings?

**Comment by kaptoxic** [comment]
This is indeed what I wanted (not sure how I missed it). Thanks!
