### ISSUE TITLE
no build 1.3.0

### ISSUE THREAD

**Issue by SergeyDjam** [majn/telegram-purple#290]
crahed on commit.h

i am fix this does commented all commit.h
in Makefile.in 
in telegram-purple.c
and remove commit.h.gen

**Comment by majn** [comment]
Needs git as new dependency for compiling.

**Comment by SergeyDjam** [comment]
i do repackage tar.gz v1.3.0 witch 
git clone --recursive --branch v1.3.0.

**Comment by SergeyDjam** [comment]
hm, pidgin d'nt viewing this library...

**Comment by SergeyDjam** [comment]
oh, reclone from git, and d'nt removed .git directory, and rebuild as is, and work plugin...

**Comment by majn** [comment]
So, you did a mistake while cloning am I understanding this correctly? Can I close this issue?
