### ISSUE TITLE
Keep renamed chats history in one place

### ISSUE THREAD

**Issue by vn971** [majn/telegram-purple#292]
Hi!
Is it possible to keep chat messages in one place even if a chat gets renamed?
As I understand it, telegram-purple currently keeps chats sorted by their visual name, not their IDs.

**Comment by majn** [comment]
Its not telegram-purple but Pidgin that does this. I don't know if there's a way to work around that, I fear that there isn't.

**Comment by vn971** [comment]
@majn AFAIunderstand, isn't it the plugin's role to supply an ID?

Currently I've tried to rename a channel (pigdin "Alias"), but the contents are still stored under its original name. Naively approaching this question I would assume pidgin handling both an ID supplied by a plugin and a visual name.

**Comment by EionRobb** [comment]
This could possibly be due to `tgprpl_get_chat_name()` returning the `subject` of the channel instead of the `id`

The telegram prpl does this with buddies too, where it should be using `id` as `name`, but that's a discussion for another issue ;)

**Comment by vn971** [comment]
Same issue here btw: https://github.com/majn/telegram-purple/issues/15

**Comment by BenWiederhake** [comment]
I'm confused.  Wasn't this already changed (and therefore fixed) in 1.3.0, so "a long time ago"?

**Comment by majn** [comment]
Its fixed, but there may be room for improvement (as Eion said), in still allowing the chat to change its name

**Comment by vn971** [comment]
Not sure it's really fixed, give me some more time plz.
You need to rename the chat on Telegram to see how it affects telegram-purple.

**Comment by lmfardin** [comment]
Just out of curiosity, has anyone renamed a contact and had a problem with the chat history in more than one place?Sorry, I don't even know if it's related to this issue. Just had a thought and decided to ask. 

    Em Quarta-feira, 12 de Abril de 2017 12:24, Vasya Novikov <notifications@github.com> escreveu:
 

 Not sure it's really fixed, give me some more time plz.
You need to rename the chat on Telegram to see how it affects telegram-purple.—

**Comment by vn971** [comment]
@lmfardin That is exactly my problem. When I rename a chat on Telegram, pidgin history gets messed up (there are 2 directories that contain history now).

**Comment by vn971** [comment]
BTW, this is no longer an issue for me personally.
So it can be closed if nobody else is expected to have this issue.

**Comment by lmfardin** [comment]
What bothers me is related to single contacts. If I have a friend called John, our chat history will be saved in a folder called John. If I rename him to John Black, then the chat history starts being stored in a new folder called John Black. It would be nice if there was a way to avoid it. 

    Em Domingo, 14 de Maio de 2017 7:44, Vasya Novikov <notifications@github.com> escreveu:
 

 BTW, this is no longer an issue for me personally.
So it can be closed if nobody else is expected to have this issue.—

**Comment by vn971** [comment]
I don't really use telegram-purple in the last years (as my work doesn't require Telegram at the moment). Since there are doubts that the issue might not even be relevant anymore, I'll close.
