### ISSUE TITLE
[solved] Arch Linux - 1.3.0 Turkish locale install problem Turkish Locale

### ISSUE THREAD

**Issue by fincan** [majn/telegram-purple#294]
While I try to install from AUR repo, there is a problem that compiling doesnt finish.

`In file included from mtproto-common.h:39:0,
from mtproto-common.c:45:
auto/constants.h:205:29: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_update_message_��_d 0x4e90bfd6

^
auto/constants.h:228:34: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_update_read_history_��nbox 0x9961fd5c

^
auto/constants.h:236:34: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_update_read_channel_��nbox 0x4214f37f

^
auto/constants.h:245:25: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_update_bot_��nline_query 0xc01eea08

^
auto/constants.h:326:33: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_document_attribute_��mage_size 0x6c37c15c

^
auto/constants.h:351:31: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_account_password_��nput_settings 0xbcfc532c

^
auto/constants.h:354:19: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_chat_��nvite_empty 0x69df3769

^
auto/constants.h:355:19: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_chat_��nvite_exported 0xfc2e05bc

^
auto/constants.h:355:0: hata: "CODE_chat_" yeniden tanımlanmış [-Werror]
# define CODE_chat_ınvite_exported 0xfc2e05bc

auto/constants.h:354:0: bilgi: burası evvelki tanımın yapıldığı yer
# define CODE_chat_ınvite_empty 0x69df3769

auto/constants.h:356:19: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_chat_��nvite_already 0x5a686d7c

^
auto/constants.h:356:0: hata: "CODE_chat_" yeniden tanımlanmış [-Werror]
# define CODE_chat_ınvite_already 0x5a686d7c

auto/constants.h:355:0: bilgi: burası evvelki tanımın yapıldığı yer
# define CODE_chat_ınvite_exported 0xfc2e05bc

auto/constants.h:357:19: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_chat_��nvite 0x93e99b60

^
auto/constants.h:357:0: hata: "CODE_chat_" yeniden tanımlanmış [-Werror]
# define CODE_chat_ınvite 0x93e99b60

auto/constants.h:356:0: bilgi: burası evvelki tanımın yapıldığı yer
# define CODE_chat_ınvite_already 0x5a686d7c

auto/constants.h:359:32: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_input_sticker_set_��_d 0x9de7a269

^
auto/constants.h:364:18: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_bot_��nfo_empty 0xbb2e37ce

^
auto/constants.h:365:18: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_bot_��nfo 0x09cf585d

^
auto/constants.h:365:0: hata: "CODE_bot_" yeniden tanımlanmış [-Werror]
# define CODE_bot_ınfo 0x09cf585d

auto/constants.h:364:0: bilgi: burası evvelki tanımın yapıldığı yer
# define CODE_bot_ınfo_empty 0xbb2e37ce

auto/constants.h:380:29: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_message_entity_��talic 0x826f8b60

^
auto/constants.h:416:24: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_input_bot_��nline_message_media_auto 0x2e43e587

^
auto/constants.h:417:24: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_input_bot_��nline_message_text 0xadf0df71

^
auto/constants.h:417:0: hata: "CODE_input_bot_" yeniden tanımlanmış [-Werror]
# define CODE_input_bot_ınline_message_text 0xadf0df71

auto/constants.h:416:0: bilgi: burası evvelki tanımın yapıldığı yer
# define CODE_input_bot_ınline_message_media_auto 0x2e43e587

auto/constants.h:418:24: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_input_bot_��nline_result 0x2cbbe15a

^
auto/constants.h:418:0: hata: "CODE_input_bot_" yeniden tanımlanmış [-Werror]
# define CODE_input_bot_ınline_result 0x2cbbe15a

auto/constants.h:417:0: bilgi: burası evvelki tanımın yapıldığı yer
# define CODE_input_bot_ınline_message_text 0xadf0df71

auto/constants.h:419:18: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_bot_��nline_message_media_auto 0xfc56e87d

^
auto/constants.h:419:0: hata: "CODE_bot_" yeniden tanımlanmış [-Werror]
# define CODE_bot_ınline_message_media_auto 0xfc56e87d

auto/constants.h:365:0: bilgi: burası evvelki tanımın yapıldığı yer
# define CODE_bot_ınfo 0x09cf585d

auto/constants.h:420:18: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_bot_��nline_message_text 0xa56197a9

^
auto/constants.h:420:0: hata: "CODE_bot_" yeniden tanımlanmış [-Werror]
# define CODE_bot_ınline_message_text 0xa56197a9

auto/constants.h:419:0: bilgi: burası evvelki tanımın yapıldığı yer
# define CODE_bot_ınline_message_media_auto 0xfc56e87d

auto/constants.h:421:18: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_bot_��nline_media_result_document 0xf897d33e

^
auto/constants.h:421:0: hata: "CODE_bot_" yeniden tanımlanmış [-Werror]
# define CODE_bot_ınline_media_result_document 0xf897d33e

auto/constants.h:420:0: bilgi: burası evvelki tanımın yapıldığı yer
# define CODE_bot_ınline_message_text 0xa56197a9

auto/constants.h:422:18: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_bot_��nline_media_result_photo 0xc5528587

^
auto/constants.h:422:0: hata: "CODE_bot_" yeniden tanımlanmış [-Werror]
# define CODE_bot_ınline_media_result_photo 0xc5528587

auto/constants.h:421:0: bilgi: burası evvelki tanımın yapıldığı yer
# define CODE_bot_ınline_media_result_document 0xf897d33e

auto/constants.h:423:18: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_bot_��nline_result 0x9bebaeb9

^
auto/constants.h:423:0: hata: "CODE_bot_" yeniden tanımlanmış [-Werror]
# define CODE_bot_ınline_result 0x9bebaeb9

auto/constants.h:422:0: bilgi: burası evvelki tanımın yapıldığı yer
# define CODE_bot_ınline_media_result_photo 0xc5528587

auto/constants.h:434:24: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_auth_sign_��n 0xbcd51581

^
auto/constants.h:437:24: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_auth_send_��nvites 0x771c1d97

^
auto/constants.h:521:35: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_messages_export_chat_��nvite 0x7d885289

^
auto/constants.h:522:34: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_messages_check_chat_��nvite 0x3eadb1bb

^
auto/constants.h:523:35: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_messages_import_chat_��nvite 0x6c50051c

^
auto/constants.h:538:27: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_messages_get_��nline_bot_results 0x9324600d

^
auto/constants.h:539:27: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_messages_set_��nline_bot_results 0x3f23ec12

^
auto/constants.h:540:28: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_messages_send_��nline_bot_result 0xb16e06fe

^
auto/constants.h:555:23: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_help_get_��nvite_text 0xa4a95186

^
auto/constants.h:560:27: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_channels_get_��mportant_history 0xddb929cb

^
auto/constants.h:582:30: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_channels_export_��nvite 0xc7560885

^
auto/constants.h:618:25: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_binlog_our_��d 0x68a870e8

^
auto/constants.h:632:29: hata: ISO C99 makro isminden sonra boşluk gerektirir [-Werror]
# define CODE_binlog_set_msg_��d 0x3c873416

^
cc1: all warnings being treated as errors
make[1]: **\* [Makefile:54: objs/mtproto-common.o] Error 1
make[1]: Leaving directory '/home/cihat/Aur/telegram-purple/src/telegram-purple/tgl'
make: **\* [Makefile:82: submade] Error 2
==> HATA: build() içinde bir hata oluştu.
Çıkılıyor...`

**Comment by majn** [comment]
I don't understand, doesn't the AUR contain the binaries? Why would you compile a package?

**Comment by fincan** [comment]
Aur doesnt contains binaries, this package is compiled from source. I ll try Aur's git version package.

**Comment by rodneyrod** [comment]
@fincan AFAIK the AUR packages haven't been updated for the latest 1.3.0 releases, and I think the maintainer isn't officially a part of this project.

Best bet would be to get in contact with them or to flag the package as out of date.

**Comment by fincan** [comment]
Well finally I ve just found the problem; my setup uses LANG=tr_TR.UTF-8 and I have to compile with "LC_ALL=en_US" entry from Aur repo.

LC_ALL=en_US makepkg -si 

and now it is ok!
