### ISSUE TITLE
Add an option to set self-destruct timer in private chats

### ISSUE THREAD

**Issue by jsalatiel** [majn/telegram-purple#300]
Would it be possible add an option to set self destruct time in private chats ?

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
