### ISSUE TITLE
pidgin: structures.c:1205: tglf_fetch_message_media: Assertion `0' failed.

### ISSUE THREAD

**Issue by Volodya** [majn/telegram-purple#311]
I have confirmed that the following pidgin bug only occurs when i turn on telegram-purple:
https://bugs.launchpad.net/ubuntu/+source/pidgin/+bug/1626882

**Comment by majn** [comment]
What version do you use?

**Comment by Volodya** [comment]
Apparently i just needed to update to the latest git version. It all works now. Sorry for the trouble.
