### ISSUE TITLE
/OPER , password

### ISSUE THREAD

**Issue by ralpheeee88** [majn/telegram-purple#313]
(Arch / weechat)

i keep getting :

 "Enter password for account telegram first (use /OPER)"

every time i Log in

**Comment by rodneyrod** [comment]
You need to delete your account and add it again using the following parameters without the <>:

account add telegram <phone number> <anything, literally anything>

If you don't add the last field then bitlbee will think you'll be adding a password later, which you can do but it's more arduous.

**Comment by dequis** [comment]
Or just do what it says and write anything as password.

Also, not a telegram-purple bug.

**Comment by dequis** [comment]
This will be less confusing with this commit https://github.com/bitlbee/bitlbee/commit/9f03c472fef309878ff2f3bc720d51e6d03077f1

This ticket can be closed.
