### ISSUE TITLE
[Feature Request] Add option to automatically and silently reject 'file transfers' in Adium

### ISSUE THREAD

**Issue by rodneyrod** [majn/telegram-purple#319]
Every time a user posts an audio file, gif or other small general file, Adium will automatically open a tab with their name asking to accept or reject.

If one has joined a large number of groups though, this can become overwhelming and flood the chat list, which more often than not results in Adium crashing.

Adding an option to silently and automatically reject these requests would hopefully prevent this issue.

**Comment by majn** [comment]
I've been thinking about an option to automatically load all (non-executable) transfers up to a certain size and provide a link.

**Comment by rodneyrod** [comment]
That's not the behaviour in my client, it opens up a new tab for every user when they send a file.

**Comment by RobFog** [comment]
@majn @rodneyrod I think that might actually depend on the message style you are using. I believe some show file transfers inline.

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
Of course, Pull Requests are still very much welcome!
