### ISSUE TITLE
Update text from phone

### ISSUE THREAD

**Issue by maxdeb** [majn/telegram-purple#32]
When I type something to a contact with my phone, this is not shown in Pidgin.
But when i send a picture from my phone, it is shown in Pidgin.

Is it possible to see the text, sent from my phone, in Pidgin too? That way I can really have a mixed conversation.
Also, it would be interesting to see the last 10 messages or when a new conversation has started.

Very good plugin btw, thanks for all your effort!

**Comment by majn** [comment]
Hi,

I know about this problem, but I've only encountered it in Adium so far. If I run Pidgin on Fedora20 I always receive all of my own messages that I send on my phone. What version of libpurple / pidgin do you use?

How incoming messages from myself are handled (that are not being sent by pidgin), appears to be implementation specific behavior that changes for each version of Pidgin / Adium. Maybe I will need to bypass the regular serv_got_im(who, message, flags) function and handle the conversations directly. 

I definitely want this to work properly, but I'm still not sure how to do it.

>Also, it would be interesting to see the last 10 messages or when a new conversation has started.
I don't know if it that should be changed from within a libpurple-protocol plugin, it is client-specific behavior.

**Comment by maxdeb** [comment]
I am using Pidgin 2.10.9 and libpurple 2.10.9.

**Comment by EionRobb** [comment]
@majn After trying a few different ways to do this in a few different plugins, I've settled on using serv_got_im() for the received messages and purple_conversation_write() for the sent messages, using a GHashTable to keep track of the message id's I've sent to make sure there's no double-ups in the display of sent messages.  This seems to have the widest cross-UI support.

**Comment by pfannie** [comment]
I have the same issue on Mac OS X 10.11.2 using Adium 1.5.10 and I don't know which version of libpurple. I downloaded the Adium Bundle v1.2.1 (Beta 3) from [here](https://github.com/majn/telegram-purple/releases).

When I open a chat in Adium that I was using from my phone or the web version of Telegram it only downloads the other person's messages but not my own.

**Comment by majn** [comment]
@pfannie Unfortunately not, Adium will simply not display those messages for whatever reason. I once tested it in Adium 1.6.0 and it seems to work in that one.

**Comment by pfannie** [comment]
Ok, so I got Adium 1.6.0, and the plugin is loaded (I can see it under Preferences -> Xtras -> Plugins), but the telegram account isn't there and I don't get the option when trying to add one. Is there anything one has to do before one can use the beta version (next to the stable one) with plugins?

**Comment by BenWiederhake** [comment]
That sounds a lot like something went wrong when loading the plugin. Can you start Adium in debug mode? With Pidgin it's `pidgin -d`, it should be similar for Adium.

**Comment by majn** [comment]
@BenWiederhake it doesn't really work like that in OSX, to run it from terminal you need to execute the binary in the .app file:

     /Applications/Adium.app/Contents/MacOS/Adium

**Comment by pfannie** [comment]
I run it from a shell and got the following output:
```
➜  MacOS  ./Adium
2016-01-01 17:26:21.288 Adium[2075:378896] Error loading /Users/justus/Library/Application Support/Adium 2.0/PlugIns/telegram-adium.AdiumLibpurplePlugin/Contents/MacOS/telegram-adium:  dlopen(/Users/justus/Library/Application Support/Adium 2.0/PlugIns/telegram-adium.AdiumLibpurplePlugin/Contents/MacOS/telegram-adium, 265): Library not loaded: @executable_path/../Frameworks/libglib.framework/Versions/2.38.1/libglib
  Referenced from: /Users/justus/Library/Application Support/Adium 2.0/PlugIns/telegram-adium.AdiumLibpurplePlugin/Contents/MacOS/telegram-adium
  Reason: image not found
2016-01-01 17:26:21.289 Adium[2075:378896] Failed to obtain principal class from plugin "telegram-adium.AdiumLibpurplePlugin" ("/Users/justus/Library/Application Support/Adium 2.0/PlugIns/telegram-adium.AdiumLibpurplePlugin")! infoDictionary: {
    AIMinimumAdiumVersionRequirement = "1.5.10";
    BuildMachineOSBuild = 14F27;
    CFBundleDevelopmentRegion = English;
    CFBundleExecutable = "telegram-adium";
    CFBundleIdentifier = "org.telegram-purple.telegram-adium";
    CFBundleInfoDictionaryVersion = "6.0";
    CFBundleInfoPlistURL = "Contents/Info.plist -- file:///Users/justus/Library/Application%20Support/Adium%202.0/PlugIns/telegram-adium.AdiumLibpurplePlugin/";
    CFBundleName = "telegram-adium";
    CFBundleNumericVersion = 16809984;
    CFBundlePackageType = BNDL;
    CFBundleShortVersionString = "1.2.1";
    CFBundleSignature = AdIM;
    CFBundleSupportedPlatforms =     (
        MacOSX
    );
    CFBundleVersion = 1;
    CFPlugInDynamicRegisterFunction = "";
    CFPlugInDynamicRegistration = NO;
    CFPlugInFactories =     {
        "00000000-0000-0000-0000-000000000000" = MyFactoryFunction;
    };
    CFPlugInTypes =     {
        "00000000-0000-0000-0000-000000000000" =         (
            "00000000-0000-0000-0000-000000000000"
        );
    };
    CFPlugInUnloadFunction = "";
    DTCompiler = "com.apple.compilers.llvm.clang.1_0";
    DTPlatformBuild = 7A220;
    DTPlatformVersion = GM;
    DTSDKBuild = 15A278;
    DTSDKName = "macosx10.11";
    DTXcode = 0700;
    DTXcodeBuild = 7A220;
    NSHumanReadableCopyright = "Copyright \U00a9 2014 Matthias Jentsch.";
    NSPrincipalClass = TelegramPlugin;
}
2016-01-01 17:26:21.289 Adium[2075:378896] Failed to initialize Plugin "telegram-adium.AdiumLibpurplePlugin" ("/Users/justus/Library/Application Support/Adium 2.0/PlugIns/telegram-adium.AdiumLibpurplePlugin")!
```

Adium is still running, but obviously the plugin isn't working.

**Comment by EionRobb** [comment]
Looks like the plugin is referencing a specific version of glib rather than using the generic version. There's a command you can add to the xcode build script that can retarget which version of glib you're looking for to be more generic

**Comment by BenWiederhake** [comment]
Both problems seem to be resolved (the first is "can't reproduce" and the second is "I think it was fixed").
Feel free to reopen this issue if you think otherwise.
