### ISSUE TITLE
Bitlbee is crashing at launch when attempting to fetch history

### ISSUE THREAD

**Issue by rodneyrod** [majn/telegram-purple#320]
Machine: OpenVZ Ubuntu 14.04, 512MB of RAM
Member of a lot of large groups with many messages
Set to retrieve only 1 day of history, however Bitlbee with either segfault retrieving history, retrieve history but not update the chats, or partially update the chats with new messages and stop

The &bitlbee room still shows users going on and offline (+v or -v) but chats will not update.

Will try and provide more info when available.

**Comment by EionRobb** [comment]
https://wiki.bitlbee.org/DebuggingCrashes

**Comment by rodneyrod** [comment]
I have the gdb dump, what's the best way to send you a copy?

**Comment by rodneyrod** [comment]
I have the gdb dump, I've posted a link to it below with the identifying information removed [hopefully].

https://gist.github.com/rodneyrod/5fba4c7fb0bfe4058e046e3a991e5faa

**Comment by EionRobb** [comment]
Doesn't look like a very helpful backtrace, without debug symbols :(

To get a better backtrace, we'll need debug symbols for glib, libpurple and bitlbee

**Comment by rodneyrod** [comment]
I was using the binaries supplied by the bitlbee nightly team, they're supposed to be using the debug symbols, not for glib but I'll try and get on that.

**Comment by rodneyrod** [comment]
Got new logs, hopefully this will help get to the bottom of the problem.

https://gist.github.com/rodneyrod/27ad310797b60671c1da681bad0c4895

**Comment by EionRobb** [comment]
Whoops, there's no bactrace in there

**Comment by rodneyrod** [comment]
https://gist.github.com/rodneyrod/a1c27847549fa3913c7cbca1cb3514f2

Should have been included, that's the output that bt produces in gdb

**Comment by dequis** [comment]
This is now fixed in bitlbee git, with either [this commit][1], or [this other commit][2], or, most likely, both.

[1]: https://github.com/bitlbee/bitlbee/commit/701ab8129ba9ea64f569daedca9a8603abad740f
[2]: https://github.com/bitlbee/bitlbee/commit/ea902752503fc5b356d6513911081ec932d804f2

It's not telegram specific, but the way telegram spams with file transfers while fetching message history makes it much more likely than anything else to trigger this. Also the fact that file transfers are rarely ever used in other protocols.

You can close this.

**Comment by rodneyrod** [comment]
The crashing issue seems to be resolved now, but it still will only get a backlog and then fall out of sync with Telegram.
All it does is +v or -v users in the &bitlbee channel

**Comment by rodneyrod** [comment]
Well, since I've been having issues compiling and getting debugging working with bitlbee myself, I tested it out with Pidgin on another similarly spec'd machine I have around

https://gist.github.com/rodneyrod/a7d7fdb91e8dcb0e1404bc47ea9a11c9

**Comment by dequis** [comment]
@rodneyrod open a new ticket
