### ISSUE TITLE
Session management

### ISSUE THREAD

**Issue by majn** [majn/telegram-purple#321]
Allow termination of tgp sessions (comparable to the phone app)

**Comment by mrkiko** [comment]
Thank you for opening this issue. Sorry if I didn't answer to your messages if you wrote something to me; I may have lost them.
Feel free to contact me in PM or here.

**Comment by BenWiederhake** [comment]
Do we get a call from the frontend when an account is being deleted?  That's probably the bext place to do it.

**Comment by BenWiederhake** [comment]
There are two enhancements with similar description:
- telegram-purple terminating its own session as soon as the libpurple-account gets removed
- telegram-purple being able to terminate sessions of other clients (i.e., an entirely new interface)

Anyway.

If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
