### ISSUE TITLE
Internal Server Error, please reconnect.

### ISSUE THREAD

**Issue by rizaksp** [majn/telegram-purple#322]
I have fail to login with respone : Internal Server Error, please reconnect.

my setting and log is here : https://gist.github.com/rizaksp/d0a6a3ae182e4f9d1c8cd00665da875e

thank's for respone

**Comment by criztovyl** [comment]
Most likely related to Spectrum2, not telegram-purple.
This repo is for telegram-purple only, sry.

**Comment by BenWiederhake** [comment]
I recently (a few days) saw the same issue with both the web client and telegram-purple, so I guess that "500 internal server error" stems from Telegram's servers.  Let's hope the Telegram people do their job, but either way: there's nothing we can do if this happens intermittently.

Feel free to reopen if this *permanently* prevents you from logging in.
