### ISSUE TITLE
Ignored order/priority of buddy contacts in a group

### ISSUE THREAD

**Issue by powerman** [majn/telegram-purple#323]
When I've both Skype ([skypeweb](https://github.com/EionRobb/skype4pidgin)) and Telegram contact of same buddy combined in a group, and I re-order contacts in that group to have telegram contact first and skype second - it doesn't work: when I open conversation at that group skype opens instead of telegram.

https://developer.pidgin.im/wiki/Using%20Pidgin#IgroupedmybuddiesintocontactscanIcontrolwhichoneisselected

Another strange thing with same contact - if I use "Send To" menu to switch from skype to telegram (after I've opened conversation on that group and by default skype opens) then telegram conversation opens in next tab instead of same tab. This happens only with that contact - another one buddy also with skype and telegram have same "default skype" priority issue but "Send To" for that buddy works as expected (telegram replace skype in same tab).

I'm using telegram-purple from master (compiled 24 hours ago) with pidgin-2.11.0, Gentoo.

**Comment by powerman** [comment]
Still actual for current master.

**Comment by BenWiederhake** [comment]
That sounds a lot like it's ["mobile online" versus "offline"](https://github.com/majn/telegram-purple/issues/234) again.  Feel free to continue over there.
