### ISSUE TITLE
Incoming audio file link opens explorer

### ISSUE THREAD

**Issue by m-alice** [majn/telegram-purple#326]
When you received audio file and try to click link, opens explorer.exe (but you see file path in popup comment).
Does not matter, you clicked "open file" or "open a path"
Windows 10 10586
Pidgin 2.11.0
Plugin Version: 1.3.0			commit: 0340e4f14b			libtgl: 2.1.0
autoreceive turn ON

**Comment by criztovyl** [comment]
Maybe related to #317?

**Comment by majn** [comment]
What exactly is the issue? Does it only open the explorer and not play the file?

**Comment by BenWiederhake** [comment]
@m-alice: Any news on this?

Can any Windows user reproduce this?  @EionRobb?

**Comment by EionRobb** [comment]
This is normal Pidgin behaviour on Windows for file:/// uri's

**Comment by BenWiederhake** [comment]
Hmm, is there a way to (ab)use MIME types in order to tell pidgin what program to call?  Anyway, duplicate of #317 like @criztovyl already noted.
