### ISSUE TITLE
tgl_init fails with OpenSSL variant of tgl

### ISSUE THREAD

**Issue by arkenoi** [majn/telegram-purple#327]
I used an older version of telegram-purple and it worked, now I tried to checkout new one from github and it doesn't.

(20:03:53) prpl-telegram: tgprpl_login(): Purple is telling the prpl to connect the account 
(20:03:53) prpl-telegram: base configuration path: '/home/ark/.purple/telegram-purple/+359878830030'                        
(20:03:53) prpl-telegram: trying global pubkey at /etc/telegram-purple/server.tglpub 
(20:03:53) prpl-telegram: read pubkey file: n_len=256 e=65537 
(20:03:53) prpl-telegram: using global pubkey  
(20:03:53) prpl-telegram: Call to tgl_init failed. 
(20:03:53) connection: Connection error on 0x16a7740 (reason: 7 description:
Unable to sign on as +359878830030: problem in the underlying library 'tgl'.
Please submit a bug report with the debug log.)

**Comment by BenWiederhake** [comment]
Whoops, somehow I didn't see this issue.  It should be fixed on the dev branch.  Try `git checkout dev-1.4.0` after pulling the lastest changes.  Don't forget to `git submodule update --recursive` before building!

**Comment by robert-scheck** [comment]
Applying https://github.com/majn/tgl/commit/ac2cdc9d93408ec612161dbc81d27d7319a0cab2.patch to 1.3.0 solves the issue, could you please backport it for something like 1.3.1?

**Comment by BenWiederhake** [comment]
Since it's in a different repository, I don't quite see the point in it.  Just do a `git checkout dev-1.4.0` or similar, and don't forget to `git submodule update --recursive`.  Or did you encounter any troubles I didn't see?

**Comment by BenWiederhake** [comment]
Should be fixed in 1.3.1.  Feel free to reopen if there's any issue.
