### ISSUE TITLE
Pidgin crash on startup

### ISSUE THREAD

**Issue by Despin** [majn/telegram-purple#332]
If I start Pidgin from a terminal it comes out when crashes
`
Pidgin 2.11.0 ha tenido un fallo y ha intentado generar un archivo «core».
Esto es una errata en el programa y no se ha producido por
algo que haya hecho.

Si puede reproducir este fallo, por favor, notifíquelo a los 
desarrolladores de Pidgin enviando un informe de errata a
http://developer.pidgin.im/simpleticket/

Asegúrese de especificar lo que estaba haciendo en el momento de
suceder esto y envíenos su traza del archivo «core». Si no sabe como
obtener una traza consulte las instrucciones disponibles en
http://developer.pidgin.im/wiki/GetABacktrace
fish: 'pidgin' terminated by signal SIGABRT (Abort)

`
The version of Pidgin is 2.11.0 and the one of telegram-purple is the day 29/10, at least that commit.

System:
Debian Jessie 8.1 x86-64

**Comment by majn** [comment]
Do you have a backtrace or a debug log? I will close it until then and assume its one of the other crashes.
