### ISSUE TITLE
Option to just get URLs for viewing stickers, pictures or GIFs on non gui clients (Spectrum, Finch, Bitlbee,.. )

### ISSUE THREAD

**Issue by TomTheDragon** [majn/telegram-purple#333]
I am bridging a Telegram, a Skype and a XMPP chat together with https://github.com/boamaod/rainbow-bridge
But gui-only features like stickers and pictures can not be send, since Finch cant receive them.
Would it be possible to maybe add an option to just receive links to everything instead?

**Comment by criztovyl** [comment]
I think Telegram transfers images in no such way you could get a clickable link, they're sending the data not a reference. (afaik)

**Comment by Orhideous** [comment]
How about the option of saving pics/stickers and their further distribution from private server?

**Comment by BenWiederhake** [comment]
"private server" is a horrible idea.  Why not just use the local path as a `file://` url, if you really really need one?

**Comment by Orhideous** [comment]
@BenWiederhake It is not as terrible as it may seem at first glance.
Obviously, in the case of plugin for desktop messenger access `file:///<local folder>/<hashed pic>.<ext>` scheme (local folder) will be preferred.
But suppose that I run `telegram-purple` as a service for the `Spectrum`, and, in this case, the server is *already there*. Therefore, if the `telegram-purple` will store files locally on the server (as in the case of plug-in), but will be *able to set the path prefix* to it, then any web server (nginx, for example) in the same way will serve pictures over the network, with `http(s)://<server>/<prefix>/<local folder>/<hashed pic>.<ext>` scheme.

**Comment by BenWiederhake** [comment]
That is far, far outside of the scope for telegram-purple.  If serves the images including paths to libpurple.  If you want your libpurple frontend to open up ports and serve arbitrary, large files to unauthorized users over an http(s) connection, then you can do that -- but that would be your frontend's job. ("frontend" as seen by libpurple.)

**Comment by BenWiederhake** [comment]
I don't recall why this issue is open.  telegram-purple puts the images into the libpurple imgstore, and it's the frontend's job to provide it from there to the user, e.g. by providing a `file://` link.  So this doesn't apply to telegram-purple.

Feel free to reopen if you have any suggestion how telegram-purple can help any further.

**Comment by TomTheDragon** [comment]
It shows the link this if i hover my mouse over it
file:///D:\Pidgin\data\.purple\telegram-purple\[my_phone_number]\downloads/download_532582752227165889.mp4
But like i said, it dont works if i click on it.

I does however work if i manually type in this address into firefox, which corrects it to this
file:///D:/Pidgin/data/.purple/telegram-purple/[my_phone_number]/downloads/download_532582752227165889.mp4

**Comment by BenWiederhake** [comment]
… which goes to #317, not here.
