### ISSUE TITLE
Support group doesn't seem to exist

### ISSUE THREAD

**Issue by languitar** [majn/telegram-purple#337]
I tried to join the telegram support group mentioned in the readme file. However, the official Telegram client indicates that this group doesn't exist.

**Comment by criztovyl** [comment]
The group itself exits, so only the link seems to be broken. Unfortunately I currently cannot find the correct link anywhere, but I think help it's on its way.

**Comment by criztovyl** [comment]
Some technical details b/c fun, from web.telegram.org.

```
Method: messages.checkChatInvite
Url: N/A
Result: {"_":"rpc_error","error_code":400,"error_message":"INVITE_HASH_EXPIRED"}
```

**Comment by majn** [comment]
Group chat link is refreshed now
