### ISSUE TITLE
hebrew characters messages are not sent

### ISSUE THREAD

**Issue by addadi** [majn/telegram-purple#339]
Hi,
whenever I try to send messages in Hebrew, the message is failing:
```

(10:45:43) prpl-telegram: tgprpl_send_typing()
(10:45:43) prpl-telegram: Sent query #### of size 24 to DC 4
(10:45:44) prpl-telegram: tgprpl_send_typing()
(10:45:44) prpl-telegram: Sent query #### of size 24 to DC 4
(10:45:45) prpl-telegram: tgprpl_send_im()
(10:45:45) prpl-telegram: parsed 0 images in messages
(10:45:45) prpl-telegram: tgprpl_send_typing()
(10:45:45) prpl-telegram: Sent query #### of size 24 to DC 4
(10:45:45) prpl-telegram: Sending message failed.
(10:45:45) prpl-telegram: Sending message failed.
```
English is working fine

Thanks

**Comment by majn** [comment]
Interesting, can you give me an example message that would cause this?

**Comment by BenWiederhake** [comment]
Probably related to #305, which wasn't reproducible but "clustered" in time.

**Comment by addadi** [comment]
An example would be any character combination in Hebrew, Such as:
ניסיון

**Comment by BenWiederhake** [comment]
Interesting.  I can reproduce this *all* the time, in contrast to the intermittent failures I usually see.

It seems this line gets executed (proof: change the string slightly, recompile, see the different error message handed down)

```
tgl_set_query_error (TLS, EINVAL, "Unknown tag"); // tgl/queries.c:755
```

There's something seriously wrong with HTML handling.  Thanks for the report, and thanks for giving me something I can finally reliably reproduce!

**Comment by addadi** [comment]
the temp workaround indeed works. I need to stress that this doesn't happen with other libraries interactive with libpurple. so for example in pidgin, there are no problems to send send Hebrew characters (only) when connected to google talk

**Comment by EionRobb** [comment]
@BenWiederhake you can use `purple_markup_is_rtl()` to see if the HTML is RTL or not, if that helps

**Comment by BenWiederhake** [comment]
> doesn't happen with other libraries interact with libpurple

That's because there's a bug in libtgl, which attempts to parse the HTML generated by purple.  And libtgl does not recognize `<span>`.

> the "<" is missing from the closing SPAN

Typo when copying.  I don't know how that happened, but when I reproduce this now, I see:

```
Message was: <SPAN style="direction:rtl;text-align:right;">נ</SPAN>
```

@EionRobb:

> to see if the HTML is RTL or not

Interesting idea, but I don't see yet how that helps.  Knowing that it's there doesn't really help with stripping it away, since I don't know whether it might appear with different attributes or in the middle of the text.

**Comment by majn** [comment]
Doh, so its the shitty HTML parsing again.

The libtgl HTML parser either needs a rework to recognize all the possible HTML markup or be stripped completely. I believe that right now that parser is only used for sending the <code>-Tag, to generate monospaced fonts on the other endpoint.

**Comment by BenWiederhake** [comment]
The workaround of #305 should fix this, if I remember correctly.  Feel free to reopen if you have any issue.

**Comment by addadi** [comment]
just installed telegram-purple from aur (https://aur.archlinux.org/packages/telegram-purple/) which is at version 1.3.1-1 Unfortunately, the problem is still there, the message is still not send but the debug log now show something different:
(10:25:29) prpl-telegram: ping alarm
(10:25:42) prpl-telegram: tgprpl_send_typing()
(10:25:42) prpl-telegram: Sent query #6408013646636057600 of size 24 to DC 4
(10:25:42) prpl-telegram: update 0x5c486927 (check=0)
(10:25:43) prpl-telegram: tgprpl_send_im()
(10:25:43) prpl-telegram: parsed 0 images in messages
(10:25:43) prpl-telegram: tgprpl_send_typing()
(10:25:43) prpl-telegram: Sent query #6408013653583882240 of size 24 to DC 4
(10:25:43) prpl-telegram: Sending message failed.
(10:25:43) prpl-telegram: Code 22: Unknown tag
(10:25:43) prpl-telegram: Message was: <SPAN style="direction:rtl;text-align:right;">ניסיון</SPAN>
(10:25:43) prpl-telegram: update 0x5c486927 (check=0)

**Comment by BenWiederhake** [comment]
I can reproduce this.  Exact same error again.  Huh.

**Comment by BenWiederhake** [comment]
Could you try it again with the latest commit on `dev-1.4.0`?  I can now send messages in a RTL-language.

**Comment by addadi** [comment]
Tested. Confirmed to work fine with branch dev-1.4.0. This is great! thank you very much!
