### ISSUE TITLE
Plugin won't load on CentOS 6.6 (64bit)

### ISSUE THREAD

**Issue by ronilaukkarinen** [majn/telegram-purple#34]
Installed everything as instructed, without errors. With `pidgin -d` getting:

	(22:12:27) plugins: /usr/lib64/purple-2/telegram-purple.so is not loadable: undefined symbol: g_format_size

What gives?

**Comment by majn** [comment]
It seems that the function g_format_size is missing in your version of GLib, it was added in version 2.29.12, I guess CentOS 6 still uses an older one?

I'll add the GLib version to the requirements in the README ...

**Comment by ronilaukkarinen** [comment]
22:22:42] [38.0°C] rolle telegram-purple $ rpm -q glib2-devel
	glib2-devel-2.28.8-4.el6.x86_64
	glib2-devel-2.28.8-4.el6.i686

Oh yeah, so it seems.

I guess the entire system of CentOS 6.6 is build around an older, but stable version of glib, so by updating it I could break everything. Any workarounds?

**Comment by majn** [comment]
I think I will implement g_format_size myself, its just a function that returns a human-readable string for a byte size, like "2 GB" or something like that, shouldn't be too much effort. 

I hope its the only function that is not available at that version ;)

**Comment by majn** [comment]
If you want to help, you can replace format_document_desc in line 219 of telegram-purple.c with this function and tell me if it works.

    static char *format_document_desc (char *type, char *caption, gint64 size) {
      char *msg = g_strdup_printf ("[%s] %s %ld bytes", type, caption, size);
      return msg;
    }

**Comment by ronilaukkarinen** [comment]
Nice! Sure, I'll test it right away.

**Comment by ronilaukkarinen** [comment]
Another one, hah:

	(22:48:30) plugins: /usr/lib64/purple-2/telegram-purple.so is not loadable: undefined symbol: purple_notify_user_info_add_pair_plaintext

**Comment by majn** [comment]
Damn, this time its Libpurple, that one might be harder.

**Comment by ronilaukkarinen** [comment]
If it helps:
	[22:53:59] [38.0°C] rolle telegram-purple $ rpm -q libpurple-devel
	libpurple-devel-2.7.9-27.el6.x86_64

**Comment by majn** [comment]
Removing both functions was possible, and I've put it into a branch for testing. You can try to compile it  https://github.com/majn/telegram-purple/commit/a08a267e22fa45cda15cc46c34ff34f5b8ce67f3 . If it works, nice I'll merge it. If it doesn't I'll, have to test it myself in a VM and see what I can do / if its possible at all.

**Comment by ronilaukkarinen** [comment]
Thank you for your effort. Removed the folder and cloned with

	git clone --recursive -b fix-centos git@github.com:majn/telegram-purple.git

Still says:

	(23:38:57) plugins: /usr/lib64/purple-2/telegram-purple.so is not loadable: undefined symbol: purple_notify_user_info_add_pair_plaintext

I have double checked the right branch is checked out and up-to-date.

**Comment by majn** [comment]
Are you sure that you have actually installed the new binary? 

    grep -R 'purple_notify_user_info_add_pair_plaintext' .

Tells me that the symbol isn't present anymore on the current branch. You could sudo make uninstall and sudo make clean and try it again then.

**Comment by ronilaukkarinen** [comment]
@majn Yeah, that grep returned empty results. I don't know why `sudo make install` didn't help, but I copied the file manually just now `sudo cp bin/telegram-purple.so /usr/lib64/purple-2/telegram-purple.so`

Now getting:

	(09:24:20) plugins: /usr/lib64/purple-2/telegram-purple.so is not loadable: undefined symbol: g_hash_table_contains

**Comment by majn** [comment]
In that case it won't work on Centos, since I can't remove that hash table without big effort.

**Comment by EionRobb** [comment]
You can replace that relatively new hash table function with g_hash_table_lookup() instead

**Comment by ronilaukkarinen** [comment]
Too bad, I was really looking forward to this. Either way, if desperate and no alternative solution available, I think I may try installing a second glib even if it may be too overkill just for one application.

**Comment by majn** [comment]
You are right, its only those functions that have a dependency of v 2.32, seems like I was a little to fast then.

**Comment by majn** [comment]
I think I'll have to set up up a test VM for Centos myself and remove all troublesome functions, since it will remove problems on other old systems too.

**Comment by majn** [comment]
fixed https://github.com/majn/telegram-purple/commit/58f34cbe8ab3306c2ca460f95cd22e3a32d31b90
