### ISSUE TITLE
wrong nick on secret chats

### ISSUE THREAD

**Issue by fauno** [majn/telegram-purple#340]
when i write on a secret chat, my messages appear printed as they were sent by the other person, like this:

```
! Other person: hello
! Other person: hi
```

instead of:

```
! Other person: hello
me: hi
```

using pidgin 2.11.0

**Comment by fauno** [comment]
it doesn't happen for regular chats

**Comment by BenWiederhake** [comment]
Indeed, I can reproduce that.

Weird, I don't know what introduced that, or why nobody noticed so far.

**Comment by hauau** [comment]
https://github.com/majn/telegram-purple/issues/310

**Comment by ghsrcgh** [comment]
Found the same issues #310, #363, #398 (mine) - they must be linked. Many users have the same issues.
