### ISSUE TITLE
Pidgin crashes on attempting to add user

### ISSUE THREAD

**Issue by Waterkonijn** [majn/telegram-purple#341]
Pidgin 2.11.0
Raspbian GNU/Linux 8 (jessie)
telegram-purple 1.3.0

As soon as I click the 'add' button, pidgin closes with the message

>pidgin:
>mtproto-utils.c:101: BN2ull: Assertion `0' failed.
>Aborted

I am unsure where this issue lies, perhaps it's the raspberry pi. I'm fairly certain that I followed the installation procedure exactly as described.

Full log below

[telegram-purple-log.txt](https://github.com/majn/telegram-purple/files/702901/telegram-purple-log.txt)

**Comment by BenWiederhake** [comment]
Yup, I guess that your Rasperry Pi has a 32-bit processor. Sorry, the fix for that isn't in `master` yet, but it's there, in the `dev-1.3.0` branch in the tgl submodule.  (The name is misleading, we should probably fix that.)  In practice, this means:

```
telegram-purple/$ cd tgl
telegram-purple/tgl/$ git checkout dev-1.3.0  # Is actually dev-1.4.0 now
telegram-purple/tgl/$ rm Makefile
telegram-purple/tgl/$ cd ..
telegram-purple/$ make # Or whatever you were using
```

Feel free to re-open if this issue persists.
