### ISSUE TITLE
Secret chat timer

### ISSUE THREAD

**Issue by TheNocturnalEvil** [majn/telegram-purple#343]
There's no option to set the timer for secret chats. Is the feature not implemented yet, because the official Telegram for MacOS has it.

**Comment by majn** [comment]
The official OSX client supports secret chats?

**Comment by TheNocturnalEvil** [comment]
Yes the official Telegram for MacOS app available in Appstore does support secret chat and has the secret chat timer too for sending self-destructing messages.
https://itunes.apple.com/us/app/telegram/id747648890

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.

(Note that tdlib-purple doesn't implement secret chats yet.)
