### ISSUE TITLE
hide chat window not working

### ISSUE THREAD

**Issue by ssibb** [majn/telegram-purple#345]
Hi everybody. I'm not sure this is a plugin problem, however i don't have this problem with other plugins so maybe the issue is on telegram-purple.
When i receive a telegram message (in particular group chats) the window opens even if I set pidgin not to open the conversation windows. It's very annoying even if the option to minimize the new chat windows works.

**Comment by majn** [comment]
Its how Telegram behaves therefore the plugin behaves similarly.

I currently don't have a plan changing it.
