### ISSUE TITLE
Empathy (telepathy-haze) doesn't popup anything for authentication (Ubuntu/Ubuntu-Gnome >16.04)

### ISSUE THREAD

**Issue by khurshid-alam** [majn/telegram-purple#346]
This is regarding issue #8 where many claimed that telegram-purple is working with telepathy-haze. However I couldn't make it work with following

| Ubuntu/ Ubuntu-Gnome | Empathy | Gnome-Control-Center | Telepathy-Haze | Telegram-Purple (webupd-ppa) |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| 16.04  | 3.12.11  | 3.18.2  | 0.8  | 1.3.0-1 |
| 16.10  | 3.12.11  | 3.20  | 0.8  | 1.3.0-1 |

I tried adding by running `empathy-accounts` and from **gnome-online-accounts** (Ubuntu-Gnome)....but it always gives me authentication error and nothing popup asking the OTP. 

I also noticed "fallback authentication" option missing from online-settings. With pidgin I had to enable it to make it work but couldn't do it online-accounts.

**Pidgin-Account-Settings:**
![telegram-pidgin](http://i.imgur.com/IdG8Jbc.png)

**Empathy-accounts:**
![telegram-empathy](http://i.imgur.com/WAjdnT7.png)

As you can see there is no way to force fallback when accessing through online-accounts.

I remembered older-version (<1.2) used to work with Ubuntu 14.04. Is there any way I can make it work current version?

**Comment by khurshid-alam** [comment]
@majin Any news on this? 

>Account creation does work, but not in the initial welcome wizard that routes you through the first start.
The popup that queries for the SMS code is not displayed on startup, so account creation in empathy will only work if you have previously entered the code in pidgin

**I did setup pidgin first, then tried to add account in empathy. But it still doesn't work.** If it doesn't work through initial welcome wizard, then how does it is supposed to work?

**Comment by majn** [comment]
The option is called "compat verification". For some reason telepathy-haze uses the internal keys not the description provided.

NOTE: You shouldn't need to use "fallback verification" in Pidgin, why do you need that?

**Comment by khurshid-alam** [comment]
>NOTE: You shouldn't need to use "fallback verification" in Pidgin, why do you need that?

Yes. You are right. I don't really need that.

>The option is called "compat verification". For some reason telepathy-haze uses the internal keys not the description provided.

So it should be enabled? I tried enabling compact verification before, but it didn't bring any popup either. If I use online-accounts from gnome-control-center, it just hangs (or wait infinitely ) after giving my number. It worked for me before in 14.04 with empathy-3.10.  Not sure why it is not working now. In fact every other pidgin plugin (skype, hangout, yahoo etc) works through telepathy-haze **except this**. Can you please confirm that whole thing works in 16.04 or in 16.10 (empathy-3.12)?

**Comment by majn** [comment]
It doesn't display a popup (cause it can't), it will open a conversation that asks you for the SMS verification code.

**Comment by khurshid-alam** [comment]
> It doesn't display a popup (cause it can't), it will open a conversation that asks you for the SMS verification code.

Exactly. And I am not getting that chat window asking for verification, nor do I get any sms. I will come up with a gif/mp4 to explain what is exactly happening here.

**Comment by majn** [comment]
Do you have two factor authentication and provided a password?

**Comment by khurshid-alam** [comment]
>Do you have two factor authentication and provided a password?

No. Is that required? For me it doesn't even try to authenticate, it says **authentication failure** the moment I try to add my phone number.

Screencast: https://dl.dropboxusercontent.com/s/2zgdycxuii5tqae/pidgin-tg.webm

**Comment by majn** [comment]
The screencast gives me a 401 Error ;)

**Comment by khurshid-alam** [comment]
Ah. Sorry. Fixed now.

**Comment by majn** [comment]
Can post get the Telepathy log while you attempt to login? Without it its almost impossible to debug this.

https://telepathy.freedesktop.org/wiki/DeveloperNotes/Debugging/

**Comment by khurshid-alam** [comment]
mission-control log from empathy-debugger:

```
 13:35:53.813669: _mcd_connection_release_tp_connection: 0x9747268
 13:35:53.813734: _mcd_account_set_connection_status: haze/telegram/_2b9194331917110: 2 because 3
 13:35:53.813795: mcd_account_freeze_properties: haze/telegram/_2b9194331917110
 13:35:53.813854: _mcd_account_set_connection_status: changing error details
 13:35:53.813919: _mcd_account_set_connection_status: changing connection status from 1 to 2
 13:35:53.813977: _mcd_account_set_connection_status: changing connection status reason from 1 to 3
 13:35:53.814038: mcd_account_changed_property: called: Connection
 13:35:53.814096: mcd_account_changed_property: First changed property
 13:35:53.814384: mcd_account_changed_property: called: ConnectionStatus
 13:35:53.814461: mcd_account_changed_property: called: ConnectionStatusReason
 13:35:53.814526: mcd_account_changed_property: called: ConnectionError
 13:35:53.814599: mcd_account_changed_property: called: ConnectionErrorDetails
 13:35:53.814670: mcd_account_thaw_properties: haze/telegram/_2b9194331917110
 13:35:53.814728: emit_property_changed: called
 13:35:53.814902: connection_should_reconnect: error code org.freedesktop.Telepathy.Error.AuthenticationFailed, not reconnecting
 13:35:53.814973: _mcd_operation_abort: Operation abort received, aborting all children
 13:35:53.815033: on_connection_abort: called (0x9747268, account haze/telegram/_2b9194331917110)
 13:35:53.815103: _mcd_mission_set_parent: child = 0x9747268, parent = (nil)
 13:35:53.815166: mcd_operation_remove_mission: removing mission: 0x9747268
 13:35:53.815227: _mcd_connection_dispose: called for object 0x9747268
 13:35:53.815287: _mcd_connection_release_tp_connection: 0x9747268
 13:35:53.815352: _mcd_operation_dispose: operation disposed
 13:35:53.815413: _mcd_mission_dispose: mission disposed 0x9747268
 13:35:53.816003: mcd_dispatcher_lost_connection: 0x976a238: 0x9747268
 13:35:53.816097: _mcd_mission_finalize: mission finalized 0x9747268
 13:35:53.816414: on_connection_ready: got error: Unable to sign on as +919433191711: file (public key) not found.
```

Not sure which public key it is talking about?

**Comment by majn** [comment]
Does the file /etc/telegram-purple/server.tglpub exists and is readable to empathy?

**Comment by BenWiederhake** [comment]
The log is incomplete.  Look for the string `both didn't work. abort.`, shortly before that it gives the two paths where it expects the global/local keys.

How did you install telegram-purple?  The make-target `local_install` doesn't work with telepathy-haze, as documented in `telegram-base.c::get_user_pk_path()`.  So if that's the case, try again to install with `sudo make install` instead.

**Comment by khurshid-alam** [comment]
@majn 

Yes. It does exist. But only root has access to it. Could that be the problem? 

```
$ ls -la /etc/telegram-purple/server.tglpub
-rw-r--r-- 1 root root 264 Mar 20 19:40 /etc/telegram-purple/server.tglpub
```

@BenWiederhake 

>The log is incomplete. Look for the string both didn't work. abort., shortly before that it gives the two paths where it expects the global/local keys.

Yes, I only copied the gist of it. I will try again

I installed from webupd8 ppa. https://launchpad.net/~nilarimogard/+archive/ubuntu/webupd8/+sourcepub/7565640/+listing-archive-extra

**Comment by BenWiederhake** [comment]
The file permissions are okay, `-rw-r--r--` means that everyone can read it.

@installation: Nevermind, if there's a `/etc/telegram-purple/server.tglpub`, then all is fine.

If telegram-purple doesn't find that file, then something went seriously wrong, because that path is hardcoded into `telegram-purple.c:44`.  The log outputs will probably be enlightening and tell us where tgp tried to look instead.

Meanwhile, let me ask you another question:  SELinux and AppArmour [have been problematic](https://github.com/majn/telegram-purple/issues/61#issuecomment-147072172) in the past by preventing read-access to that file.  Do you use either of these, or other "chroot jailing" things?  If you don't recognize any of these terms, then the answer is probably "no".

**Comment by khurshid-alam** [comment]
I copied server.tglpub to ~/.purple/telegram-purple/.....but that didn't really fixed the issue for 16.04 or 16.10, although in Trusty, it `didn't` complain about not finding public key, it produced some other error (I am investigating this now).


Ubuntu by default uses apparmour, and in  /etc/apparmor.d/usr.lib.telepathy I could only found this:
```
    /usr/lib/purple*/            r,
    /usr/lib/purple*/*.so        mr,
    /usr/lib/telepathy/*/        r,
    /usr/lib/telepathy/*/*.so    mr
```

But telegram-purple installed in `/usr/lib/purple-2/telegram-purple.so`, so that needs to be included. But what should be permission for `/etc/telegram-purple/server.tglpub`? `r `?

**Comment by BenWiederhake** [comment]
> in Trusty, it didn't complain about not finding public key, it produced some other error

Trusty is 14.04, right?  That's probably so oudated that you would need to do some black magic about providing a compatible crypto library.  So Trust is a bad idea.

(There is a way, though: either install `libgcrypt20{,-dev}` from backports and `./configure && make && sudo make install`, or install any version of openssl and `./configure --disable-gcrypt && make && sudo make install`.  But I really recommend against that, it's unnecessarily fragile.)

> Ubuntu by default uses apparmour, …
> But telegram-purple installed in /usr/lib/purple-2/telegram-purple.so, so that needs to be included.

Absolutely right, you found the same bug as [back then](https://github.com/majn/telegram-purple/issues/61#issuecomment-147072172), and it's in AppArmour being too restrictive here.  So please copy server.tglpub to `~/.purple/telegram-purple/server.tglpub`.

I'm sorry for the inconvenience, but please file a bug against AppArmour because that's where the problem comes from.

**Comment by khurshid-alam** [comment]
>Trusty is 14.04, right?

Yes. I have a old machine lying around (with 14.04 installed), So I just wanted to test it whether I can reproduce the issue. Please Ignore it.

**But I already solved the problem. The issue was indeed in apparmour**. 


>EDIT: If you manage to find out how to add a rule to AppArmour (I didn't manage to do so, back then), please tell us which line is needed where, then we'll add it to the README.

Gladly.

The rules should be added to `/etc/apparmor.d/usr.lib.telepathy` under 

```
/usr/lib/telepathy/telepathy-* {
....
....
}
```

Users can manually add it. Here is the patch.

```diff
--- a/etc/apparmor.d/usr.lib.telepathy
+++ b/etc/apparmor.d/usr.lib.telepathy
@@ -159,6 +159,16 @@
     /usr/lib/libproxy*/*/modules/     r,
     /usr/lib/libproxy*/*/modules/*.so mr,
 
+    # for purple telegram
+    /etc/telegram-purple/server.tglpub r,
+    /usr/lib/purple-2*/		r,
+    /usr/lib/purple-2/*.so	mr,
+    /usr/share/locale/*/LC_MESSAGES/*.mo r,
+    /usr/share/pixmaps/pidgin/protocols/{16,32,48}/*.png r,
+    @{HOME}/.purple/telegram-purple/** rw,
+     
     # for telepathy-butterfly (LP: #816429)
     #include <abstractions/python>
```

The one must relaod apparmor profile. On Debian/Ubuntu:

`sudo service apparmor reload`

Now Everything works ok...
(except 2 issues: 
1. it asks for sms code every time It gets to online from offline
2 No Telepathy groups

But These are separate issues. )

I will file a bug about this. Thanks for help. Much appreciated.

**Comment by BenWiederhake** [comment]
Thanks for the detailed instructions!

**Comment by EionRobb** [comment]
```
+    /usr/lib/purple-2*/		r,
+    /usr/lib/purple-2/*.so	mr,
```
That one's not necessary since you've already got 
```
    /usr/lib/purple*/            r,
    /usr/lib/purple*/*.so        mr,
```

**Comment by khurshid-alam** [comment]
@EionRobb 

Right. I also noticed that telepathy would require read-write access for ~/.telegram-purple. It solved the issue-1 from above comment. I updated the patch with that.

**Comment by khurshid-alam** [comment]
Sorry I forgot...this is the bug: https://bugs.launchpad.net/ubuntu/+source/telepathy-mission-control-5/+bug/1708375
