### ISSUE TITLE
Crash on Startup - accessing deleted chats

### ISSUE THREAD

**Issue by uudruid74** [majn/telegram-purple#348]
I've noticed a lot of odd behavior such as people coming back into the "Telegram" group after moving them to another group, secret chats that keep coming up in my buddy list long after they've been closed and deleted, and now chats are coming back after the chat has been deleted.  Only in this instance, a deleted chat crashes pidgin and I can't use it!

Here is a full log ...  http://pastebin.com/GmGXYfya
I don't see a way to do a direct upload from Octodroid, but piping logs to pastebin is pretty easy.  Enjoy!

**Comment by majn** [comment]
This is now fixed on dev-1.4.0, I will leave this ticket open until the fix was merged into the main branch

**Comment by BenWiederhake** [comment]
Included in 1.3.1, if majn is correct.

**Comment by BenWiederhake** [comment]
Feel free to reopen it if you have any issue.
