### ISSUE TITLE
Bot Keyboards Not Displayed In Adium

### ISSUE THREAD

**Issue by poyntz** [majn/telegram-purple#355]
When you issue commands to Telegram bots and a keyboard displays in Telegram web (http://pasteboard.co/DZb9UnJtP.png), the keyboard does not display in Adium and no message received (http://pasteboard.co/DZd1qRTTG.png) preventing the user from progressing.    In the example, I typed the /join command which traditionally brings up a keyboard full of options, i.e, 'JA', which the user clicks in the web client to bring up the next detail.

Non-interactive commands (ie, plain text response only) seem to work ok. (e.g, /refresh from the example - http://pasteboard.co/DZiK72IBx.png). 

Adium version: 1.5.10.2
telegram-purple version: 1.3.0
Mac OS X version: 10.10.5

For API information on bot keyboards, please refer to https://irazasyed.github.io/telegram-bot-sdk/usage/keyboards/

**Comment by majn** [comment]
This can be nicely implemented with the purple request API request.h, but it won't work with clients that don't implement requests.h (e.g. telepathy-haze).

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
