### ISSUE TITLE
Uninstall wizard

### ISSUE THREAD

**Issue by Schmaiffe** [majn/telegram-purple#356]
Hi, I installed the Telegram third-party extension into Pidgin on Windows 10 using the wizard, but decided after that I didn't want it. A friend gave me a list of .dlls to delete, but honestly I'm not convinced I won't break Pidgin entirely if I delete them because they say they were created/modified a while ago, not today. So meanwhile I'm stuck with this on my computer. It was an easy click of a button to install, but I can't remove it.

**Comment by EionRobb** [comment]
The installer should have added an uninstaller to the Programs and Features list in Control Panel. On the other hand, there's not much reason to get rid of it other than saving a couple of megabytes of dlls, just removing the account from Pidgin will stop it from being used.

**Comment by Schmaiffe** [comment]
Thank you for the reply! I looked in the Programs and Features list, and I saw Pidgin, but not this plugin. Do I need to reboot my computer first for it to show up?

I know it's not really a big deal, I just don't like installing things, realizing I won't use them, and leaving them on. It feels sloppy to me.

**Comment by BenWiederhake** [comment]
Any updates on this?  I have no idea how Windows Installers work, but I thought that the `nsi` is also used to uninstall all stuff?

@Schmaiffe: Could you point out a few files that you think should have been deleted?

**Comment by Schmaiffe** [comment]
Hi, I actually have no idea either, sorry. I just know that there's no uninstall option at all, and that Telegram appears as an option to add a new account (so it's obviously still installed.) I didn't go deleting files because I didn't want to delete the wrong ones by mistake and break something else. So the very problem is I don't know what files are relevant. But I assume it would be more or less the same on any Windows install, so easy to reproduce.

I...kind of just gave up and left it. I do wish I'd known there was no uninstall before trying it, but I guess it's not really a big deal.

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
Of course, Pull Requests are still very much welcome!
