### ISSUE TITLE
Handle new invite link format

### ISSUE THREAD

**Issue by majn** [majn/telegram-purple#357]
Instead of an access hash 

https://telegram.me/joinchat/MarB8wG2fUzQwJbaccL5drZ some channels and supergroups seem to have a 

Some invite links seem to use a human readable format that uses the /@name of a channel, handle that special case.

**Comment by BenWiederhake** [comment]
This is (probably) already implemented in [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
