### ISSUE TITLE
Clean up README

### ISSUE THREAD

**Issue by majn** [majn/telegram-purple#360]
To make the README less bloated we should only keep the installation/compilation manual on the first page and move everything else to the new WIKI functionality.

User Manual:
- First Steps: Login, Authentication & Buddy List
- Group Chats
- Secret Chats
- File Transfers

Tweaking:
- Pidgin Emojis
- Pidgin Groupchat Typing-Notifications

Clients:
- Libtelepathy / Empathy

FAQ

Hacking:
- Submitting Bug Reports
- Custom Public Key

Packaging:
- Debian
- Adium

**Comment by unansweredocd** [comment]
I'll gladly do it for you.

**Comment by BenWiederhake** [comment]
Currently it's good enough, and the project sees too little activity anyway.
