### ISSUE TITLE
no group chats visible

### ISSUE THREAD

**Issue by mightyBroccoli** [majn/telegram-purple#365]
I am using spectrum2 with a compiled dev-1.4.0 version of telegram-purple. It works fine I can send and receive messages and everything works. But my Channels and even normal groups are completely absend. But in the backend log I can see that the server receive the messages but my client is not displaying anything.  In the backend log I get the message.

> 4949: 2017-03-30 17:29:26,212 INFO  backend: Received message body='Message' xhtml='' name='Channel NAme' Random Person
> 4949: 2017-03-30 17:29:26,213 ERROR backend: GLib g_string_free: assertion 'string != NULL' failed

I used the 1.3.0 version of telegram-purple but then i didnt even get the message in the backend log. I am not sure what I did wrong.

---- edit ----
Ok I just recompiled the 1.3.0 version and now I can see the channel messages in the logfile but not in my im client. This is the reaction in the backend log file.

> 11248: 2017-03-30 18:05:02,811 INFO  libpurple: prpl-telegram:tgp_msg_recv before=(nil) server_id=5381
> 11248: 2017-03-30 18:05:02,811 INFO  libpurple: prpl-telegram:setting channel message server_id=
> 11248: 2017-03-30 18:05:02,811 INFO  backend: Received message body='message' xhtml='' name='creative Channel Name' mightyBroccoli
> 11248: 2017-03-30 18:05:02,811 INFO  libpurple: prpl-telegram:sending all pending recipes
> 11248: 2017-03-30 18:05:02,811 INFO  libpurple: prpl-telegram:tgl_do_mark_read (1078253661)
> 11248: 2017-03-30 18:05:02,812 INFO  libpurple: prpl-telegram:Sent query #6403323324534081536 of size 24 to DC 2
> 11248: 2017-03-30 18:05:02,812 INFO  libpurple: prpl-telegram:tgp_msg_process_in_ready, queue size=0
> 11248: 2017-03-30 18:05:02,812 INFO  libpurple: prpl-telegram:wrote state file: wpts=16230 wqts=0 wseq=150 wdate=1490889890
> 11248: 2017-03-30 18:05:02,812 INFO  libpurple: prpl-telegram:wrote secret chat file: 0 chats written.

**Comment by mightyBroccoli** [comment]
I think this refers to majn/telegram-purple#295

**Comment by mightyBroccoli** [comment]
Is this even problem with your software or am I doing something wrong?

**Comment by mightyBroccoli** [comment]
I discoverd something that is maybe interesting. I installed your plugin in my local pidgin and the groupchats and channels work perfectly.
In my local installation of purple the accounts.xml 
```
<account>
		<protocol>prpl-telegram</protocol>
		<name>+phonenumber</name>
		<statuses/>
		<settings>
			<setting name='media-size-threshold' type='int'>8192</setting>
			<setting name='buddy_icon_timestamp' type='int'>0</setting>
			<setting name='send-read-notifications' type='bool'>1</setting>
			<setting name='password-two-factor' type='string'></setting>
			<setting name='last-server-id/123456789' type='int'>6047</setting>
			<setting name='inactive-days-offline' type='int'>5</setting>
			<setting name='compat-verification' type='bool'>0</setting>
			<setting name='display-read-notifications' type='bool'>1</setting>
			<setting name='accept-secret-chats' type='string'>ask</setting>
			<setting name='history-retrieve-days' type='int'>30</setting>
			<setting name='auto-join-group-chats' type='bool'>1</setting>
			<setting name='use-global-buddyicon' type='bool'>1</setting>
		</settings>
		<current_error/>
</account>
```
and on the server spectrum instance of purple the account.xml
```
<account>
		<protocol>prpl-telegram</protocol>
		<name>+phonenumber</name>
		<alias>mightyBroccoli</alias>
		<statuses/>
		<settings>
			<setting name='custom_smileys' type='bool'>0</setting>
			<setting name='direct_connect' type='bool'>0</setting>
			<setting name='buddy_icon' type='string'><ydgsdxhcfzj.png</setting>
			<setting name='compat-verification' type='bool'>1</setting>
			<setting name='last-server-id/1078253661' type='int'>6047</setting>
			<setting name='buddy_icon_timestamp' type='int'>1491861237</setting>
		</settings>
		<settings ui='spectrum'>
			<setting name='auto-login' type='bool'>1</setting>
		</settings>
		<current_error/>
</account>
```
I am confused the plugin works perfectly with my local pidgin and as a transport with spectrum2 the groupchats and channels dont even appear even though the backend log seems to capture the messages as seen above.

Can someone help me ? @majn ? or @EionRobb ?

**Comment by BenWiederhake** [comment]
Most definitely a combination of #295 and spectrum2's failure to gracefully handle that.  Feel invited to tell us where to add "one call to in_progress with complete=true", like @vitalyster put it.  I have no idea whether that's the reason, but it sounds plausible.

**Comment by vitalyster** [comment]
@BenWiederhake skypeweb, facebook and hangouts plugins works correctly in spectrum2, see https://github.com/EionRobb/skype4pidgin/blob/master/skypeweb/skypeweb_messages.c#L1001 for example

**Comment by vitalyster** [comment]
and https://github.com/EionRobb/skype4pidgin/blob/master/skypeweb/skypeweb_messages.c#L977 when completed :)
