### ISSUE TITLE
Add Telegram Channels to Empathy (Telepathy-Haze)?

### ISSUE THREAD

**Issue by khurshid-alam** [majn/telegram-purple#367]
I noticed that when I add an account through telepathy-haze, everything works except channels. They do not show up as contacts.

I realized 

1. In Pidgin channels just act as a room. I can also get the **id** of the room from `edit room` preference.

2. So it should also be possible to add channels as room in empathy as well. All I need is to have the name of the server and room id (which I already have in pidgin)

I tried adding them as contacts but that didn't work. So How do I add channels in Empathy?

**Comment by EionRobb** [comment]
Unfortunately telepathy-haze doesn't support group chats from libpurple plugins, only one-to-one IMs
