### ISSUE TITLE
Switch off all group and channels

### ISSUE THREAD

**Issue by korjavin** [majn/telegram-purple#370]
Is it possible to consider adding an option to switch off all channels and groups + supergroups, and receive only direct messages?

**Comment by majn** [comment]
Why?

**Comment by korjavin** [comment]
Pidgin doesn't show reply-to and other things.
In a crowdy group it became a mess. You just can't react adequately.

**Comment by majn** [comment]
If you don't wanna see chats make them "persistent" then they will just run in the background and write history, but not pop up on every new message.
