### ISSUE TITLE
Do not display deletes that have been deleted before receiving them for the first time

### ISSUE THREAD

**Issue by majn** [majn/telegram-purple#375]
Messages cannot be deleted from the history, but they can not be displayed if a message is already known to be deleted.

Currently it does not behave like that:
1. Send a message on a different client to another tgp client
2. Delete the message before it was read
3. Message is displayed in tgp

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
