### ISSUE TITLE
RFE: Voice calls support

### ISSUE THREAD

**Issue by alex3kov** [majn/telegram-purple#377]
https://telegram.org/blog/calls  
Disclaimer: I have no idea if that's even possible in a plugin.  
If this were to be implemented, I'd blackmail all my friends to switch to Telegram so I can make calls from my Linux PC.

**Comment by majn** [comment]
Apparently sipe prpl has implemented audio conforences with gstreamer, so it might be possible. But the effort would be huge, cause there isn't even support for voice calls libtgl yet.

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements, so I'm closing them all.
