### ISSUE TITLE
Cannot build latest git version on gentoo (_FORTIFY_SOURCE redefined)

### ISSUE THREAD

**Issue by Penaz91** [majn/telegram-purple#381]
As from title, building the live version (-9999, pulled from Git), doesn't work on gentoo.
I'm attaching the build log, hoping it helps a bit.
Thank you a lot for this plugin, it really makes my life a lot easier :+1: 
[build.zip](https://github.com/majn/telegram-purple/files/925265/build.zip)

**Comment by Penaz91** [comment]
So it seems like the workaround doesn't work. The error stays and kind of looks like the -U_FORTIFY_SOURCE flag is ignored
[build.zip](https://github.com/majn/telegram-purple/files/925818/build.zip)

**Comment by BenWiederhake** [comment]
I just wondered why this is considered an error, not just a warning, until I remembered about tgl's use of `-Werror`.  Having a warning about that is fine, so I left it in.

I already pushed to the main repo, so please pull from majn's `dev-1.4.0` branch.

**Comment by Penaz91** [comment]
Pulling from said branch worked perfectly. Closing as wolved.
