### ISSUE TITLE
Mark delivered/read messages somehow 

### ISSUE THREAD

**Issue by alex3kov** [majn/telegram-purple#386]
Something like green checks in their mobile app https://telegram.org/faq#q-what-do-the-green-checks-mean

**Comment by BenWiederhake** [comment]
libpurple doesn't offer any API for that, and in the account preferences there already is an option that prints out each and every read receipt.

**Comment by ildar** [comment]
Yep, and it looks ugly. Maybe it's worth making the request to pidgin team
to remove all but one read receipts?

**Comment by BenWiederhake** [comment]
Sadly, that's not how it works.  What actually happens is that telegram-purple uses the "system message" feature to print the read receipt line.  So it would require a wholly new API to change anything about this.

I agree that this is ugly, but I don't see any other way of handling it.  Feel free to re-open if you find a better way to interface with libpurple.

**Comment by EionRobb** [comment]
Would be interesting if it could work with the XMPP Receipts plugin, which adds a tick next to every sent message which was received

**Comment by BenWiederhake** [comment]
Sounds very interesting, but it uses a function which starts with [`gtk_text_buffer_…`](https://github.com/kontalk/pidgin-xmpp-receipts/blob/0f4d50b6609a7ac71144acfbce5edd40025ed55c/xmpp-receipts.c#L121), so it sounds pretty pidgin-specific.  Just like the build-instructions say:

> You will need pidgin development packages
> (link in ubuntu: libpurple-dev and pidgin-dev).

So at best it would be an optional thing, for example enabled by `./configure --pidgin-read-receipt` or so.
