### ISSUE TITLE
Segfault of unknown cause

### ISSUE THREAD

**Issue by seirl** [majn/telegram-purple#39]
This segfault happens quite regularly, still don't understand in what circumstances exactly.
I'm using bitlbee with libpurple.

    #0  alarm_query () at tgl/queries.c:110
    110	    q->msg_id = tglmp_encrypt_send_message (TLS, q->session->c, q->data, q->data_len, (q->flags & QUERY_FORCE_SEND) | 1);
    (gdb) bt
    #0  alarm_query () at tgl/queries.c:110
    #1  0x00007fce8d960221 in timer_alarm () from /usr/lib/purple-2/telegram-purple.so
    #2  0x00007fcea0ac3eeb in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
    #3  0x00007fcea0ac3355 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
    #4  0x00007fcea0ac3688 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
    #5  0x00007fcea0ac3a82 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
    #6  0x00007fcea16afd93 in main ()

**Comment by majn** [comment]
I think it may be a bug in libtgl, some timers arent removed when the connection is freed, and once the timers are called it crashes. Ive already submitted a pull request.

**Comment by majn** [comment]
I've pointed the current version of the repo to my tgl pull request, which fixes this issue.

If you pull, please make sure that all submodules are correctly synchronised and updated, easiest is to just clone a fresh version of this repository.
