### ISSUE TITLE
Show replies in groupchats better

### ISSUE THREAD

**Issue by mindcombatant** [majn/telegram-purple#390]
Currently, in groupchats, replies do not work as expected. In official clients, you see the message that the reply is to repeated, then the reply itself. In Pidgin with telegram-purple, you only see the reply itself. If the reply was to a message you sent, the username is highlighted, but still does not show which message of yours was replied to. I feel this could be handled better, maybe the reply could be split up, with the message replied to showing up again as a "forward" (because forwarded messages work nicely and as I would expect), and then the reply?

**Comment by mindcombatant** [comment]
i apologize in advance if this is already fixed in dev-1.4.0, i can't test that as it's unstable for me.

**Comment by majn** [comment]
Implemented on dev-1.4.0
