### ISSUE TITLE
Can't see my own messages in IM window if I write in Persian

### ISSUE THREAD

**Issue by solsav** [majn/telegram-purple#394]
OS:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.8 (jessie)
Release:	8.8
Codename:	jessie
```
Pidgin version:
```
$ pidgin -v
Pidgin 2.11.0 (libpurple 2.11.0)
```
source code obtained from:
`https://github.com/majn/telegram-purple`

Issue description:
When I type in my message in Persian, I do not see my own message in the message box (the IM window) but I see the others' messages in either Persian or English

**Comment by BenWiederhake** [comment]
Another instance of #339, as Persian is a right-to-left.  This would mean that *sending* your messages already fails, so nobody else sees your Persian messages.

Sigh.  I guess i'll have to implement the dirty workaround and hope that pidgin doesn't insert any other wierd stuff.  (Just to reiterate: it's technically pidgin's fault, as that tag is not supposed to be there.)

**Comment by BenWiederhake** [comment]
Could you try it again with the latest commit on `dev-1.4.0`?  I can now send messages in a RTL-language.  If it doesn' work, please let's continue in #339.
