### ISSUE TITLE
Issues with an adding Telegram users in a Pidgin

### ISSUE THREAD

**Issue by ghsrcgh** [majn/telegram-purple#399]
I'm not sure this is relate 100% for a plugin, but I think it provides an API for a Pidgin common interface. (If it is  not related to the plugin core, please specify and I will create a bug in a Pidgin's bugtracker)

When I trying to add Telegram user by his "@nickname" (without quotes) - it is not working. It is working only in case if I writing his "FirstName LastName" in add user window. I.e. I'm unable to add user by a nickname, that is very strange to see.

pidgin-2.12.0-offline.exe
telegram-purple-1.3.0rev2.exe

P.S. Moreover, due to this issue, I did not understand how to add any group (telegram channel) to read it. Because all of them are using @telegram_channel_name nicknames.

**Comment by ghsrcgh** [comment]
Will someone check this?

**Comment by majn** [comment]
Well I use the full name as unique user ID, cause not everyone has a @-username in Telegram

**Comment by ghsrcgh** [comment]
I understand that not all users have @-username. But why I cannot add users by @-username if specified user have it?

"FirstName LastName" are not unique BTW, except of @-username.

**Comment by BenWiederhake** [comment]
No specific reason, other than that nobody implemented it so far.

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple), which might already have this enhancement. For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
