### ISSUE TITLE
You are unable to start Secret Chat from a Contact List in Pidgin

### ISSUE THREAD

**Issue by ghsrcgh** [majn/telegram-purple#400]
I'm not sure this is relate 100% for a plugin, but I think it provides an API for a Pidgin common interface. (If it is  not related to the plugin core, please specify and I will create a bug in a Pidgin's bugtracker)

I found only a one way (this was REALLY hard to find) to create Secret Chat in a Pidgin: in a Conversations tabbed windows you need to select one tab with a non-secret chat with the user (!), then you need to click on the top menu (!) "Conversation", than select "More ->", then "Start secret chat..."

It is absolutely non user-friendly.

How it must be (best ways):
1) Right click on user name tab in a conversation window and select "Start secret chat..." (even if some submenu will be required)
2) Right click on user name in a contact list (buddy list) and select "Start secret chat..." (even if some submenu will be required)

pidgin-2.12.0-offline.exe
telegram-purple-1.3.0rev2.exe

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.

(Note that tdlib-purple doesn't implement secret chats yet.)
