### ISSUE TITLE
"Get info" on user if it is added "strangely" just hanging and never stops (Pidgin)

### ISSUE THREAD

**Issue by ghsrcgh** [majn/telegram-purple#401]
I'm not sure this is relate 100% for a plugin, but I think it provides an API for a Pidgin common interface. (If it is  not related to the plugin core, please specify and I will create a bug in a Pidgin's bugtracker)

This issue is also related to the #399 

For example, I trying to add user @nickname as "@nickname" (without quotes) and "nickname" (without quotes). One user just a two ways of trying to add. Both "users" are offline and I can't send messages to them (because of #399).

But when I trying to use right click and select "Get Info..." about user (to see anything) I see only "Info: Retreiving..." and that all. Nothing more. No timeouts, no errors. No info. Just nothing.

pidgin-2.12.0-offline.exe
telegram-purple-1.3.0rev2.exe

**Comment by majn** [comment]
Well this is just an effect of not supporting adding by @username
