### ISSUE TITLE
Issue with an image downloads in Secret Chats (Pidgin)

### ISSUE THREAD

**Issue by ghsrcgh** [majn/telegram-purple#402]
I'm not sure this is relate 100% for a plugin, but I think it provides an API for a Pidgin common interface. (If it is  not related to the plugin core, please specify and I will create a bug in a Pidgin's bugtracker)

I'm using a Pidgin and created a secret chat with the user. He send me a few screenshots. All of them was shown to me like they was downloaded for a 10-15% only and then connection failed. (Text messages before, between and after - OK). It seems that plugin or client does not support continue/redownload if some issues with connection or any other issues with that? (Pictures was like a jpeg file if you will kill about 80% data of the file, tail of the file).

In Pidgin options: Media auto-download 8192 kb
Downloaded files (damaged): 49720 bytes and 133372 bytes.

pidgin-2.12.0-offline.exe
telegram-purple-1.3.0rev2.exe

**Comment by majn** [comment]
https://github.com/majn/telegram-purple/issues/151
