### ISSUE TITLE
GetInfo does not show key's fingerprint of secret chat as hex (only as picture) (Pidgin)

### ISSUE THREAD

**Issue by ghsrcgh** [majn/telegram-purple#403]
Official mobile Telegram client allows to see key's fingerprint of secret chat as hex string (not only as hipster's picture). GetInfo in Pidgin does not show key's fingerprint as hex.

pidgin-2.12.0-offline.exe
telegram-purple-1.3.0rev2.exe

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.

Note that tdlib-purple doesn't implement secret chats yet. What a bummer, this one would have been an easy fix. I'm still accepting PRs though! Pretty please write one? :D
