### ISSUE TITLE
Log file names and directories with %-symbols

### ISSUE THREAD

**Issue by ghsrcgh** [majn/telegram-purple#404]
I'm not sure this is relate 100% for a plugin, but I think it provides an API for a Pidgin common interface. (If it is not related to the plugin core, please specify and I will create a bug in a Pidgin's bugtracker)

Log file names and directories with %-symbols.
Locating telegram account, it is named: "\logs\%2b&lt;here-your-number&gt;"
%2b means +&lt;here-your-number&gt;

Going deeper: "\logs\%2b&lt;here-your-number&gt;\%21%20John%20Doe\"
that in practice means secret chat with "! John Doe"

Who is returning symbols from 0 to 48 (ascii) as %-format? Probably, you need to make this range smaller.

Available chars on Windows FS (FAT*, NTFS):
* all from 0x20 (32) to 0x2F (47), except: 22h ("), 2Ah (*), 2Fh (/)
* all from 0x3B (59) to 0x3E (62), except: 3Ah (:), 3Ch (<), 3Eh (>), 3Fh (?)

I.e. all symbols from 0x20 to 0x3F maybe used except these list (they must be converted to % or changed to "_" for example): 22h ("), 2Ah (*), 2Fh (/), 3Ah (:), 3Ch (<), 3Eh (>), 3Fh (?).

Correct path names will be (just sample):
"\logs\+12345678912\! John Doe\"

pidgin-2.12.0-offline.exe
telegram-purple-1.3.0rev2.exe

**Comment by EionRobb** [comment]
Protocol plugins do not have control over how a UI (such as Pidgin) stores it's logs

**Comment by ghsrcgh** [comment]
Okay, thank you. Moving to https://developer.pidgin.im/ticket/17226
