### ISSUE TITLE
[Feature Request] Support for pinned messages

### ISSUE THREAD

**Issue by rodneyrod** [majn/telegram-purple#405]
Not sure what would be the best way to implement this in Pidgin, but it would be a great feature to have to have a room's description or tagline change to whatever the pinned message is.

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
