### ISSUE TITLE
non-ascii JID

### ISSUE THREAD

**Issue by p5n** [majn/telegram-purple#412]
Environment:
- telegram-purple 1.3.1-2 and spectrum2 xmpp transport connected to ejabberd on ArchLinux.

Ejabberd complains on nonascii JIDs. For example:

```
иван\20..рёв@telegram.example.com
```
So it looks like transport escapes space to \20, but does not escape cyrillic characters.

**Comment by BenWiederhake** [comment]
Sorry to hear that!  But telegram-purple has nothing to do with XMPP, so please contact the spectrum2 devs.
