### ISSUE TITLE
Option to use user's username as default contact name value?

### ISSUE THREAD

**Issue by goutsune** [majn/telegram-purple#415]
I've been using this plugin for an year or so and I replace names in my roster with aliases which look like "@username". This lets me to highlight people when I write and since usernames use only ASCII I don't get chat list distorted by emoji in sender name.

Other reason for this would be avoiding conflicts when using transports like spectrum2 or bitlbee since these work way better when user ID contains just ASCII symbols.

**Comment by majn** [comment]
Not everyone has an @-username in Telegram, which is why I cannot use them as user ID in pidgin

**Comment by Thaodan** [comment]
use display name if username is not set.
See for example teleirc for workarounds:
https://github.com/FruitieX/teleirc/blob/develop/src/config.defaults.js#L99

**Comment by pbui** [comment]
Here is a patch I am currently using so that the `print_name` defaults to the `username` if it exists, otherwise it falls back to the current method of `first_name` and `last_name`:

https://gist.github.com/pbui/b2f457f412c4aa1a6776a57896d87577

I am testing this with bitlbee + telegram-purple.

**Comment by Thaodan** [comment]
Can this be reset when the user sets a username and doesn't had one before?

**Comment by pbui** [comment]
I believe the patch above only triggers when building the intial buddy list.  It doesn't respond to updates (unfortunately).  

Overall, I'm not sure how the library responds to changes to say `first_name` and `last_name` and if it updates the `print_name` when those values change.  If it does, then we can simply apply the same methodology to update `print_name` when `username` is changed.  Otherwise, someone would need to figure out how to react to such changes.

**Comment by Thaodan** [comment]
That makes sense. I don't how purple works but 
telegram uses the first name last name as diplay 
and show the username after this.
But the only the username is used when typing 
after inserting @ and showing a preview of 
matching usernames.

**Comment by BenWiederhake** [comment]
I'm not really sure what either of you mean.  If you're willing to make an actual PR so I can look at it, I'd be happy to do so.

The print name should change as seldomly as possible, as this causes a rollover for all logs and everything.  Does this patch make the situation better or worse?

**Comment by Thaodan** [comment]
Its better and worse because you need usernames for mentions and you wont get them for uses that set a username after being inside the contact list with the patch.
In groups mentions are necessary. What do you mean by roll over? Is there a way to avoid a rollover if the print name changes?

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple), which might already have this enhancement. For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
