### ISSUE TITLE
Unable to Join Group Chat in Adium

### ISSUE THREAD

**Issue by MaxNanasy** [majn/telegram-purple#42]
OS: Mac OS X 10.10.1
Chat client: Adium 1.5.10
telegram-purple version: 0.6

Steps to reproduce:
1. Connect to a Telegram account in Adium
2. Click File > Join Group Chat
3. In the Join Chat window, under Account, select the Telegram account
4. BUG: The Join Chat window is blank except for Account

![blank-join-chat-window](https://cloud.githubusercontent.com/assets/628032/5967339/e49d307c-a7c0-11e4-833d-e2cb55491e6a.png)

**Comment by Nnubes256** [comment]
Confirmed. This can be because in Telegram group chats aren't joined directly, you are joined by someone else. This also makes the window resize a lot. As a suggestion, this menu could be used to create group chats. Something like:
```
Account: {Telegram}

<text>This menu is actually used in telegram-purple TO CREATE A GROUP CHAT.</text>
Name: [Test              ]
Invite list: <list-of-telegram-contacts-with-checkboxes>
```
This is out of this issue, however.

**Comment by majn** [comment]
Done.
