### ISSUE TITLE
How to compile for Windows?

### ISSUE THREAD

**Issue by fulalas** [majn/telegram-purple#420]
I've been compiling this plugin for Linux for so long time with no problems, but I'm struggling to compile it for Windows. Is there a step by step?

I tried with cygwin and it compiled a .so bin which seems to be a DLL (since inside I found the string: 
'This program cannot be run in DOS mode'), however even changing the extension to .dll and copying all cygwin DLLs to the same folder where Pidgin plugins are installed, telegram plugin fails to load. Anyway, even if it could work, it's not a reasonable solution; I just want one single DLL.

With MinGW I can't even execute ./configure.

Another solution would be a pre-built recent version available for download, since the version here is kind of old: http://eion.robbmob.com/telegram/

Another solution would be fixing the following bugs by some magic setting:
1- can't open received audio messages by clicking on the hyper-links, since it points to a wrong path;
2- can't receive files;

**Comment by criztovyl** [comment]
Maybe take a look at #397

**Comment by fulalas** [comment]
@criztovyl, thanks for the tip. It was a long journey until I finally got a valid DLL from mkwindows.sh script. Telegram plugin indeed loads, although during the first attempt to connect there's an error and I have to re-enable the plugin in order to be able to connect.

The bug 2 seems to be fixed. But unfortunately the bug 1 is still present.

**Comment by criztovyl** [comment]
Glad I could help.

Your first bug sounds like #414, maybe +1 there.

**Comment by fulalas** [comment]
Thanks! :)
