### ISSUE TITLE
Error: RPC_CALL_FAIL 401: SESSION_REVOKED Weechat

### ISSUE THREAD

**Issue by unansweredocd** [majn/telegram-purple#421]
Hey all, I tried using this with Weechat but it only worked the first time. I used this [link](https://wiki.archlinux.org/index.php/bitlbee#Telegram) to set it up.

After I terminated all my sessions in Telegram this message keeps showing up:
```
telegram - Logging in: Logged in
telegram - Error:: RPC_CALL_FAIL 401: SESSION_REVOKED
```
My question to you is, how do I make sure it tries to renew my session instead of using the old one. #

**Comment by criztovyl** [comment]
Telegram Purple can't handle terminated sessions yet.
You will need to delete `state`, `auth` and `secret` files in the `.purple/telegram-purple/ +yourphonenumber/` folder.

**Comment by unansweredocd** [comment]
I don't seem to have those directories on my system. Do you happen to know where the .purple directory is created on Arch?

**Comment by unansweredocd** [comment]
Issue seems to be known #419 closing this one and will be following that instead.
