### ISSUE TITLE
libtelegram.dll for Windows does not containt VERSION_INFO structure in resources

### ISSUE THREAD

**Issue by ghsrcgh** [majn/telegram-purple#433]
libtelegram.dll for Windows does not containt VERSION_INFO structure in resources
So it is unusable for debug purposes, you will see something like:
```
 Fault Module Name:	libtelegram.dll
  Fault Module Version:	0.0.0.0
```

Please add VERSION_INFO structure in resources with major, minor, revision/build versions.

**Comment by ghsrcgh** [comment]
1) Yes, but a common crash report on Windows does not contain such info. But pidgin for windows (its files) contain that info filled correctly (so, available in crashes).

2) Moreover, pidgin.RPT does not contain info about version, because of VERSION_INFO does not exist. For files, that contain VERSION_INFO in .rpt you will see:
\Pidgin\pidgin.dll [2.12.0.0]
\libgtk-win32-2.0-0.dll [2.16.6.0]
and so on.

So for Windows it is really actual.

P.S. BTW, please build 1.3.1 version, if possible.

**Comment by BenWiederhake** [comment]
Hey @ghsrcgh, does this work for you? https://github.com/majn/telegram-purple/pull/446#issuecomment-379464670
