### ISSUE TITLE
Reply with a quote is displayed as a regular message

### ISSUE THREAD

**Issue by alex3kov** [majn/telegram-purple#435]
In telegram mobile app replies with a quote are displayed roughly like this:
```
| *User1*
| I'm right.  

No, you're wrong.
```
In Pidgin the quoted part ("I'm right." and username) is not displayed.

**Comment by M1cRO** [comment]
In branch dev-1.4.0 it works.

**Comment by luisg123v** [comment]
Yes, it has been solved in https://github.com/majn/telegram-purple/commit/af200e0b38c48fac0b1c1d7d534938576dbd5c11

**Comment by BenWiederhake** [comment]
Should be fixed in [v1.4.1](https://github.com/majn/telegram-purple/releases/tag/v1.4.1).
