### ISSUE TITLE
Option to use some kind of unique ID as contact IDs?

### ISSUE THREAD

**Issue by himselfv** [majn/telegram-purple#437]
Telegram-purple uses nicknames or first+second names as user "names". With Spectrum2, these translate into jabber IDs which are supposed to be unique and stable. But these names can change, can't they?

If I'm reading this correctly, with Pidgin telegram-purple saves additional constant for each buddy list entry which stores actual ID. But this is telegram-purple dependent, so spectrum2 as a plugin neutral transport probably can't rely on that.

If you don't mind, can you please add an option to use some kind of stable IDs as user "names"? I would much prefer to have ugly but reliable jabber IDs and actual nicknames can be set via alias (again, if I'm understanding correctly what's going on here).

For instance, another standalone telegram transport uses "u1234567" format (u + base 10 number).

What that number is I don't know, but from looking at ```tgl_user```, maybe it's peer ID? If it's stable and consistent between accounts (even better).

**Comment by BenWiederhake** [comment]
This goes back to 4eeb7f73c9bdff4fc3eac31ac6d5d7e720c96b9d , where it was decided that Telegram-assigned user-IDs are "not unique enough", and were actually worse than just the printnames set by the users.

You're right that IDs have significant advantages over names, but that's how we currently roll.  If enough people complain, maybe we change it back again.  (This would make it *another* breaking change!)

Also, sorry for not seeing your ticket for a full year.

**Comment by himselfv** [comment]
Thanks! Okay, I'll have to settle on doing something downstream then. By the way, the commit only talks about
> This means that getting a useful username in the interface relied on the alias resolution,
>  which unfortunately doesn't work when a user isn't in the buddy list, or in Adium group chats.

If I'm reading this right, this is a libpurple thing. Are there some other ways in which Telegram IDs are not unique enough that I should know about?
