### ISSUE TITLE
Newer Windows download available?

### ISSUE THREAD

**Issue by Foxtaur** [majn/telegram-purple#439]
The install instructions say that Windows users should visit Eion Robb's page, where the version available there is 1.3.0.  Is that still the "official" release, or is there a later version available somewhere?

**Comment by Foxtaur** [comment]
Thanks for uploading that version.

I'm confused though, because the file you uploaded is called "telegram-purple-1.4.0-dev+g811125cc60.exe" which seems to imply plugin version 1.4.0.  But when viewing the About / Plugins info, the version is listed as 1.3.1.

I was able to install it, but regrettably it does not fix my Telegram issue.  Most closely resembles #418.

Thank you for the upload, though.  :)

**Comment by BenWiederhake** [comment]
It says "1.4.0-dev" right there.  So "the development version which is going to be 1.4.0 in a while", or rather: "if anyone ever works on it again".

**Comment by rodneyrod** [comment]
@BenWiederhake Is no one currently working on it? If that's the case, shouldn't the readme state that it's unmaintained?

**Comment by BenWiederhake** [comment]
Which would require effort and someone actually pushing a new commit, which in turn would mean that someone *does* work on it.  Now you know why unmaintained projects never have an "unmaintained" notice.

**Comment by BenWiederhake** [comment]
Will be fixed by #446.  Can you check whether [the installer](https://github.com/majn/telegram-purple/pull/446#issuecomment-379464670) works?

**Comment by BenWiederhake** [comment]
Should be fixed in [v1.4.1](https://github.com/majn/telegram-purple/releases/tag/v1.4.1).
