### ISSUE TITLE
Can't send messages with non Latin characters (tested Hebrew and Arabic)

### ISSUE THREAD

**Issue by doronbehar** [majn/telegram-purple#440]
I've downloaded and installed the plugin for pidgin and I can't send messages in Hebrew and Arabic, perhaps other languages are not fully supported as well.

I ran `pidgin -d` and tried to catch some meaningful insights regarding the problem and these are the lines that came out when I typed the message in Hebrew:
```
(21:21:06) prpl-telegram: tgprpl_send_typing()
(21:21:06) prpl-telegram: Sent query #6514328361868554240 of size 24 to DC 4
(21:21:07) prpl-telegram: tgprpl_send_typing()
(21:21:07) prpl-telegram: Sent query #6514328365020257280 of size 24 to DC 4
(21:21:09) prpl-telegram: tgprpl_send_im()
(21:21:09) prpl-telegram: parsed 0 images in messages
(21:21:09) prpl-telegram: tgprpl_send_typing()
(21:21:09) prpl-telegram: Sent query #6514328372988951552 of size 24 to DC 4
(21:21:09) prpl-telegram: Sending message failed.
(21:21:09) prpl-telegram: Code 22: Unknown tag
(21:21:09) prpl-telegram: Message was: <SPAN style="direction:rtl;text-align:right;">שלום</SPAN>
```
I think this is a problem with RTL languages because I tested Greek and I experienced no problem at all.

Oh and thank you so much for making this plugin, besides that it works great.

**Comment by BenWiederhake** [comment]
Already fixed in "development" version `dev-1.4.0`: https://github.com/majn/telegram-purple/issues/339#ref-commit-550dc48
