### ISSUE TITLE
Online users to be voiced

### ISSUE THREAD

**Issue by realies** [majn/telegram-purple#441]
Could online users become voiced when used with BitlBee, similarly to what the`bitlbee-facebook` plugin does?

**Comment by BenWiederhake** [comment]
Sorry for the slow response, somehow I never saw this ticket.

Sure, that sounds like a straightforward patch.  If you implement it, I'd be happy to pull it.

**Comment by realies** [comment]
Not sure how.

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple), which might already have this enhancement. For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
