### ISSUE TITLE
bitlbee telegram - Login error: Connection timeout

### ISSUE THREAD

**Issue by softcombiz** [majn/telegram-purple#443]
Hi, can't login to telegram
Archlinux
bitlbee-libpurple 3.5.1
telegram-purple 1.3.1 (also try 1.4.0-pre (git))
I add accaunt, type auth code from sms, but gets Connection timeout

[28.02.18 14:48] <support> acc telegram on
[28.02.18 14:50] <root> telegram - Login error: Connection timeout
[28.02.18 14:50] <root> telegram - Logging in: Signing off..
[28.02.18 14:50] <root> telegram - Logging in: Reconnecting in 5 seconds..

Log from bitlbee debug mode:

DEBUG prpl-telegram: tgprpl_status_types()
DEBUG account: Connecting to account +4**************.
DEBUG connection: Connecting. gc = 0x562003099340
DEBUG prpl-telegram: tgprpl_login(): Purple is telling the prpl to connect the account
DEBUG prpl-telegram: base configuration path: '/var/lib/bitlbee//purple/support/telegram-purple/+4**************'
DEBUG prpl-telegram: initializing empty auth file
DEBUG signals: Signal data for chat-conversation-typing not found!
DEBUG dnsquery: Performing DNS lookup for 149.154.175.50
DEBUG dnsquery: Performing DNS lookup for 149.154.167.51
DEBUG dnsquery: Performing DNS lookup for 149.154.175.100
DEBUG dnsquery: Performing DNS lookup for 149.154.167.91
DEBUG dnsquery: Performing DNS lookup for 149.154.171.5
DEBUG dnsquery: IP resolved for 149.154.175.50
DEBUG proxy: Attempting connection to 149.154.175.50
DEBUG proxy: Connecting to 149.154.175.50:443 with no proxy
DEBUG proxy: Connection in progress
DEBUG dnsquery: IP resolved for 149.154.167.51
DEBUG proxy: Attempting connection to 149.154.167.51
DEBUG proxy: Connecting to 149.154.167.51:443 with no proxy
DEBUG proxy: Connection in progress
DEBUG dnsquery: IP resolved for 149.154.175.100
DEBUG proxy: Attempting connection to 149.154.175.100
DEBUG proxy: Connecting to 149.154.175.100:443 with no proxy
DEBUG proxy: Connection in progress
DEBUG dnsquery: IP resolved for 149.154.167.91
DEBUG proxy: Attempting connection to 149.154.167.91
DEBUG proxy: Connecting to 149.154.167.91:443 with no proxy
DEBUG proxy: Connection in progress
DEBUG dnsquery: IP resolved for 149.154.171.5
DEBUG proxy: Attempting connection to 149.154.171.5
DEBUG proxy: Connecting to 149.154.171.5:443 with no proxy
DEBUG proxy: Connection in progress
DEBUG proxy: Connecting to 149.154.167.51:443.
DEBUG proxy: Connected to 149.154.167.51:443.
DEBUG proxy: Connecting to 149.154.167.91:443.
DEBUG proxy: Connected to 149.154.167.91:443.
DEBUG proxy: Connecting to 149.154.175.50:443.
DEBUG proxy: Connected to 149.154.175.50:443.
DEBUG proxy: Connecting to 149.154.175.100:443.
DEBUG proxy: Connected to 149.154.175.100:443.
DEBUG proxy: Connecting to 149.154.171.5:443.
DEBUG proxy: Connected to 149.154.171.5:443.
DEBUG util: Writing file accounts.xml to directory /var/lib/bitlbee//purple/support
DEBUG util: Writing file /var/lib/bitlbee//purple/support/accounts.xml
DEBUG util: Writing file blist.xml to directory /var/lib/bitlbee//purple/support
DEBUG util: Writing file /var/lib/bitlbee//purple/support/blist.xml
DEBUG prpl-telegram: tgl requests user input, tgl_value_type: 0, prompt: phone number:, count: 1
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG prpl-telegram: ping alarm
DEBUG account: Disconnecting account +4************ (0x562003154c00)
DEBUG connection: Disconnecting connection 0x562003099340
DEBUG prpl-telegram: tgprpl_close()
DEBUG connection: Destroying connection 0x562003099340
DEBUG util: Writing file accounts.xml to directory /var/lib/bitlbee//purple/support
DEBUG util: Writing file /var/lib/bitlbee//purple/support/accounts.xml
DEBUG prpl-telegram: tgprpl_status_types()

i try to remove /var/lib/bitlbee, and setup telegram again, but in second setup have no more auth verification via sms, only Connection timeout...
P.S. sorry for my bad english

**Comment by instinctualjealousy** [comment]
I haven't checked my debug but I'm getting the same issue. I had it working to start with. I did change some settings in Telegram (swapped 2FA) but even a removal, readd doesn't work. It won't prompt for authentication, it just goes EHHH and fails.

**Comment by himmijimmy** [comment]
Hi, same problem with timeouts on my fresh archlinux@armv7 install.

```
local/telegram-purple-git 1.4.0.a887786-1
local/bitlbee-libpurple 3.5.1-1

```

any hints to solve this problem?

**Comment by Michal-Szczepaniak** [comment]
Any updates on this problem? happens on many OSes.

**Comment by Michal-Szczepaniak** [comment]
I discovered that right after that error account was blocked from login because of too many logins. Then after some time it connected without problems. So that could be the problem

**Comment by BenWiederhake** [comment]
Jup, Telegram is a bit finnicky, and is quick to assume that tgp is trying to flood it.  Even though we properly back off after a `BACK_OFF`.

Feel free to reopen if this happens again.
