### ISSUE TITLE
*Feature Request* Custom Download Folder

### ISSUE THREAD

**Issue by radasbona** [majn/telegram-purple#444]
Hi,
can we get on Option in the Account Settings to chance the Location of the Download Folder?
I want to protect my SSD from unnecessary Writes. A Download Folder in /tmp or a Ramdisk would be useful.
I do already a dirty solution with hardlinks, but all Links in the chat window has a wrong (the old) destination now.

**Comment by BenWiederhake** [comment]
At first glance, this feels like too much customization.  

Hardlinks?  Why not symlinks?  For example, the following should work for you:
- Shut down pidgin
- Move `~/.purple/logs/telegram/` to your ramdisk, let's say `/mnt/telegram-logs/`
- Now that `~/.purple/logs/` has no folder `telegram` anymore, create a symlink: `ln -s /mnt/telegram-logs/ telegram`
- Start pidgin

**Comment by radasbona** [comment]
Ups, my fault, sorry. That's exactly what i did on Linux, on Windows i used Junction Link Magic. 
But not with to logs Folder, i moved the Download Folder. Many (really many) Sticker webp files and voices messages to the /tmp or the Y:/ramdisk/ Folder.
But under Windows the Chatwindow Links of the Voice messages still head the to %Appdata% Folder. 
Thats why i thought a custom download folder would be i good idea. :-)

**Comment by BenWiederhake** [comment]
> That's exactly what i did on Linux, on Windows i used Junction Link Magic.

So the problem is solved?  Great.  Feel free to re-open if there's any further problems.
