### ISSUE TITLE
[-Werror=format-overflow=] when compiling

### ISSUE THREAD

**Issue by Fubukimaru** [majn/telegram-purple#445]
Hello, 

I'm getting the following error:
```
....
tl-parser/tl-parser.c: In function 'tl_parse_args134':
tl-parser/tl-parser.c:1907:26: error: '__builtin___sprintf_chk' may write a terminating nul past the end of the destination [-Werror=format-overflow=]
         sprintf (s, "%lld", lrand48 () * (1ll << 32) + lrand48 (
....
```

Any clue on this?

I'm running a Raspberry Pi Zero (armv6h) with archlinux on it.

Thanks!

**Comment by BenWiederhake** [comment]
Already handled in https://github.com/majn/tgl/commit/147af9250832a09567ba354b6f45b2ce17b8745a

Feel free to re-open if you're already using dev-1.4.0.
