### ISSUE TITLE
Pidgin freezes and account disconnects

### ISSUE THREAD

**Issue by ivankuraj** [majn/telegram-purple#448]
This is something that started happening relatively recently: pidgin effectively freezes (is unresponsive), for about a minute or two, and after that Telegram reports that the account is disconnected. (After that, the account usually reconnects after a while.)
I am not sure what's exactly wrong, but I am pretty sure it is this plugin. Any idea what could be wrong and how to debug this?

**Comment by lmfardin** [comment]
It also happens to me. Everyday, Telegram disconnects for a short while (sometimes more than once), but soon gets back to normal.
    Em sábado, 28 de abril de 2018 16:58:37 BRT, Ivan Kuraj <notifications@github.com> escreveu:  
 
 
This is something that started happening relatively recently: pidgin effectively freezes (is unresponsive) and after some time Telegram reports that the account is disconnected. (After that, the account usually reconnects after a while.)
I am not sure what's exactly wrong, but I am pretty sure it is this plugin. Any idea what could be wrong and how to debug this?

**Comment by BenWiederhake** [comment]
It seems like Telegram is having server issues.  I'm also unable to connect since a few hours ago.  Neither Pidgin nor [Webogram](web.telegram.org) work.  I'm closing this issue, as it's not our fault.  I'll post an update when it works for webogram again.  Any issues after that are actually out fault again.

**Comment by BenWiederhake** [comment]
Looks like everything's back to normal again.  If you're still having problems, please open a new issue.
