### ISSUE TITLE
Seems like the git download compiles an older version of the plugin. Any solutions for this?

### ISSUE THREAD

**Issue by ktlinux** [majn/telegram-purple#450]
I did all it said in the README.md, compiled all the stuff but it was simply not connected once I instelled it with `make`. So for the last attempt I just tried to compile the .deb binary and I saw it compiled the 1.2.4 version. I even updated the git before with the commands in the README.

Any way to get the latest version of this compiled? (screenshot for clarity)
![image](https://user-images.githubusercontent.com/27150141/39690326-5a350944-51e2-11e8-819a-228fea21070e.png)

**Comment by BenWiederhake** [comment]
It looks like you installed the third-party version by user "webudp8", because we only started development of the debian metadata for 1.3.0.

> all it said in the README.md

Which section?  There are several methods of installation.

What do you mean by "it was simply not connected"?  Does the plugin get loaded?

To get detailed plugin-information, in the "Buddy-List" window click the "Help > Addon-Information" (or "Plugin-Information" or something), and you should find an entry like this, probably close to the bottom of the list:

    Telegram
        Author: Matthias Jentsch <mtthsjntsch@gmail.com>
        		Vitaly Valtman
        		Ben Wiederhake
        		Christopher Althaus <althaus.christopher@gmail.com>
        Version: 1.?.?
        		commit: ??????????
        		libtgl: ?.?.?
        Website: https://github.com/majn/telegram-purple
        ID String: prpl-telegram
        Loadable: Yes
        Loaded: Yes

**Comment by ktlinux** [comment]
> Which section?
The one where it said how to build from source. I did build it from source and installed it both by using the `make` command and by compiling the .deb file. I did the whole thing again because I uninstalled the plugin before, this time by checking the version in the specified window each time I installed the plugin. After the `make` command, I got the 1.3.1 version, but after installing the .deb I got the 1.2.4 one (don't know how since I compiled from the same source - screenshot below).
![image](https://user-images.githubusercontent.com/27150141/39711571-c2ddafe6-5228-11e8-90f4-df0eaf6e7a0e.png)
> What do you mean by "it was simply not connected"? Does the plugin get loaded?
At login it didn't ask me for any code and I got the notification saying that there is no connection to the server, or that there was no token. After clicking "retry", it just kept on loading.

**Comment by BenWiederhake** [comment]
Sounds like "it was simply not connected" is just a symptom of the underlying problem "it's an old version".

The mistake here is that `debian-master` really should exist anymore, whoops.  Please use `dev-1.4.0` instead.

I'll try to update the `README.md` accordingly even sooner, as already suggested in #408.  Also, we should probably get 1.4.0 out of the door soon-ish.

If this works for you, please close this issue.  If not, just respond with the "new" error message.

**Comment by BenWiederhake** [comment]
See https://github.com/majn/telegram-purple/tree/dev-1.4.0#building-the-debian-package

In other words: Do a `git checkout dev-1.4.0` and rebuild.

**Comment by ktlinux** [comment]
I got an error while compiling the deb.

`configure: exit 1
dh_auto_configure: ./configure --build=i686-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/i386-linux-gnu --libexecdir=${prefix}/lib/i386-linux-gnu --disable-maintainer-mode --disable-dependency-tracking returned exit code 1
debian/rules:8: recipe for target 'binary' failed
make: *** [binary] Error 2`

I even tried a `git submodule update --recursive` and I got into the same error. I also got this at the submodule update command:

`$ git submodule update --recursive
error: The following untracked working tree files would be overwritten by checkout:
	tl-parser/.gitignore
	tl-parser/LICENSE
	tl-parser/README.md
	tl-parser/portable_endian.h
	tl-parser/tl-parser-tree.h
	tl-parser/tl-parser.c
	tl-parser/tl-parser.h
	tl-parser/tl-tl.h
	tl-parser/tlc.c
Please move or remove them before you switch branches.
Aborting
Unable to checkout '147af9250832a09567ba354b6f45b2ce17b8745a' in submodule path 'tgl'`

**Comment by BenWiederhake** [comment]
Looks like your worktree is dirty.  Either:
- Read up on git, find out what is the problem, understand how to use git (more works, but pays off in the future)
- or: just `rm -rf` and checkout again, for example with `git clone -b dev-1.4.0 https://github.com/majn/telegram-purple.git`  (less work, but means that you don't understand what you're doing)

**Comment by BenWiederhake** [comment]
As this seems to boil down to a git usage error, I close this issue.  Feel free to reopen if I misunderstood.
