### ISSUE TITLE
Logo Proposal: Telegram-purple

### ISSUE THREAD

**Issue by baranpirincal** [majn/telegram-purple#451]
Hey, I am graphic designer and my aim is make my portfolio better with supporting open source project in field of graphic. I can contribute on your project with making a logo design. I would be very pleased if you interested. I can show my portfolio if you want it. I am waiting your feedback, have a nice day! :)

Best Regards,
Baran Pirincal
Visual Communication Designer

**Comment by BenWiederhake** [comment]
I'm sorry, but the only logos we need are just [the telegram logo](https://github.com/majn/telegram-purple/tree/master/imgs), and we already have that.

On the other hand, @majn (the owner of this project) may have a different opinion than me.
