### ISSUE TITLE
telegram-purple shows message RPC_CALL_FAIL 401: USER_DEACTIVATED

### ISSUE THREAD

**Issue by MstrSinister** [majn/telegram-purple#459]
Like in the title: when i use telegram-purple with pidgin it doesn't connect because apparently my number is deactivated. I've tried the telegram desktop afterwards and it works fine. Of course I want/need to use pidgin so...

**Comment by dragetd** [comment]
Have you tried on yet another device pidgin? Maybe something during login messed up, and it is only 'this installation/device' that the servers do not allow to log on right now.

**Comment by g00dy22** [comment]
In my case the issue has been fixed by removing ~/.purple/telegram-purple directory. Then I've added account to pidgin, received activation message from Telegram and connected successfully.

**Comment by MstrSinister** [comment]
> In my case the issue has been fixed by removing ~/.purple/telegram-purple directory. Then I've added account to pidgin, received activation message from Telegram and connected successfully.

Thank you very much! That did the trick and it all works like a charm now.

**Comment by BenWiederhake** [comment]
Since it's an account management issue, and not a problem with tgp, I'll close this.  Feel free to reopen if I misunderstood.
