### ISSUE TITLE
Handle file receiving.

### ISSUE THREAD

**Issue by Nnubes256** [majn/telegram-purple#46]
This doesn't happen to work, at least in Adium. I'd like this to be supported.

Thanks a lot!

UPDATE: Seems to happen with stickers. The sticker is received as a message that says:
```
[DOCUMENT] sticker.webp 45.2 KB,
```
Could be fixed on the library side by updating mime.types, but waiting for response before closing.

**Comment by Nnubes256** [comment]
UPDATE: Doesn't work with sound files too, so it's a broader issue.

**Comment by majn** [comment]
Yes audio, video and documents transfers dont  work at the moment, but I'm planning to add it in a future version.

**Comment by majn** [comment]
Fixed in 0.7.0
