### ISSUE TITLE
Strange behaviour of autocomplete and notifications

### ISSUE THREAD

**Issue by ftyers** [majn/telegram-purple#460]
When I'm in a group chat and I try and tab complete someone's nick, I get their "viewed nick" instead of their actual nick. This means they don't get notified that I've mentioned their name. 

For example: I'm in a chat with Brynhildr (`@brnh`) and Sigurð (`@siggster`) ... When I type `b-TAB` or `B-TAB` I'd like it to auto complete to `@brnh` instead of `Brynhildr` that way they will get notified.

Apologies if this is the wrong place to report this bug.

**Comment by BenWiederhake** [comment]
That's a valid concern, but I don't see how telgram-purple could behave differently in this case.  AFAIK the tab-completion is done by libpurple or even pidgin itself, so there's no way telegram-purple could convey this information.

So either rename your contacts to brnh, or tell the purple developers that there needs to be a new field, something like "mentionable-name" in addition to displayname and internal ID.

**Comment by ftyers** [comment]
@BenWiederhake any idea where to report that ? I searched GitHub but it seems that libpurple isn't there...

**Comment by ildar** [comment]
This sounds like a new function that may be implemented with a plugin. If
you can you may choose to write it yourself.
The issue tracker is at pidgin.im if you want; but it'll hardly help in
your case

**Comment by BenWiederhake** [comment]
Since this is beyond what we can possibly do, I'll close this.  Feel free to reopen if I misunderstood.

Also, I'm really sorry.  Obviously I and everyone else has the same problem, I just don't think we can *do* anything about it.  Again, if I'm wrong *hell yes please reopen*.
