### ISSUE TITLE
Audio files in Bitlbee

### ISSUE THREAD

**Issue by rodarima** [majn/telegram-purple#461]
Hi, I just wanted to comment how I got Bitlbee working with Telegram and the download folder were the files are stored. I'm running Arch Linux, and I used the last version from git 60bb2ba in the dev-1.4.0 branch, I mainly followed the [wiki](https://wiki.archlinux.org/index.php/bitlbee#Telegram) steps.

First I installed bitlbee with purple enabled from the [bitlbee-libpurple](https://aur.archlinux.org/packages/bitlbee-libpurple/) aur package . Then the dev package of [telegram-purple](https://aur.archlinux.org/packages/telegram-purple-git/)

Then started the Bitlbee daemon, which runs with the `bitlbee` user:
```# systemctl start bitlbee.service```

I use the `irssi` IRC client, which I connect to localhost with `/connect localhost`, then I created my account with the commands:

```
account add telegram <phone_number_with_region_prefix>
account telegram on
```

Then I received some audio files, which are [stored by default](https://www.bitlbee.org/user-guide.html#id-1.2.4) in `/var/lib/bitlbee/purple/<my_irc_username>/telegram-purple/<my_phone>/downloads`

**Comment by BenWiederhake** [comment]
Awesome!  I incorporated it here: https://github.com/majn/telegram-purple/tree/dev-1.4.0#faq

Please re-open if you think it can be improved.
