### ISSUE TITLE
libtelegram.dll not loadable after update to 2.13.0

### ISSUE THREAD

**Issue by advtal52** [majn/telegram-purple#462]
after the pidgin update to 2.13.0, the plugins stopped working

Pidgin 2.13.0 (libpurple 2.13.0)
f07927902113041d6fa291293d9205ea4f05e9e6		

(22:19:30) plugins: probing D:\PidginPortable-new\App\Pidgin\plugins\libtelegram.dll
(22:19:31) plugins: D:\PidginPortable-new\App\Pidgin\plugins\libtelegram.dll is not loadable: `D:\PidginPortable-new\App\Pidgin\plugins\libtelegram.dll': No se puede encontrar el m¾dulo especificado.

**Comment by BenWiederhake** [comment]
Sounds like a dependency problem because of the libpurple versions.  I was hoping that it's compatible, that's why the windows variant still builds against pidgin 2.12, not pidgin 2.13.

Just to make sure: Please try the [installer that builds against 2.12.0](https://github.com/majn/telegram-purple/pull/446#issuecomment-381402503).  If that doesn't work, I'll just have to publish two installers (one for pidgin 2.12 and one for pidgin 2.13).

**Comment by EionRobb** [comment]
It won't be from the libpurple version, since libpurple follows semantic versioning principals. 

Saying the module can't be found sounds more like a missing dependency dll like gcrypt or something?

**Comment by BenWiederhake** [comment]
Hey Eion!  Thanks for the feedback, and nice to see you still around! :)

Hmm, wouldn't the missing dependency (like gcrypt) be listed?  Something like "Symbol XYZ ot found" or somesuch?

@advtal52: Which installer did you use?

**Comment by EionRobb** [comment]
Sadly, on windows we don't get that level of detail of error feedback. 
If it were to do with libpurple it would say " the specified procedure was missing" (or words to that effect) instead of the whole module being missing, which implies a dll

**Comment by advtal52** [comment]
i do not have a installer (http://eion.robbmob.com/telegram/ IS DOWN)
I tried to update an existing version, it did not work
I copied the DLLs that were listed as dependencies in a fresh install of 2.13, it did not work
I copied the DLLs that were listed as dependencies in a in a fresh install of 2.12, it worked like a charm

@EionRobb  thank for compile the windows version

**Comment by BenWiederhake** [comment]
So now it works?  Great!  (Please reopen if I misunderstood that.)

**Comment by advtal52** [comment]
is not working
just list the tests performed

does not work in PIDGIN 2.13.0 (recentry released )
works fine in PIDGIN 2.12.0 (previus release)

**Comment by advtal52** [comment]
i tried install the buil telegram-purple-1.3.1+g23f4eaeebc, it works ok
thanks
