### ISSUE TITLE
Cannot send Hebrew letters / characters / glyphs

### ISSUE THREAD

**Issue by shlomif** [majn/telegram-purple#464]
I cannot send Hebrew letters / characters / glyphs using purple-telegram-1.3.0-2.mga7 on mageia v7. I can receive them fine.

For example typing :

```
נסיון
```

and pressing enter causes these letters to be eaten by pidgin.

**Comment by BenWiederhake** [comment]
Already known as #339, and fixed on the dev branch.  Until we finally get around to build the Adium bundle and can finally release 1.4.0, please use the dev version.

**Comment by shlomif** [comment]
very well, but see https://slashdot.org/story/06/05/20/1651253/the-cvs-cop-out - as a packager - i hesitate to package prereleases. thanks! You can also try using travis-ci or similar for streamlining the macos build.

**Comment by BenWiederhake** [comment]
I completely understand, and I really would prefer to finally have a release.  But majn's dev env is down, and I never actually used a Mac, so building an Adium bundle is a bit of a bottleneck.
