### ISSUE TITLE
No incoming messages

### ISSUE THREAD

**Issue by x-t** [majn/telegram-purple#470]
Trying to use telegram-purple from master (f686f8a6e7669bce2e50645638497abfc3d6a8ef) on bitlbee-libpurple 3.5.1-1build1, I get no incoming messages from a direct chat. I know it works for another person, as I hosted the server publicly, but for me, in the same network/device that I host bitlbee on, I can send messages and they'll go through, but I do receive any messages.

**Comment by BenWiederhake** [comment]
That sounds bad.  I'd love to find out what exactly is happening here.

However, it doesn't seem to be the entire setup that you're in multiple groups.  I'm in multiple groups, too, and it works fine.  Apparently something else made it break.

**Comment by x-t** [comment]
It doesn't give much indication at where things fail, it just doesn't receive messages and it started working after I left groups. Could it be bitlbee's fault? It's the default build from Ubuntu's repo, I know that at least on Debian the repo builds of bitlbee-libpurple were non-functioning. I'll try to build bitlbee manually tomorrow or something and report if I find anything.

**Comment by x-t** [comment]
After reinstalling bitlbee, it seems to work fine now.
