### ISSUE TITLE
Telegram-purple Pidgin Error,Server.tglpub file   

### ISSUE THREAD

**Issue by DJxZeonExpert** [majn/telegram-purple#474]
Hi, there!
Im, have trouble, after building Telegram-purple 1.40dev in Tails 3.10.
I get message in Pidgin, after make account, i try it authorized & i take this message:
Make sure telegram-purple is installed properly, incluiding the .tglpub file.
If you're running SELinux (e.g. when using Tails),
try 'make local_install', or simply copy
 /etc/telegram-purple/server.tglpub to /home/amnesia/.purple/server.tglpub
I try it copy,this files & i give root &  amnesia permissions , i try make local_install, this is not working.
Please help me, solve this problem.

**Comment by DJxZeonExpert** [comment]
Ok i give U, number of commit.
I try it on this last git pull/clone.

**Comment by BenWiederhake** [comment]
So you have two options:
- Use dev-1.4.0, like I suggested
- Don't use 1.3.1 in an environment that actively tries to lock everything down in an overly paranoid fashion and denies access to config files, i.e. SELinux.

You should already know this.  See the error message you copied originally.  It tells you this.
