### ISSUE TITLE
[RFC] Status of the macOS build

### ISSUE THREAD

**Issue by shlomif** [majn/telegram-purple#479]
Hi all,

I've been working on git fork with travis-CI / macOS build support here - https://travis-ci.org/shlomif/telegram-purple/ . On macOS, the make -j2 and make check pass fine, but trying to build adium from source fails with a preprocessor error. Furthermore https://hg.adium.im/adium has an invalid ssl cert and then gives an internal server error, and the upstream adium seems to have been abandoned.

Can we release a new version which will cater for windows and linux/BSD/etc. users and tell macOS users to use homebrew or whatever?

**Comment by BenWiederhake** [comment]
That doesn't look like it's trivial to fix.  Pull Requests welcome.

**Comment by shlomif** [comment]
Can we please release a new version? Right now non-macOS users suffer and macOS users are not doing any better than before. So it is throwing the baby along with the bathwater. @BenWiederhake , anyone?

**Comment by BenWiederhake** [comment]
Sigh.  You're right.  It's been long overdue.

[Here it comes.](https://github.com/majn/telegram-purple/releases/)

Please report any issues separately.  Have a nice day! :)

**Comment by shlomif** [comment]
On Fri, 01 Mar 2019 16:53:13 -0800
Ben Wiederhake <notifications@github.com> wrote:

> Sigh.  You're right.  It's been long overdue.
> 
> [Here it comes.](https://github.com/majn/telegram-purple/releases/)
> 
> Please report any issues separately.  Have a nice day! :)
> 

Awesome, many thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/open-source/resources/tech-tips/

Happy Birthday! You'll be older than I in no time at this rate!
    — ED Curtis Curtis on Facebook

Please reply to list if it's a mailing list post - http://shlom.in/reply .
