### ISSUE TITLE
pidgin crashes when using purple-telegram and last-seen setting is not "Everybody"

### ISSUE THREAD

**Issue by Sesivany** [majn/telegram-purple#481]
This bug was reported to me in [downstream bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1669473), since it's something that needs to be fixed upstream, I'm opening it here as well:
How reproducible:

Always, follow the steps below

Steps to Reproduce:
1. Change your Telegram account  privacy 'last seen' settings from 'Everybody' to 'My contacts' or 'Nobody' (eg: using mobile app, or web browser)
2. Start pidgin and try to log into your telegram account.
3. See segfault :

$ pidgin &
pidgin: queries.c:470: tglq_query_result: Assertion `0' failed.
[1]+  Aborted                 (core dumped) pidgin

Actual results:

pidgin crashes

**Comment by nomeata** [comment]
Related to https://github.com/majn/telegram-purple/issues/478?

**Comment by nomeata** [comment]
I have the same assertion, but changing last-seen to Everybody does not help.

**Comment by josx** [comment]
It is working pretty well with  telegram-purple 1.4.1 and tgl submodule updated.

**Comment by Sesivany** [comment]
The downstream bug has been closed, the reporter can't reproduce it with 1.4.1, so I'm closing it.
