### ISSUE TITLE
Full path is used instead of just filename when sending files

### ISSUE THREAD

**Issue by foxmajik** [majn/telegram-purple#486]
When sending a file, the file is named after the full path to the file as on the local system.

For example, if you send this file:

c:\users\joe\pictures\foo.png

Then the file would be named cUsersJoePicturesFoo.png

This is unfortunate because it exposes details of the local filesystem to remote users.

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple), which might already have this enhancement. For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
