### ISSUE TITLE
nick format

### ISSUE THREAD

**Issue by jacekjaros** [majn/telegram-purple#497]
Hi,

I use few accounts via bitlbee/libpurple. I want to set custom nick format (%full_name[TG]).

i was try to do it running following command:
```
 account telegram set nick_format %full_name[TG]
```
This is working to hangouts and facebook. Unfortunately this is not working to telegram-purple.

Is there any way to set custom nick format in telegram-purple?

**Comment by BenWiederhake** [comment]
"command"?  I'm surprised you can execute commands anywhere in telegram-purple?

I'm afraid telegram-purple doesn't have direct support for that.  However, I see two way around this:
- Close pidgin completely, do a search-replace on `~/.purple/accounts.xml`, start pidgin again
- Change the template in telegram-purple's source code, wherever it is, and recompile.  You may need to delete `accounts.xml` and/or the `telegram-purple/phone_number` folder.

**Comment by EionRobb** [comment]
@BenWiederhake you can tell bitlbee how to display a user by sending commands to the &bitlbee command channel, nothing to do with the prpl - kinda like an inline way of setting UI preferences

@jacekjaros telegram-purple doesn't set buddy aliases, so the %full_name nick_format (which maps to the libpurple buddy alias) won't do anything.  Instead, the alias is mapped to the id of the buddy, so you'll want to `account telegram set nick_format %nick[TG]`

**Comment by jacekjaros** [comment]
@EionRobb - thanks for clarification. ```account telegram set nick_format %nick[TG]``` is exactly what i need. Thanks a lot.
