### ISSUE TITLE
Crash when Adding contact to new group in Adium

### ISSUE THREAD

**Issue by psydwannabe** [majn/telegram-purple#50]
When attempting to add a Telegram contact to another group, Adium crashes.  I have verified this problem on two Macs now-- both running OS X 10.9.5 and the latest version of Adium and the Telegram plugin.
![telegram-crash-group-add](https://cloud.githubusercontent.com/assets/6654256/6160878/a5bcfc04-b21d-11e4-86f9-280f680176cb.gif)

Here is a pastebin of the problem details:
http://pastebin.com/aVsi8ByC

**Comment by majn** [comment]
Fixed.
