### ISSUE TITLE
ancient glib fix

### ISSUE THREAD

**Issue by halftux** [majn/telegram-purple#501]
Hi,

to have support for old glib you could fix in tgp-utils.c the following. I Hope that the fix is doing the same like g_list_free_full which exists since 2.28.0. At least I could start the plugin with this fix.

```
diff -Naur telegram-purple-1.4.1-org/tgp-utils.c telegram-purple-1.4.1-maemo/tgp-utils.c
--- telegram-purple-1.4.1-org/tgp-utils.c	2019-03-02 01:36:26.000000000 +0100
+++ telegram-purple-1.4.1-maemo/tgp-utils.c	2019-06-05 13:38:29.000000000 +0200
@@ -92,11 +92,20 @@
   g_queue_free (queue);
 }
 
+#if GLIB_CHECK_VERSION(2,28,0)
 void tgp_g_list_free_full (GList *list, GDestroyNotify free_func) {
   if (list) {
     g_list_free_full (list, free_func);
   }
 }
+#else
+void tgp_g_list_free_full (GList *list, GDestroyNotify free_func) {
+  if (list) {
+    g_list_foreach (list, (GFunc)free_func, NULL);
+    g_list_free (list);
+  }
+}
+#endif
 
 const char *tgp_mime_to_filetype (const char *mime) {
   int len = (int) strlen (mime);
```

**Comment by EionRobb** [comment]
What OS/distro are you using that's on pre-2.28?

**Comment by BenWiederhake** [comment]
I have the same question as Eion.

Since you wrote "ancient" in the title, I'm going to assume you indeed have an acient system and a reason not to update.  Okay, fine with me.

If you open a PR, you can get credit for your contribution.  Otherwise, I could merge it by hand, if you want that.

**Comment by halftux** [comment]
It is a debian derivate for Nokia "internet tablets" specific [Maemo fremantle](http://maemo.org/packages/view/purple-protocol-telegram/) for the N900. Closed sources makes it impossible to update glib. There is a new ongoing work/project to "update and to free it from closed sources" and to let it run on more hardware. By porting hildon and other key functions to a new linux distro. This new project is called [Maemo Leste](https://maemo-leste.github.io/) based on Devuan very interesting.

And I am fine if you could merge it by hand, I can't actively work on the code, in prinziple I only packed it.
Other things are waiting.
So many thanks for the last release and ongoing development.

**Comment by BenWiederhake** [comment]
Merged into dev.  We'll close this issue when it reaches master.
