### ISSUE TITLE
Latest git revision: Voice messages not transferred

### ISSUE THREAD

**Issue by Photon89** [majn/telegram-purple#504]
With the latest git revision (dev branch) I get a message that a voice message (an .oga file) has been received, as usual; I can also open the folder containing transferred files, but the file is not in this folder and cannot be opened by clicking the link in the message. The release version (1.4.1) works fine though!

**Comment by BenWiederhake** [comment]
Should be fixed by [v1.4.2](https://github.com/majn/telegram-purple/releases/tag/v1.4.2).
