### ISSUE TITLE
All Contacts are always set mobile and away in Adium

### ISSUE THREAD

**Issue by psydwannabe** [majn/telegram-purple#51]
Even when actively chatting with other users who appear as active on the Telegram apps, in Adium, all contacts always show up as "Away" and "Mobile" in Adium with the Telegram plugin.

**Comment by blinry** [comment]
In Pidgin, all contacts are set to "Online" and "Mobile" (as of 8fec18e). It would probably make sense to define a timeout for "last seen", after which users are set to "Offline".

**Comment by majn** [comment]
Fixed. The online-state works properly again. I've also added a setting that will display users offline after a configurable amount of days.
