### ISSUE TITLE
Plugin uses invalid hard-coded server IP addresses

### ISSUE THREAD

**Issue by foxmajik** [majn/telegram-purple#510]
It appears that the IP addresses for Telegram servers have changed and as they are hard coded in the plugin it's no longer possible to connect.

See debug log here:

(14:38:57) account: Account +1[redacted phone number] not enabled, not connecting.
(14:38:57) autorecon: done calling purple_account_connect
(14:38:57) account: Connecting to account [redacted phone number]
(14:38:57) connection: Connecting. gc = 05AE6800
(14:38:57) prpl-telegram: tgprpl_login(): Purple is telling the prpl to connect the account
(14:38:57) prpl-telegram: base configuration path: 'C:\Users\[username]\AppData\Roaming\.purple\telegram-purple\+1[redacted phone number]'
(14:38:57) prpl-telegram: initializing empty auth file
(14:38:57) signals: Signal data for chat-conversation-typing not found!
(14:38:57) dnsquery: Performing DNS lookup for 149.154.175.50
(14:38:57) dnsquery: Performing DNS lookup for 149.154.167.51
(14:38:57) dnsquery: Performing DNS lookup for 149.154.175.100
(14:38:57) dnsquery: Performing DNS lookup for 149.154.167.91
(14:38:57) dnsquery: Performing DNS lookup for 149.154.171.5
(14:38:57) dnsquery: IP resolved for 149.154.175.50
(14:38:57) proxy: Attempting connection to 149.154.175.50
(14:38:57) proxy: Connecting to 149.154.175.50:443 with no proxy
(14:38:57) proxy: Connection in progress
(14:38:57) dnsquery: IP resolved for 149.154.167.51
(14:38:57) proxy: Attempting connection to 149.154.167.51
(14:38:57) proxy: Connecting to 149.154.167.51:443 with no proxy
(14:38:57) proxy: Connection in progress
(14:38:57) dnsquery: IP resolved for 149.154.175.100
(14:38:57) proxy: Attempting connection to 149.154.175.100
(14:38:57) proxy: Connecting to 149.154.175.100:443 with no proxy
(14:38:57) proxy: Connection in progress
(14:38:57) dnsquery: IP resolved for 149.154.167.91
(14:38:57) proxy: Attempting connection to 149.154.167.91
(14:38:57) proxy: Connecting to 149.154.167.91:443 with no proxy
(14:38:57) proxy: Connection in progress
(14:38:57) dnsquery: IP resolved for 149.154.171.5
(14:38:57) proxy: Attempting connection to 149.154.171.5
(14:38:57) proxy: Connecting to 149.154.171.5:443 with no proxy
(14:38:57) proxy: Connection in progress
(14:38:57) proxy: Connecting to 149.154.175.50:443.
(14:38:57) proxy: Connected to 149.154.175.50:443.
(14:38:57) proxy: Connecting to 149.154.175.100:443.
(14:38:57) proxy: Connected to 149.154.175.100:443.
(14:38:57) proxy: Connecting to 149.154.167.51:443.
(14:38:57) proxy: Connected to 149.154.167.51:443.
(14:38:57) proxy: Connecting to 149.154.167.91:443.
(14:38:57) proxy: Connected to 149.154.167.91:443.
(14:38:57) proxy: Connecting to 149.154.171.5:443.
(14:38:57) proxy: Connected to 149.154.171.5:443.
(14:39:04) util: Writing file accounts.xml to directory C:\Users\[username]\AppData\Roaming\.purple
(14:39:04) util: Writing file C:\Users\[username]\AppData\Roaming\.purple\accounts.xml
(14:39:17) prpl-telegram: ping alarm
(14:39:17) prpl-telegram: ping alarm
(14:39:17) prpl-telegram: ping alarm
(14:39:24) prpl-telegram: ping alarm
(14:39:24) dnsquery: Performing DNS lookup for 149.154.175.50
(14:39:24) dnsquery: IP resolved for 149.154.175.50
(14:39:24) proxy: Attempting connection to 149.154.175.50
(14:39:24) proxy: Connecting to 149.154.175.50:443 with no proxy
(14:39:24) proxy: Connection in progress
(14:39:25) proxy: Connecting to 149.154.175.50:443.
(14:39:25) proxy: Connected to 149.154.175.50:443.
(14:39:31) prpl-telegram: ping alarm
(14:39:31) dnsquery: Performing DNS lookup for 149.154.175.100
(14:39:31) dnsquery: IP resolved for 149.154.175.100
(14:39:31) proxy: Attempting connection to 149.154.175.100
(14:39:31) proxy: Connecting to 149.154.175.100:443 with no proxy
(14:39:31) proxy: Connection in progress
(14:39:31) dnsquery: Performing DNS lookup for 149.154.167.51
(14:39:31) dnsquery: IP resolved for 149.154.167.51
(14:39:31) proxy: Attempting connection to 149.154.167.51
(14:39:31) proxy: Connecting to 149.154.167.51:443 with no proxy
(14:39:31) proxy: Connection in progress
(14:39:31) proxy: Connecting to 149.154.175.100:443.
(14:39:31) proxy: Connected to 149.154.175.100:443.
(14:39:31) dnsquery: Performing DNS lookup for 149.154.167.91
(14:39:31) dnsquery: IP resolved for 149.154.167.91
(14:39:31) proxy: Attempting connection to 149.154.167.91
(14:39:31) proxy: Connecting to 149.154.167.91:443 with no proxy
(14:39:31) proxy: Connection in progress
(14:39:32) proxy: Connecting to 149.154.167.91:443.
(14:39:32) proxy: Connected to 149.154.167.91:443.
(14:39:32) proxy: Connecting to 149.154.167.51:443.
(14:39:32) proxy: Connected to 149.154.167.51:443.
(14:39:32) dnsquery: Performing DNS lookup for 149.154.171.5
(14:39:32) dnsquery: IP resolved for 149.154.171.5
(14:39:32) proxy: Attempting connection to 149.154.171.5
(14:39:32) proxy: Connecting to 149.154.171.5:443 with no proxy
(14:39:32) proxy: Connection in progress
(14:39:32) proxy: Connecting to 149.154.171.5:443.
(14:39:32) proxy: Connected to 149.154.171.5:443.
(14:39:40) prpl-telegram: ping alarm
(14:39:47) prpl-telegram: ping alarm
(14:39:47) prpl-telegram: ping alarm
(14:39:47) prpl-telegram: ping alarm
(14:39:48) prpl-telegram: ping alarm
(14:39:55) prpl-telegram: ping alarm
(14:40:02) prpl-telegram: ping alarm
(14:40:02) prpl-telegram: ping alarm
(14:40:02) prpl-telegram: ping alarm
(14:40:03) prpl-telegram: ping alarm
(14:40:10) prpl-telegram: ping alarm
(14:40:17) prpl-telegram: ping alarm
(14:40:17) prpl-telegram: ping alarm
(14:40:17) prpl-telegram: ping alarm
(14:40:18) prpl-telegram: ping alarm
(14:40:25) prpl-telegram: ping alarm
(14:40:30) prefs: /pidgin/debug/width changed, scheduling save.
(14:40:30) prefs: /pidgin/debug/height changed, scheduling save.
(14:40:32) prpl-telegram: ping alarm
(14:40:32) prpl-telegram: ping alarm
(14:40:32) prpl-telegram: ping alarm
(14:40:33) prpl-telegram: ping alarm
(14:40:36) util: Writing file prefs.xml to directory C:\Users\[username]\AppData\Roaming\.purple
(14:40:36) util: Writing file C:\Users\[username]\AppData\Roaming\.purple\prefs.xml
(14:40:40) prpl-telegram: ping alarm
(14:40:47) prpl-telegram: ping alarm
(14:40:47) prpl-telegram: ping alarm
(14:40:47) prpl-telegram: ping alarm
(14:40:48) prpl-telegram: ping alarm
(14:40:55) prpl-telegram: ping alarm
(14:41:02) prpl-telegram: ping alarm
(14:41:02) prpl-telegram: fail connection: reason: ping timeout
(14:41:02) prpl-telegram: Lost connection to server ... 149.154.175.100:80
(14:41:02) connection: Connection error on 05AE6800 (reason: 0 description: Lost connection to the server...)
(14:41:02) prpl-telegram: ping alarm
(14:41:02) prpl-telegram: ping alarm
(14:41:02) account: Disconnecting account +1[redacted phone number] (025C55D8)
(14:41:02) connection: Disconnecting connection 05AE6800
(14:41:02) prpl-telegram: tgprpl_close()
(14:41:02) connection: Destroying connection 05AE6800
(14:41:07) util: Writing file accounts.xml to directory C:\Users\[username]\AppData\Roaming\.purple
(14:41:07) util: Writing file C:\Users\[username]\AppData\Roaming\.purple\accounts.xml

**Comment by BenWiederhake** [comment]
We're using the same servers as [the reference implementation](https://github.com/tdlib/td/blob/master/td/telegram/net/ConnectionCreator.cpp#L1336), and this is the first such report.  Are you sure it's not just you who got blocked?

The webm-servers are named, for whatever reason, and run on different IPs than the rest.  It may be worth a shot to try replacing the IPs with their URLS, names, or IPs.

I will close this unless someone else has problems, too.

**Comment by BenWiederhake** [comment]
Feel free to reopen if you have any new information, of if any other person has the same problem.

**Comment by foxmajik** [comment]
Sorry about that, you were right, it was Telegram servers blocking me for some reason.

I can't figure out why though. It only happens on Windows. If I open my BSD or Linux VM and sign in it works OK.

**Comment by BenWiederhake** [comment]
Hmm, did you have any very important secret chats?  If not, you could delete the account in pidgin, re-create it, and it might work.  (Assuming only that single client got blocked, or bugged, which I find more likely.)

**Comment by sdfg2** [comment]
I get exactly the same thing, despite the official telegram app working on the same machine.  I'm at a complete loss how to proceed.

**Comment by BenWiederhake** [comment]
Can you check which outbound connections the Telegram app holds?  Are those IPs similar to what is hardcoded in tgl?  What error exactly do you see when connecting: Connection refused, read timeout, no route to host, connection reset by peer, protocol error?

**Comment by sdfg2** [comment]
The output of pidgin -d is exactly as @foxmajik posted.

`tcp        0      0 10.1.2.4:60296          149.154.167.91:443      ESTABLISHED 7023/telegram-deskt`

So it's using the same IP.  I even tried closing the official client to make sure there wasn't any socket tomfoolery going on (not that there really could be, but you never know).

**Comment by Tuxino88** [comment]
same problem 

> prpl-telegram: ping alarm

how to solve?

**Comment by foxmajik** [comment]
> same problem
> 
> > prpl-telegram: ping alarm
> 
> how to solve?

I don't think this project is being worked on anymore, or at least not very much.

I believe it has been forked to [tdlib-purple](https://github.com/ars3niy/tdlib-purple/).

**Comment by BenWiederhake** [comment]
> I don't think this project is being worked on anymore, or at least not very much.

Correct.

> I believe it has been forked to tdlib-purple.

Kinda. tdlib-purple is mostly independent, and uses a very different library.

Anyway, all of this is necro-posting on an old and dead issue. If you still run into trouble, please open a new one.
