### ISSUE TITLE
Setting number of days of history to pull to a high number results in 429 error (rate limit) with no error to UI

### ISSUE THREAD

**Issue by foxmajik** [majn/telegram-purple#516]
If you set the number of days of history to retrieve to a high number the client fetches some messages and then fails silently due to a rate limit error (error 429) from the Telegram server.

However, the error is not handled, so all the user knows is that their messages aren't appearing in their chat histories.

This exposes an unhandled error: When the Telegram server returns a rate limit error the user needs to be informed and there should be an explanation of what the error means (too many requests were made in a short time to the server).

Also, generally, there needs to be rate handling in the plugin to prevent the user from being rate limited.

The plugin should calculate the total number of requests going to the server at a given interval of time and automatically rate limit at the client side to prevent the user's Telegram account being rate limited, and it should inform the user that transactions are being paused to prevent that.

**Comment by foxmajik** [comment]
So it's been a year now and this bug is still marked "help wanted."

Might I suggest a quick fix while you're waiting?

You could find out how many messages the Telegram protocol allows you to poll and... stop before that limit?

Maybe inform the user that the limit is there and that there's a maximum number of days they can set in the history box?

**Comment by BenWiederhake** [comment]
I understand your frustration, sorry that the code doesn't magically appear :/

If you have a working PR, I'll gladly accept it.

**Comment by foxmajik** [comment]
I'm sorry not everybody writes software. I'll stop contributing to your project so you don't have to deal with giving me responses to my update requests.
