### ISSUE TITLE
Crash when receiving location data

### ISSUE THREAD

**Issue by bwachter** [majn/telegram-purple#522]
As soon as it tries reading location data from telegram it segfaults:

#0  0x00007ffff653746d in send () from /lib64/libpthread.so.0
#1  0x00007fffdedf3a66 in try_write (c=0x555555914f40) at tgp-net.c:372
#2  0x00007fffdedf335a in conn_try_write (arg=0x555555914f40, source=17, cond=(PURPLE_INPUT_READ | PURPLE_INPUT_WRITE)) at tgp-net.c:237
#3  0x0000555555588b95 in ?? ()
#4  0x00007ffff75d1e87 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#5  0x00007ffff75d2230 in ?? () from /usr/lib64/libglib-2.0.so.0
#6  0x00007ffff75d2542 in g_main_loop_run () from /usr/lib64/libglib-2.0.so.0
#7  0x000055555556e550 in main ()

I didn't see anything obviously broken, but I guess the buffer length passed into send might be off.

**Comment by gregcollin** [comment]
By the way if a user doesn't get many location messages then they can temporarily workaround by deleting location message on another client.

**Comment by BenWiederhake** [comment]
See #517
