### ISSUE TITLE
Unable to use old url pattern to download new release.

### ISSUE THREAD

**Issue by Grandmother** [majn/telegram-purple#524]
Hello.

We in ArchLinux use this pattern "https://github.com/majn/${pkgname}/releases/download/v${pkgver}/telegram-purple_${pkgver}.orig.tar.gz" to download plugin releases, but it doesn't work for the last one.

Is it for ever or it's just mistake in this release?

**Comment by BenWiederhake** [comment]
Gah!  I began "editing" the release, due to some other thing, and didn't finish because of yet another thing.  I didn't know that GitHub would *unpublish* the release immediately, even before I click "Save".

Sorry for the hassle, and it should be back to normal again.
