### ISSUE TITLE
Plugin not working when compiled from source on CentOS 6.4

### ISSUE THREAD

**Issue by nuTTeLLo** [majn/telegram-purple#53]
Compile of plugin goes through smoothly but does not load at all.
Looking at the plugin information reveals this:

(16:52:38) plugins: probing ~/.purple/plugins/telegram-purple.so
(16:52:38) plugins: ~/.purple/plugins/telegram-purple.so is not loadable: undefined symbol: g_list_free_full

**Comment by majn** [comment]
Removed calls to unsupported methods, tested it on Centos 6.6 and it works.
