### ISSUE TITLE
Chat Poll

### ISSUE THREAD

**Issue by Junker** [majn/telegram-purple#536]
When somebody in chat add a Poll, there no any message appear. I think should show system message like "User Nick add Poll 'What color do you prefer?'" etc

**Comment by BenWiederhake** [comment]
Good idea! But with libtgl this probably won't work. Wanna help porting tgp to TDLIB? I'm pretty sure something like this would be dead simple with TDLIB. #480

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
Of course, Pull Requests are still very much welcome!
