### ISSUE TITLE
Pidgin Portable - WIndows 10

### ISSUE THREAD

**Issue by drkui** [majn/telegram-purple#541]
When I run the installer on Windows 10, everything looks like it works fine and I can see Telegram under account setup.

However, I'm primarily using Pidgin Portable on Windows 10. Transferring just libtelegram.dll to my portable plugin's folder (PidginPortable\App\Pidgin\plugins) doesn't work as I'd hope as I'm not able to see Telegram as an option in the account setup.

Can someone please list the files needed and which directories they should go in?

**Comment by BenWiederhake** [comment]
I guess that you forgot auxiliary libraries like `libgpg-error-0.dll`.

Technically, you could work out all the files from the [installation script template](https://github.com/majn/telegram-purple/blob/master/telegram-purple.nsi.awk-in#L74).

Effectively, all the files that you absolutely need are descriped by this NSIS-pseudoscript:
```
SetOutPath "$PidginDir\pixmaps\pidgin"
File "/oname=protocols\16\telegram.png" "imgs\telegram16.png"
File "/oname=protocols\22\telegram.png" "imgs\telegram22.png"
File "/oname=protocols\48\telegram.png" "imgs\telegram48.png"
SetOutPath "$PidginDir\plugins"
File "bin\${PRPL_NAME}"
SetOutPath "$PidginDir\locale"
File /nonfatal "/oname=bg\LC_MESSAGES\telegram-purple.mo" "po\bg.mo"
File /nonfatal "/oname=cs_CZ\LC_MESSAGES\telegram-purple.mo" "po\cs_CZ.mo"
File /nonfatal "/oname=de\LC_MESSAGES\telegram-purple.mo" "po\de.mo"
File /nonfatal "/oname=es\LC_MESSAGES\telegram-purple.mo" "po\es.mo"
File /nonfatal "/oname=es_AR\LC_MESSAGES\telegram-purple.mo" "po\es_AR.mo"
File /nonfatal "/oname=fr\LC_MESSAGES\telegram-purple.mo" "po\fr.mo"
File /nonfatal "/oname=it\LC_MESSAGES\telegram-purple.mo" "po\it.mo"
File /nonfatal "/oname=nl\LC_MESSAGES\telegram-purple.mo" "po\nl.mo"
File /nonfatal "/oname=nn\LC_MESSAGES\telegram-purple.mo" "po\nn.mo"
File /nonfatal "/oname=pl\LC_MESSAGES\telegram-purple.mo" "po\pl.mo"
File /nonfatal "/oname=pt_BR\LC_MESSAGES\telegram-purple.mo" "po\pt_BR.mo"
File /nonfatal "/oname=ru\LC_MESSAGES\telegram-purple.mo" "po\ru.mo"
File /nonfatal "/oname=sq\LC_MESSAGES\telegram-purple.mo" "po\sq.mo"
File /nonfatal "/oname=uk\LC_MESSAGES\telegram-purple.mo" "po\uk.mo"
SetOutPath "$PidginDir"
File "contrib\libgpg-error-0.dll"
File "contrib\libgcrypt-20.dll"
File "contrib\libwebp-7.dll"
File "contrib\libgcc_s_sjlj-1.dll"
```

All these files, in the correct folder structure, can already be found in the [windows installer](https://github.com/majn/telegram-purple/releases/tag/v1.4.3), so I strongly recommend taking them from *there*, instead of installing it and taking it from the installed version.

(Meanwhile, I'm trying to figure out a way for `mkwindows.sh` to produce a more accessible archive, e.g. a zip.)

**Comment by drkui** [comment]
Thank you for the list. Unfortunately, I still wasn't able to get it to work even after copying over the auxiliary libraries and .png files.

If anything I can continue to use Eion's last Telegram build until something comes along to replace it.

**Comment by BenWiederhake** [comment]
Can you post the log during startup with `Path\To\Your\pidgin.exe -d`? It should say something along the lines of "Trying to load libtelegram.dll … failed due to (some reason here)".

**Comment by drkui** [comment]
I took a look at the log, I saw:

`(11:11:28) plugins: [...]\PidginPortable\App\Pidgin\plugins\libtelegram.dll is not loadable: ABI version mismatch 2.13.x (need 2.12.x)`

Then, I remembered I was on Pidgin 2.12 rather than 2.13 because of some issue I had in the past. I tried a fresh copy of 2.13 Portable, put the files in the right place, and it worked.

**Comment by BenWiederhake** [comment]
Great to hear that it works! :)
