### ISSUE TITLE
Commit Added simple caching for usage with bitlbee breaks remote bitlbee instances

### ISSUE THREAD

**Issue by Thaodan** [majn/telegram-purple#549]
I use bitlbee remote on a server through znc and the commit fcdd8a037a7b5c30a57e2e36c9a7ca05c386677a assumes that the file is local and breaks remote urls.

**Comment by BenWiederhake** [comment]
How would file downloads through libpurple *and* bitlbee *and* znc work?

**Comment by Thaodan** [comment]
They don't go really through znc but there's a patch for bitlbee to support images but this assumes that images are always local using the file uri.

**Comment by BenWiederhake** [comment]
Doesn't tgp already generate `file://` links? How does the commit change that?

And sorry for the stupid questions, I just don't use bitlbee so I don't understand how this all works together with bitlbee. Fun fact: If you send a PR, I'll most likely accept it.

**Comment by Thaodan** [comment]
It does but https://github.com/bitlbee/bitlbee/pull/102 parse <img tags and shows them with an requested uri.
This commit intercepts the <img messages[1] and shows them as file:// which is okay for local bitlbee instances and doesn't break anything in this case. But if the instance is not local its breaks because the file is not accessible from the client. Either revert the commits or take into account that the uri needs to adjusted for remote setups.

[1] https://github.com/majn/telegram-purple/blob/62ae6f82cd6c097e3caf28d22d7426edd2df924b/tgp-msg.c#L440

**Comment by BenWiederhake** [comment]
That commit was made in order to accomodate Bitlbee users, so I'm not sure how to proceed. Maybe you could introduce yet another flag?

I really dislike the explosion of flags, but I don't see a way around it, given that lots of people want lots of mutually-incompatible behavior.

**Comment by BenWiederhake** [comment]
Should be fixed in v1.4.5 with this new feature: https://github.com/majn/telegram-purple/pull/558

Let me know if that is not the case.

**Comment by Thaodan** [comment]
It should be a option that can be set during runtime, it is impractical to 
have set during build time.

**Comment by BenWiederhake** [comment]
I also get complaints that config options are inconvenient, especially from bitlbee users. I myself don't use bitlbee, so it's hard for me to judge these things. You're very welcome to implement the config option, and as you can see I'm happy to accept PRs.
