### ISSUE TITLE
Login error: Daemon mode detected. Do *not* try to use libpurple in daemon mode! Please use inetd or ForkDaemon mode instead.

### ISSUE THREAD

**Issue by stintel** [majn/telegram-purple#551]
After upgrading Pidgin from 2.13.0 to 2.14.1, I'm getting this error when trying to connect to Telegram from Bitlbee:

```
04|20:30:54 <@Stijn> account telegram on
04|20:30:54 <@bitlbee> telegram - Login error: Daemon mode detected. Do *not* try to use libpurple in daemon mode! Please use inetd or ForkDaemon mode instead.
04|20:30:54 <@bitlbee> telegram - Logging in: Signing off..
```

**Comment by BenWiederhake** [comment]
That message isn't part of telegram-purple. Can you check whether loading other purples also fails in your setup?

**Comment by stintel** [comment]
Bitlbee is also using pidgin to connect to jabber, which is working fine.

**Comment by BenWiederhake** [comment]
Weird. Again, that message isn't part of telegram-purple, I don't know what to say.

Can you test with *other*, non-XMPP and non-IRC prpls? (XMPP and IRC might get special treatment from Bitlbee, so I want to avoid those.) [tdlib-purple](https://github.com/ars3niy/tdlib-purple/) would be an obvious candidate.

**Comment by stintel** [comment]
Seems like I was a bit too quick to report an issue here. Seems Bitlbee was also recently updated, and the message comes from Bitlbee. Sorry for the noise.
