### ISSUE TITLE
Cannot add language

### ISSUE THREAD

**Issue by tmtfx** [majn/telegram-purple#552]
I'd like to translate to friulian language, but Transifex doesn't recognize it as language in the "Request language". I already did some translation for friulian in Transifex for other software like colord, PackageKit etc.

**Comment by BenWiederhake** [comment]
I added it. Please click "send join request" or a similar button, then I can give you permissions to translate it :)

(Apparently Transifex' search system is broken, and given "friu" it doesn't find "Friulian". To get around this, I looked up the ISO 639-2 code `fru`, tried that, and [viola](https://upload.wikimedia.org/wikipedia/commons/1/1e/Viola_d%27amore.jpg): It worked!)

**Comment by BenWiederhake** [comment]
Oh, wait, this is telegram-purple, not tdlib-purple. May I interest you to contribute to the [future successor][https://www.transifex.com/tdlib-purple-developers/tdlib-purple/), tdlib-purple, instead?

**Comment by tmtfx** [comment]
both is fine? :)
