### ISSUE TITLE
Ubuntu 1.4.3-3ubuntu2 do not let pidgin start

### ISSUE THREAD

**Issue by elcepi** [majn/telegram-purple#560]
The error showing is "pidgin: telegram-base.c:324: read_secret_chat: Assertion `l > 0 && l < 999' failed."

The only way to use pidging was to remove the package. Removing and then installing it did not work.

**Comment by BenWiederhake** [comment]
Your local files for the secret chat probably have been corrupted somehow. Either that's a bug, or you accepted a secret chat that ended up needing more than 999 bytes for the name.

Workarounds:
- Delete the file named just `secret` in your base path (if you don't know where that is, start pidgin with `-d` and search for the line that says `base configuration path: …`), and restart pidgin. Note that this loses all your existing secret chats on that device.
- Telegram-purple is not really actively maintained anymore. Try using [tdlib-purple](https://github.com/ars3niy/tdlib-purple/), which also supports secret chats, and is not based on the crappy libtgl library. Note that this loses all your existing secret chats on that device, and old logs are difficult to access.
- If you really really absolutely have to use telegram-purple, and you definitely for-sure have to revive that one particular secret chat, you could try looking at that file, and use a hexeditor to fix it. Good luck; that's going to be a Herculian task.

**Comment by elcepi** [comment]
Thanks that worked
