### ISSUE TITLE
Please mark project as read-only

### ISSUE THREAD

**Issue by ConiKost** [majn/telegram-purple#581]
Please mark project as read-only, as it's abandoned.

**Comment by BenWiederhake** [comment]
Well, in theory someone might still make a PR. And given that there still are active users, I don't really want to push that button. And last but not least, I don't have the permissions to do so.

**Comment by ConiKost** [comment]
I am sorry, even if someone make a PR, who is gonna merge when whole project is being described as abandoned? Doesn't make much sense.

**Comment by BenWiederhake** [comment]
Me, for example.
