### ISSUE TITLE
Messages are not sent if they are too long.

### ISSUE THREAD

**Issue by 0nse** [majn/telegram-purple#59]
MTProto restricts restricts messages to a length of X (I can't look it up right now as telegram.org seems to be down).

If you compose a message longer than this, other clients (such as webogram) split the message into multiple messages and transmit each individually. However Telegram-purple seemingly sends the message but it will neither be received by the opposite party nor appear in the chat log.

The user should be notified about this and hindered to send the message or – and that is the preferrable alternative – the message should automatically be split into smaller messages that don't exceed the size limit.

**Comment by majn** [comment]
Done. Long messages are split up in up to 4 messages, beyond that an error will be displayed.
