### ISSUE TITLE
pidgin plugin with no sms verification

### ISSUE THREAD

**Issue by fabastrid** [majn/telegram-purple#60]
I installed the plugin on Mint 17.1 cinnamon x64, set my phone number as username (with the country code), but can't receive sms for verification. Of course, the gear of connection keeps beeing grey. Tried to change the default setting of proxy label, installed all the dependecies suggested, but still no sms.

**Comment by majn** [comment]
Can you please start Pidgin in Terminal with the -d flag and give me the output?

   pidgin -d

**Comment by fabastrid** [comment]
it's huge, I do it?

**Comment by majn** [comment]
Create a gist and link it https://gist.github.com

**Comment by fabastrid** [comment]
I'm sorry, I don't know what you mean

**Comment by fabastrid** [comment]
that could be interesting:

16:35:39) prpl-telegram: adjusting CLOCK_MONOTONIC delta to -0,173988
(16:35:42) util: Writing file prefs.xml to directory /home/fabio/.purple
(16:35:42) util: Writing file /home/fabio/.purple/prefs.xml
(16:35:42) util: Writing file accounts.xml to directory /home/fabio/.purple
(16:35:42) util: Writing file /home/fabio/.purple/accounts.xml
(16:35:42) util: Writing file blist.xml to directory /home/fabio/.purple
(16:35:42) util: Writing file /home/fabio/.purple/blist.xml
dns[6982]: nobody needs me... =(
(16:36:09) jabber: Sending (ssl) (fabio@palanoleg.it/028637F0): <iq type='get' id='purplec5623d7b'><ping xmlns='urn:xmpp:ping'/></iq>
(16:36:09) jabber: Recv (ssl)(72): <iq to="fabio@palanoleg.it/028637F0" id="purplec5623d7b" type="result"/>

**Comment by fabastrid** [comment]
that could be interesting:

16:35:39) prpl-telegram: adjusting CLOCK_MONOTONIC delta to -0,173988
(16:35:42) util: Writing file prefs.xml to directory /home/fabio/.purple
(16:35:42) util: Writing file /home/fabio/.purple/prefs.xml
(16:35:42) util: Writing file accounts.xml to directory /home/fabio/.purple
(16:35:42) util: Writing file /home/fabio/.purple/accounts.xml
(16:35:42) util: Writing file blist.xml to directory /home/fabio/.purple
(16:35:42) util: Writing file /home/fabio/.purple/blist.xml
dns[6982]: nobody needs me... =(
(16:36:09) jabber: Sending (ssl) (------@-------.--/028637F0):
(16:36:09) jabber: Recv (ssl)(72):

**Comment by fabastrid** [comment]
that's it:

~ $ pidgin -d
(16:48:22) prefs: Reading /home/fabio/.purple/prefs.xml
(16:48:22) prefs: Finished reading /home/fabio/.purple/prefs.xml
(16:48:22) prefs: purple_prefs_get_path: Unknown pref /pidgin/browsers/command
(16:48:22) dbus: okkk
(16:48:22) plugins: probing /usr/lib/pidgin/notify.so
(16:48:22) plugins: probing /usr/lib/pidgin/markerline.so
(16:48:22) plugins: probing /usr/lib/pidgin/gestures.so
(16:48:22) plugins: probing /usr/lib/pidgin/iconaway.so
(16:48:22) plugins: probing /usr/lib/pidgin/extplacement.so
(16:48:22) plugins: probing /usr/lib/pidgin/history.so
(16:48:22) plugins: probing /usr/lib/pidgin/ticker.so
(16:48:22) plugins: probing /usr/lib/pidgin/convcolors.so
(16:48:22) plugins: probing /usr/lib/pidgin/cap.so
(16:48:22) plugins: probing /usr/lib/pidgin/spellchk.so
(16:48:22) plugins: probing /usr/lib/pidgin/timestamp_format.so
(16:48:22) plugins: probing /usr/lib/pidgin/musicmessaging.so
(16:48:22) plugins: probing /usr/lib/pidgin/xmppconsole.so
(16:48:22) plugins: probing /usr/lib/pidgin/pidginrc.so
(16:48:22) plugins: probing /usr/lib/pidgin/xmppdisco.so
(16:48:22) plugins: probing /usr/lib/pidgin/vvconfig.so
(16:48:22) plugins: probing /usr/lib/pidgin/themeedit.so
(16:48:22) plugins: probing /usr/lib/pidgin/timestamp.so
(16:48:22) plugins: probing /usr/lib/pidgin/gtkbuddynote.so
(16:48:22) plugins: probing /usr/lib/pidgin/sendbutton.so
(16:48:22) plugins: probing /usr/lib/purple-2/libjabber.so
(16:48:22) plugins: /usr/lib/purple-2/libjabber.so is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INIT_PLUGIN() macro?
(16:48:22) plugins: probing /usr/lib/purple-2/libicq.so
(16:48:22) plugins: probing /usr/lib/purple-2/libsimple.so
(16:48:22) plugins: probing /usr/lib/purple-2/buddynote.so
(16:48:22) plugins: probing /usr/lib/purple-2/dbus-example.so
(16:48:22) plugins: probing /usr/lib/purple-2/libirc.so
(16:48:22) plugins: probing /usr/lib/purple-2/libmsn.so
(16:48:22) plugins: probing /usr/lib/purple-2/joinpart.so
(16:48:22) plugins: probing /usr/lib/purple-2/libmyspace.so
(16:48:22) plugins: probing /usr/lib/purple-2/libsametime.so
(16:48:22) plugins: /usr/lib/purple-2/libsametime.so has a prefs_info, but is a prpl. This is no longer supported.
(16:48:22) plugins: probing /usr/lib/purple-2/telegram-purple.so
(16:48:22) plugins: probing /usr/lib/purple-2/perl.so
(16:48:22) plugins: probing /usr/lib/purple-2/tcl.so
(16:48:22) plugins: /usr/lib/purple-2/tcl.so is not loadable: libtcl8.6.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
(16:48:22) plugins: probing /usr/lib/purple-2/libnovell.so
(16:48:22) plugins: probing /usr/lib/purple-2/ssl-nss.so
(16:48:22) plugins: probing /usr/lib/purple-2/libzephyr.so
(16:48:22) plugins: probing /usr/lib/purple-2/libyahoo.so
(16:48:22) plugins: probing /usr/lib/purple-2/liboscar.so
(16:48:22) plugins: /usr/lib/purple-2/liboscar.so is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INIT_PLUGIN() macro?
(16:48:22) plugins: probing /usr/lib/purple-2/idle.so
(16:48:22) plugins: probing /usr/lib/purple-2/libmxit.so
(16:48:22) prpl-loubserp-mxit: Loading MXit libPurple plugin...
(16:48:22) plugins: probing /usr/lib/purple-2/libymsg.so
(16:48:22) plugins: /usr/lib/purple-2/libymsg.so is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INIT_PLUGIN() macro?
(16:48:22) plugins: probing /usr/lib/purple-2/newline.so
(16:48:22) plugins: probing /usr/lib/purple-2/libbonjour.so
(16:48:22) plugins: probing /usr/lib/purple-2/psychic.so
(16:48:22) plugins: probing /usr/lib/purple-2/libxmpp.so
(16:48:22) plugins: probing /usr/lib/purple-2/libyahoojp.so
(16:48:22) plugins: probing /usr/lib/purple-2/pidgin-libnotify.so
(16:48:22) plugins: probing /usr/lib/purple-2/offlinemsg.so
(16:48:22) plugins: probing /usr/lib/purple-2/statenotify.so
(16:48:22) plugins: probing /usr/lib/purple-2/ssl.so
(16:48:22) plugins: probing /usr/lib/purple-2/autoaccept.so
(16:48:22) plugins: probing /usr/lib/purple-2/log_reader.so
(16:48:22) plugins: probing /usr/lib/purple-2/libaim.so
(16:48:22) plugins: probing /usr/lib/purple-2/libgg.so
(16:48:22) util: Reading file xmpp-caps.xml from directory /home/fabio/.purple
(16:48:22) jabber: creating hash tables for data objects
(16:48:22) prefs: /purple/status/scores/offline changed, scheduling save.
(16:48:22) prefs: /purple/status/scores/available changed, scheduling save.
(16:48:22) prefs: /purple/status/scores/invisible changed, scheduling save.
(16:48:22) prefs: /purple/status/scores/away changed, scheduling save.
(16:48:22) prefs: /purple/status/scores/extended_away changed, scheduling save.
(16:48:22) prefs: /purple/status/scores/idle changed, scheduling save.
(16:48:22) prefs: /purple/status/scores/offline_msg changed, scheduling save.
(16:48:22) util: Reading file accounts.xml from directory /home/fabio/.purple
(16:48:22) prpl-telegram: tgprpl_status_types()
(16:48:22) util: Reading file status.xml from directory /home/fabio/.purple
(16:48:22) certificate: CertificateVerifier x509, singleuse requested but not found.
(16:48:22) certificate: CertificateVerifier singleuse registered
(16:48:22) certificate: CertificatePool x509, ca requested but not found.
(16:48:22) certificate: CertificateScheme x509 requested but not found.
(16:48:22) certificate/x509/ca: Lazy init failed because an X.509 Scheme is not yet registered. Maybe it will be better later.
(16:48:22) certificate/x509/ca: Init failed, probably because a dependency is not yet registered. It has been deferred to later.
(16:48:22) certificate: CertificatePool ca registered
(16:48:22) certificate: CertificatePool x509, tls_peers requested but not found.
(16:48:22) certificate: CertificatePool tls_peers registered
(16:48:22) certificate: CertificateVerifier x509, tls_cached requested but not found.
(16:48:22) certificate: CertificateVerifier tls_cached registered
(16:48:22) prefs: /purple/logging/format changed, scheduling save.
(16:48:22) prefs: /purple/logging/format changed, scheduling save.
(16:48:22) prefs: /purple/proxy/type changed, scheduling save.
(16:48:22) prefs: /purple/proxy/host changed, scheduling save.
(16:48:22) prefs: /purple/proxy/port changed, scheduling save.
(16:48:22) prefs: /purple/proxy/username changed, scheduling save.
(16:48:22) prefs: /purple/proxy/password changed, scheduling save.
(16:48:22) certificate: CertificateScheme x509 requested but not found.
(16:48:22) certificate: CertificateScheme x509 registered
(16:48:22) util: Reading file smileys.xml from directory /home/fabio/.purple
(16:48:22) util: File /home/fabio/.purple/smileys.xml does not exist (this is not necessarily an error)
(16:48:22) stun: using server 
(16:48:22) sound: Initializing sound output drivers.
(16:48:22) prefs: /pidgin/conversations/placement changed, scheduling save.
(16:48:22) prefs: purple_prefs_get_bool: Unknown pref /pidgin/docklet/x11/embedded
(16:48:22) gtkmedia: Registering media element types
(16:48:22) util: Reading file blist.xml from directory /home/fabio/.purple
(16:48:22) plugins: Loading saved plugin /usr/lib/purple-2/ssl-nss.so
(16:48:22) plugins: Loading saved plugin /usr/lib/purple-2/pidgin-libnotify.so
(16:48:22) pidgin-libnotify: Updating status set from pidgin to 'available'
(16:48:22) gtkblist: added visibility manager: 1
(16:48:22) plugins: Loading saved plugin /usr/lib/purple-2/ssl.so
(16:48:22) pounce: Error reading pounces: Apertura del file "/home/fabio/.purple/pounces.xml" non riuscita: File o directory non esistente
(16:48:22) Session Management: ICE initialized.
(16:48:22) Session Management: Connecting with no previous ID
(16:48:22) Session Management: Handling new ICE connection... 
(16:48:22) done.
(16:48:22) Session Management: Connected to manager (cinnamon-session) with client ID 109001e971478bf1d142608890232917000000015160042
(16:48:22) Session Management: Using pidgin as command
(16:48:22) GLib-GObject: value "-1003162719" of type 'gint' is invalid or out of range for property 'weight' of type 'gint'
(16:48:22) account: Connecting to account +393398329139.
(16:48:22) connection: Connecting. gc = 0x7febc60c6db0
(16:48:22) prpl-telegram: tgprpl_login()
(16:48:22) prpl-telegram: base configuration path: '/home/fabio/.telegram-purple/+39339832913'
(16:48:22) prpl-telegram: public key '/etc/telegram-purple/server.pub' loaded successfully
(16:48:22) prpl-telegram: DC1 '' update: 149.154.175.50:443
(16:48:22) prpl-telegram: DC2 '' update: 149.154.167.51:443
(16:48:22) prpl-telegram: DC3 '' update: 174.140.142.6:443
(16:48:22) prpl-telegram: DC4 '' update: 149.154.167.91:443
(16:48:22) prpl-telegram: DC5 '' update: 149.154.171.5:443
(16:48:22) util: requesting to fetch a URL
(16:48:22) dnsquery: Performing DNS lookup for 192.168.178.1
(16:48:22) Session Management: Received first save_yourself
(16:48:22) dnsquery: Performing DNS lookup for 149.154.175.50
(16:48:22) dnsquery: Performing DNS lookup for 149.154.167.51
(16:48:22) dnsquery: Performing DNS lookup for 174.140.142.6
(16:48:22) dnsquery: Performing DNS lookup for 149.154.167.91
(16:48:22) dnsquery: Performing DNS lookup for 149.154.171.5
(16:48:22) Session Management: Received save_complete
(16:48:22) dnsquery: IP resolved for 192.168.178.1
(16:48:22) proxy: Attempting connection to 192.168.178.1
(16:48:22) proxy: Connecting to 192.168.178.1:49000 with no proxy
(16:48:22) proxy: Connection in progress
(16:48:22) dnsquery: IP resolved for 149.154.175.50
(16:48:22) proxy: Attempting connection to 149.154.175.50
(16:48:22) proxy: Connecting to 149.154.175.50:443 with no proxy
(16:48:22) proxy: Connection in progress
(16:48:22) dnsquery: IP resolved for 149.154.167.51
(16:48:22) proxy: Attempting connection to 149.154.167.51
(16:48:22) proxy: Connecting to 149.154.167.51:443 with no proxy
(16:48:22) proxy: Connection in progress
(16:48:22) dnsquery: IP resolved for 174.140.142.6
(16:48:22) proxy: Attempting connection to 174.140.142.6
(16:48:22) proxy: Connecting to 174.140.142.6:443 with no proxy
(16:48:22) proxy: Connection in progress
(16:48:22) dnsquery: IP resolved for 149.154.167.91
(16:48:22) proxy: Attempting connection to 149.154.167.91
(16:48:22) proxy: Connecting to 149.154.167.91:443 with no proxy
(16:48:22) proxy: Connection in progress
(16:48:22) dnsquery: IP resolved for 149.154.171.5
(16:48:22) proxy: Attempting connection to 149.154.171.5
(16:48:22) proxy: Connecting to 149.154.171.5:443 with no proxy
(16:48:22) proxy: Connection in progress
(16:48:22) proxy: Connecting to 192.168.178.1:49000.
(16:48:22) proxy: Connected to 192.168.178.1:49000.
(16:48:22) util: request constructed
(16:48:22) util: Response headers: 'HTTP/1.1 200 OK
Cache-Control: max-age=120
Connection: close
Content-Length: 3166
Content-Type: text/xml
Date: Wed, 11 Mar 2015 15:48:22 GMT
ETag: "3F71BA7F62CBD9A0F"
Expires: Wed, 11 Mar 2015 15:50:22 GMT
Last-Modified: Mon, 02 Mar 2015 18:12:25 GMT
Mime-Version: 1.0

'
(16:48:22) util: parsed 3166
(16:48:22) util: requesting to fetch a URL
(16:48:22) dnsquery: Performing DNS lookup for 192.168.178.1
(16:48:22) dnsquery: Performing DNS lookup for 192.168.178.1
(16:48:22) dnsquery: IP resolved for 192.168.178.1
(16:48:22) proxy: Attempting connection to 192.168.178.1
(16:48:22) proxy: Connecting to 192.168.178.1:49000 with no proxy
(16:48:22) proxy: Connection in progress
(16:48:22) dnsquery: IP resolved for 192.168.178.1
(16:48:22) proxy: Attempting connection to 192.168.178.1
(16:48:22) proxy: Connecting to 192.168.178.1:49000 with no proxy
(16:48:22) proxy: Connection in progress
(16:48:22) proxy: Connecting to 192.168.178.1:49000.
(16:48:22) proxy: Connected to 192.168.178.1:49000.
(16:48:22) util: request constructed
(16:48:22) proxy: Connecting to 192.168.178.1:49000.
(16:48:22) proxy: Connected to 192.168.178.1:49000.
(16:48:22) upnp: Local IP: 192.168.178.33
(16:48:22) util: Response headers: 'HTTP/1.1 200 OK
DATE: Wed, 11 Mar 2015 15:48:22 GMT
SERVER: FRITZ!Box Fon WLAN 7390 UPnP/1.0 AVM FRITZ!Box Fon WLAN 7390 84.06.20
CONNECTION: keep-alive
CONTENT-LENGTH: 379
CONTENT-TYPE: text/xml; charset="utf-8"
EXT:

'
(16:48:22) util: parsed 379
(16:48:22) upnp: NAT Returned IP: 80.117.236.56
(16:48:22) proxy: Connecting to 149.154.167.51:443.
(16:48:22) proxy: Connected to 149.154.167.51:443.
(16:48:22) prpl-telegram: connect result: 16
(16:48:22) prpl-telegram: outbound rpc connection from dc #2 becomed ready
(16:48:22) proxy: Connecting to 149.154.167.91:443.
(16:48:22) proxy: Connected to 149.154.167.91:443.
(16:48:22) prpl-telegram: connect result: 18
(16:48:22) prpl-telegram: outbound rpc connection from dc #4 becomed ready
(16:48:22) proxy: Connecting to 149.154.175.50:443.
(16:48:22) proxy: Connected to 149.154.175.50:443.
(16:48:22) prpl-telegram: connect result: 15
(16:48:22) prpl-telegram: outbound rpc connection from dc #1 becomed ready
(16:48:22) proxy: Connecting to 174.140.142.6:443.
(16:48:22) proxy: Error connecting to 174.140.142.6:443 (Connessione rifiutata).
(16:48:22) proxy: Connection attempt failed: Connessione rifiutata
(16:48:22) prpl-telegram: connect result: -1
(16:48:22) proxy: Connecting to 149.154.171.5:443.
(16:48:22) proxy: Connected to 149.154.171.5:443.
(16:48:22) prpl-telegram: connect result: 19
(16:48:22) prpl-telegram: outbound rpc connection from dc #5 becomed ready
(16:48:22) prpl-telegram: adjusting CLOCK_MONOTONIC delta to 0,191789
(16:48:22) prpl-telegram: DC3 '' update: 149.154.175.100:443
(16:48:22) prpl-telegram: adjusting CLOCK_MONOTONIC delta to 0,172823
(16:48:23) prpl-telegram: adjusting CLOCK_MONOTONIC delta to -0,640593
(16:48:24) prpl-telegram: adjusting CLOCK_MONOTONIC delta to -0,174372
(16:48:27) util: Writing file prefs.xml to directory /home/fabio/.purple
(16:48:27) util: Writing file /home/fabio/.purple/prefs.xml
(16:48:27) util: Writing file accounts.xml to directory /home/fabio/.purple
(16:48:27) util: Writing file /home/fabio/.purple/accounts.xml
(16:48:27) util: Writing file blist.xml to directory /home/fabio/.purple
(16:48:27) util: Writing file /home/fabio/.purple/blist.xml

**Comment by majn** [comment]
Thanks, that's what I needed.

**Comment by fabastrid** [comment]
I'm happy
Did you see that:
(16:48:22) plugins: /usr/lib/purple-2/libjabber.so is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INIT_PLUGIN() macro?

**Comment by jeroenpraat** [comment]
I have the same thing. I pulled to 0.7a and now it gives similar debug codes. I removed and added my telegram account, but without luck.

**Comment by majn** [comment]
Your log tells me that you don't seem to run the most current version, one of the submodules is not up to date. There is a bug in libtgl which needs a fix or else login won't work. https://github.com/vysheng/tg/issues/440

Update all submodules, or (easier) just clone a new version with git clone --recursive and it should work.

**Comment by jeroenpraat** [comment]
I cut and pasted debug lines with telegram in it:

(17:03:54) plugins: probing /usr/lib/purple-2/telegram-purple.so
(17:03:54) util: Reading file accounts.xml from directory /home/jeroen/.purple
(17:03:54) prpl-telegram: [0mtgprpl_status_types()[0m
(17:03:54) util: Reading file status.xml from directory /home/jeroen/.purple
(17:03:54) connection: Connecting. gc = 0x7fc2faeeaf10
(17:03:54) prpl-telegram: [0mtgprpl_login()[0m
(17:03:54) prpl-telegram: [0mbase configuration path: '/home/jeroen/.telegram-purple/+3164347606'[0m
(17:03:54) prpl-telegram: [0mpublic key '/etc/telegram-purple/server.pub' loaded successfully[0m
(17:03:54) prpl-telegram: [0mDC1 '' update: 149.154.175.50:443[0m
(17:03:54) prpl-telegram: [0mDC2 '' update: 149.154.167.51:443[0m
(17:03:54) prpl-telegram: [0mDC3 '' update: 174.140.142.6:443[0m
(17:03:54) prpl-telegram: [0mDC4 '' update: 149.154.167.91:443[0m
(17:03:54) prpl-telegram: [0mDC5 '' update: 149.154.171.5:443[0m
(17:03:54) util: requesting to fetch a URL
(17:03:54) proxy: Connected to 149.154.167.51:443.
(17:03:54) prpl-telegram: [0mconnect result: 20[0m
(17:03:54) prpl-telegram: [0moutbound rpc connection from dc #2 becomed ready[0m
(17:03:54) proxy: Connecting to 149.154.167.91:443.
(17:03:54) proxy: Connected to 149.154.167.91:443.
(17:03:54) prpl-telegram: [0mconnect result: 22[0m
(17:03:54) prpl-telegram: [0moutbound rpc connection from dc #4 becomed ready[0m
(17:03:54) util: Response headers: 'HTTP/1.1 200 OK

**Comment by majn** [comment]
@jeroenpraat  Same issue in your plugin, you need to update the libtgl submodule to the newest version.

**Comment by fabastrid** [comment]
I'd be so happy if I could do it!
I'm not an expert one.
Should I remove the version I got from repository ppa: nilarimogard / webupd8 and install the one from the zip here?
Then I don't bother you anymore...

**Comment by majn** [comment]
No, the zip releases don't work. You need to fetch this repository with git like described in the README and compile it from source.

**Comment by fabastrid** [comment]
when I try to compile
Compile and install

    ./configure
    make
    sudo make install

the terminal says there's no file nor directory.
What should I do?

**Comment by majn** [comment]
What is the exact output?

**Comment by jeroenpraat** [comment]
Great it works.

@majn How to update in the future? Just a 'git pull' like before or is there another way to avoid these issues?

**Comment by fabastrid** [comment]
./configure
bash: ./configure: File o directory non esistente 

trat means fire or folder not existing

**Comment by jeroenpraat** [comment]
@fabastrid Did you cd in the telegram-purple directory?

**Comment by fabastrid** [comment]
where is it?

**Comment by jeroenpraat** [comment]
The telegram-purple should be a subdirectory of the directory where you did the git clone.

**Comment by majn** [comment]
@jeroenpraat 
git pull will only fetch updates of the pointer to the new submodule commit in the main repository, but not check out  the local files to that commit. To do that you need git submodule update, every time there is an update in one of the submodules and --recursive since the submodule has another submodule.

So basically

   git pull
   git submodule update --recursive

**Comment by fabastrid** [comment]
great, thank so much, it works!
We can close the issue.
Thank you again

**Comment by majn** [comment]
@fabastrid I think I'll leave this open for a while. There are probably more people that are having this issue right now and this way they'll find it faster.

**Comment by ay4** [comment]
Hi, thanks for the great plugin! 

Judging by the logs, I seem to be expecting the same problem on Adium, which is only logical if the default server has, indeed, changed. Is there a way to apply a workaround without actually recompiling the plugin under Mac OS X? The process seems a bit more complicated than on Linux.

**Comment by majn** [comment]
> Is there a way to apply a workaround without actually recompiling the plugin under Mac OS X? The process seems a bit more complicated than on Linux.
@ay4 Yes, I'm aware that its not working properly in the Adium bundle right now. Unfortunately there isn't a way to fix this without recompiling, but I'll drop a new version of the Adium plugin which includes the fix very soon.

**Comment by ay4** [comment]
That's awfully kind of you, cheers!

And thanks once more for relieving us from having to install yet another bulky app!
