### ISSUE TITLE
Does not compile (make: *** No rule to make target 'tgl/scheme.tl', needed by 'auto/scheme.tl'.  Stop.)

### ISSUE THREAD

**Issue by SwooshyCueb** [majn/telegram-purple#62]
When trying to compile from the current code in github, ./configure works fine, but make fails with
`make: *** No rule to make target 'tgl/scheme.tl', needed by 'auto/scheme.tl'.  Stop.`

**Comment by majn** [comment]
Have you cloned the repository with git clone --recursive?

**Comment by SwooshyCueb** [comment]
Huh. I could have sworn I did but checking just now apparently I haven't. Closing the issue.

**Comment by jeroenpraat** [comment]
I also have this problem and I really did a recursive clone.

Actually there is this fatal message in the clone output:

```
fatal: reference is not a tree: 195b2bcccdefd63282654c4d827315a48b677f97
Unable to checkout '195b2bcccdefd63282654c4d827315a48b677f97' in submodule path 'tgl'
```

This is of course the cause of it, but how to fix this?

**Comment by majn** [comment]
Its not your fault, I forgot to set the submodule url back to upstream libtgl. It works now, thanks for reporting.

**Comment by jeroenpraat** [comment]
Thank you for fixing.

**Comment by nitrogl** [comment]
I get the same "No rule to make target `tgl/scheme.tl', needed by `auto/scheme.tl'.  Stop." in version 1.1.0 beta2, with tar.gz package.
