### ISSUE TITLE
Pidgin immediately crashes when my account is in accounts.xml and enabled

### ISSUE THREAD

**Issue by SwooshyCueb** [majn/telegram-purple#63]
Worked fine for a while, but then this started happening. Tried updating to the latest git commit, still does it.
```
pidgin: telegram-base.c:171: read_dc: Assertion `l >= 0 && l < 100' failed.
fish: 'pidgin' terminated by signal SIGABRT (Abort)
```

**Comment by majn** [comment]
Can you give me the whole Pidgin output please? (But make sure that you remove all occurences of your phone number)

**Comment by SwooshyCueb** [comment]
That's all I get without specifying -d on the command line. With -d, I get this: https://paste.weasyldev.com/show/ZQgQkzdHFbbygnNHmgsa/

**Comment by majn** [comment]
Are you sure that you have checked out all submodules to the latest commit? This should ensure that all submodules are on the latest commit:

git submodule update

If you've already used an older version before, you might also want to try removing the ~/.telegram-purple directory (You will loose your secret chats) and try again.

**Comment by SwooshyCueb** [comment]
Removing ~/.telegram-purple seems to have fixed it.
