### ISSUE TITLE
Profile images not shown.

### ISSUE THREAD

**Issue by TheLoko** [majn/telegram-purple#66]
I'm using the AUR telegram-purple package, and since 1 month ago or so, profile images were not updated anymore, and some were missing.
I have checked `~/.purple/telegram-purple/{phone}/downloads/` folder, and missing images were there but they are corrupted: If I try to open them with any image viewer, like Viewinor, it says: "Couldn't recognize the image file format."
I have tried deleting those files and it downloads 1 of them correctly when login, only 1, the first (the one with the lower number).
If I delete that chat, when login again, it will download successfully the next one only, the others will be corrupted.
So it seems that it only will download 1 image and the others will be corrupted.
I have noiticed too that corrupted images are saved on ~/.purple/icons/ too as .icon instead of .jpg

Debugger output:
> (10:37:33) blist: Updating buddy status for xxxxx (Telegram)
> (10:37:33) gtkutils: gdk_pixbuf_loader_write() failed with size=93761: Unrecognized image file format
> (10:37:33) gtkblist: Couldn't load buddy icon on account +xxxxxxxx (prpl-telegram)  > buddyname=xxxxxx  custom_img_data=(nil)
> (10:37:33) prpl-telegram: Already downloaded

If I remove the icons:
> (10:42:04) blist: Updating buddy status for xxxxxxxx (Telegram)
> (10:42:05) util: Writing file /home/julio/.purple/icons/fd733701be3caa63933ed4e2f3cbd1a25c2f4915.icon
> (10:42:05) gtkutils: gdk_pixbuf_loader_write() failed with size=43542: Unrecognized image file format
> (10:42:05) gtkblist: Couldn't load buddy icon on account +xxxxxxx (prpl-telegram)  buddyname=xxxxxx  custom_img_data=(nil)

Steps to reproduce:
1. Delete the downloads folder of your Telegram account
2. Login again and check if all profile photos were downloaded

**Comment by TheLoko** [comment]
This seems to be fixed now

**Comment by BenWiederhake** [comment]
Bump, this can be closed.
