### ISSUE TITLE
Better Sticker Handling

### ISSUE THREAD

**Issue by thepaperpilot** [majn/telegram-purple#67]
Right now, when someone sends me a sticker, it initiates a file request, a fairly annoying dialog for such a common event. I think it would be much better to just display the sticker as an image in the chat. Or even just show the emoticon. But I don't want to have to save each sticker just to know what it was. Especially in an active group chat. /Especially/ since it doesn't even auto-open the image. It becomes a huge hassle to deal with, and I end up denying most requests.

**Comment by majn** [comment]
Bummer, just forgot to handle the __days == 0__ case. Thanks for reporting, its fixed.

https://github.com/majn/telegram-purple/commit/1573309875064660d3a62ad650c8ed1b092b3398

**Comment by majn** [comment]
Yes, you are definitely right.

The main problem with Stickers is that they are send in .webp format, which none of the libpurple clients  can handle natively.

**Comment by omyno** [comment]
This might be an ugly temporary workaround, but couldn't telegram-purple ship the stickers itself (in a format which the clients understand) so they wouldn't need to be downloaded at all? I am aware that users can still send custom stickers by just sending .webp files as documents, but I guess that's a rare usecase.

**Comment by thepaperpilot** [comment]
would it be feasible to check if imagemagick is installed, and convert the file to a png?

**Comment by majn** [comment]
I think the best way to solve this would be to just include googles webp library to decode the images. I'm only worried about older distributions which might now have the library available, or just a very old version of it.

**Comment by kaptoxic** [comment]
+1 for this one

**Comment by majn** [comment]
implemented

**Comment by omyno** [comment]
Thank you so much for implementing this feature, @majn. Unfortunately I still only see an empty message when receiving a sticker with Pidgin 2.10.9 on Ubuntu 15.04. Package libwebp-dev is installed and ./configure says:

    checking for libwebp... enabled
    checking for WebPDecodeRGBA in -lwebp... yes

Is it possible to send stickers as well?

**Comment by thepaperpilot** [comment]
It works for me. I have to say, it's pretty incredible. Transparency and
everything.

**Comment by majn** [comment]
@omyno 

No, there's simply no UI for choosing stickers available in libpurple. If there's a way to do that it would probably be some ugly hack.
