### ISSUE TITLE
Show online buddies in group chats

### ISSUE THREAD

**Issue by thepaperpilot** [majn/telegram-purple#68]
In the buddy list, buddies who don't have the app open have a phone symbol(representing push notifications, I believe) next to them. I like being able to see who is currently in a group chat, and currently keep my Telegram buddy group expanded so I can see who does and doesn't have that symbol. It would be much more useful if there was an icon next to their name in the sidebar. Apart from the owner, there are no ranks, so you could use, say, the voiced symbol for someone who's online.

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
Of course, Pull Requests are still very much welcome!
