### ISSUE TITLE
Not fetching unlimited messages

### ISSUE THREAD

**Issue by thepaperpilot** [majn/telegram-purple#69]
I set the option "Don't fetch messages older than (days)" to 0, since it said that was unlimited.
After doing that, I wouldn't receive any messages (through pidgin, other telegram clients worked) until I reset the option to >0.

(sorry for making 3 issues so quickly, just trying to help)

**Comment by majn** [comment]
Bummer, just forgot to handle the __days == 0__ case. Thanks for reporting, its fixed.

https://github.com/majn/telegram-purple/commit/1573309875064660d3a62ad650c8ed1b092b3398
