### ISSUE TITLE
Sends messages but does not receive.

### ISSUE THREAD

**Issue by kenetik** [majn/telegram-purple#70]
The plugin login and connected with no issues, sends messages to the recipient, shows read notifications and when other user is typing but no messages from the other user are displayed in the pidgin plugin client.

What information can I provide that would help debug the issue?

**Comment by majn** [comment]
The debug output would be useful.

- You can get it by clicking on help -> debug window
- By starting pidgin with -d from the terminal.
- In Adium by pressing alt while starting the Application.

**Comment by thepaperpilot** [comment]
That sounds similar to the symptoms I described in issue #69. I don't
suppose it could be the same problem?

**Comment by majn** [comment]
@kenetik have you selected 0 days as message retrieval threshold?
