### ISSUE TITLE
Starting a OTR private conversation with another Telegram user (not "start secure chat") crashes pidgin on the partner side

### ISSUE THREAD

**Issue by nepda** [majn/telegram-purple#71]
I've pidgin with OTR plugin installed and a Telegram account. When I ("A") start a private conversation with another Pidgin-OTR-Telegram user "B" the pidgin client of "B" crashes with the following message:

    (14:57:50) blist: Updating buddy status for 7*****1 (Telegram)
    (14:57:50) prpl-telegram: 8****7: when=1*****6
    (14:57:50) prpl-telegram: mobile
    (14:57:50) prpl-telegram: tgprpl_send_im()
    (14:57:50) prpl-telegram: send all pending ack
    (14:57:50) prpl-telegram: tgl_do_mark_read (9****3)
    (14:57:50) prpl-telegram: Unread 90 ints. Len = 12
    pidgin: tgl/binlog.c:1589: add_log_event: Assertion `rptr == wptr' failed.
    dns[30157]: Oops, father has gone, wait for me, wait...!
    [1]    30155 abort (core dumped)  pidgin -d

The plain message looks like this on the phone

    ?OTRv23?
    <b>+4917***</b> has requested an <a href="https://otr.cypherpunks.ca/">Off-the-Record private conversation</a>.  However, you do not have a plugin to support that.
    See <a href="https://otr.cypherpunks.ca/">https://otr.cypherpunks.ca/</a> for more information.

**Comment by chrischaan** [comment]
+1

**Comment by nepda** [comment]
You can go to https://web.telegram.org/ (may be also via phone) and delete the OTR-request message. Then restart pidgin.

**Comment by majn** [comment]
Could you try it? Worked for me. https://github.com/majn/telegram-purple/tree/fix-otr

**Comment by nepda** [comment]
Sorry for the late response. W've tested it and it works perfectly. We can now create OTR secured chat sessions on top of telegram and on top of secure telegram chats :+1:
Please merge this into master. Thank you for this work!

**Comment by majn** [comment]
changes in master now
