### ISSUE TITLE
Since updating to v1.0.0-beta each login causes SMS verification with Empathy

### ISSUE THREAD

**Issue by lurtz** [majn/telegram-purple#72]
Hi,

I like to use Empathy simply because it logs off all my connections automatically, when I close the lid of my laptop. Empathy uses telepathy-haze [0] to access protocols made available by libpurple.

Recently I updated to v1.0.0-beta and since then the authentication data does not seem to be saved and doing SMS verification over and over again is quite annoying.

My guess is that moving the authentication data from ~/.telegram-purple to ~/.purple/telegram-purple caused this.

Greetings

[0] https://developer.pidgin.im/wiki/TelepathyHaze

**Comment by majn** [comment]
Yes, that is probably the reason. 

I just looked briefly into the telepathy-haze source and it appears that they set the user configuration directory to a new temporary directory on each startup.


    user_dir = g_strconcat (g_get_tmp_dir (), G_DIR_SEPARATOR_S,
                                  "haze-XXXXXX", NULL);
    if (!mkdtemp (user_dir)) {
        g_error ("Couldn't make temporary conf directory: %s",
                 strerror (errno));
    }
    purple_util_set_user_dir (user_dir);

**Comment by lurtz** [comment]
I wrote a bug report to the telepathy guys [0]. Maybe they do something about it.

[0] https://bugs.freedesktop.org/show_bug.cgi?id=89984

**Comment by majn** [comment]
I don't think that this is a bug in telepathy-haze. After all, I'm bypassing the regular libpurple mechanism for storing protocol settings, which telepathy-haze supports properly.

**Comment by lurtz** [comment]
Do you have plans to use the libpurple mechanism or is it not possible for telegram?

**Comment by majn** [comment]
Well, I probably could abuse the protocol settings for storing base64 strings of the binary state file format (or something like that), but I'll most likely just try to find some workaround for telepathy-haze, way less effort that way.

**Comment by lurtz** [comment]
Great to hear. I will close the bug at the bugtracker of telepathy then.

**Comment by lurtz** [comment]
Empathy seems to store the authentication data again when using the beta2 branch

**Comment by majn** [comment]
yes, it should be fixed now in current master.
