### ISSUE TITLE
Group Chat participants are listed by phone #, not name.

### ISSUE THREAD

**Issue by CodeMonk** [majn/telegram-purple#73]

**Comment by majn** [comment]
Are you using Adium? In that case I'm aware, for some reason Adium is using the user name instead of the user alias for displaying group chat participants. I've not yet found a way to work around this. 

Pidgin will display group chats participant names correctly.

**Comment by CodeMonk** [comment]
I am using Adium.  Guess that explains it. :(

**Comment by majn** [comment]
fixed in v1.2.1
