### ISSUE TITLE
adding account won't lead to Telegram SMS with number-code

### ISSUE THREAD

**Issue by Zanzibari** [majn/telegram-purple#75]
Telegram-purple: adding account won't lead to Telegram SMS with number-code. Useless so far.

**Comment by majn** [comment]
Which version are you using?

**Comment by Zanzibari** [comment]
Version: 0.7.0-1~webupd8~trusty0
I use the ubuntu repository provided by webupd8

**Comment by majn** [comment]
This version doesn't work anymore, due to an old bug and some current changes in the Telegram network that triggered this bug. The only way around is to compile the new version.

**Comment by Zanzibari** [comment]
That's pretty bad, as I think I am not the only one, who has no time to re-learn how to compile (did it years ago, but forgot how meanwhile).  
After almost 10 years of using Linux I may say, that unfortunately many developers seem not very interested in making their product user-friendly enough reach wider circulation.

**Comment by chpii** [comment]
@Zanzibari It's written at front page. You need to be able to read and copy-paste commands, at very least.

**Comment by majn** [comment]
@Zanzibari I'll provide official RPM and DEB packages with the next beta release now that the whole project seems stable enough for that.

**Comment by Zanzibari** [comment]
@majn: that's good news, please notify me when ready. I'll give beta testing-feedback in case of anything.
Cheers!

**Comment by EionRobb** [comment]
Except that you shouldn't until you resolve the gpl issue
