### ISSUE TITLE
Lost messages in group chat when Pidgin disconnects.

### ISSUE THREAD

**Issue by Najoj** [majn/telegram-purple#76]
Messages sent when chat is open but not connected are not recieved when connection is again established.

1. Open a Telegram group chat i Pidgin
2. Log out of Telegram in Pidgin or disconnect Pidgin from Internet
3. Get or send a message using another Telegram client.
4. Re-connect Telegram in Pidgin
5. Message(s) from step 3 are no where to be found in Pidgin, even if group chat is re-opened.

If chat window is closed before reconnecting (step 4), messages are recieved.

**Comment by majn** [comment]
fixed in current master
