### ISSUE TITLE
Send oversized pictures as documents

### ISSUE THREAD

**Issue by omyno** [majn/telegram-purple#79]
When sending a specific image with big dimensions, Pidgin crashes/freezes. When trying to send the image as a file (as it has been solved in [webogram](https://github.com/zhukov/webogram/issues/726)), the transfer hangs at 92%. Sending the image via Telegram/Android and tdesktop works fine. The dimensions of the image are 7000x3156. I can see "PHOTO_INVALID_DIMENSIONS" in the debugging output. Maybe the other mobile and desktop clients scale the image down before sending them?

Here is some more gdb output:

Program received signal SIGSEGV, Segmentation fault.
tgp_msg_send_done (TLS=0x555556886ca0, callback_extra=<optimized out>, success=<optimized out>, M=0x0) at tgp-msg.c:152
152     tgp_msg_err_out (TLS, err, M->to_id);
(gdb) backtrace full
#0  tgp_msg_send_done (TLS=0x555556886ca0, callback_extra=<optimized out>, success=<optimized out>, M=0x0) at tgp-msg.c:152

```
    err = 0x7fffcb0ee168 "Sending message failed. Maybe you don't have the permission to send to this peer, or the peer does no longer exist."
    callback_extra = <optimized out>
    M = 0x0
    TLS = 0x555556886ca0
```
#1  0x00007fffcaf84189 in send_msgs_on_error (TLS=0x555556886ca0, q=0x555556c10cf0, error_code=<optimized out>, error_len=<optimized out>, error=<optimized out>) at tgl/queries.c:1844

```
    E = 0x555556a13cd0
```
#2  0x00007fffcaf8ae13 in tglq_query_error (TLS=0x555556886ca0, id=6157296829555197952) at tgl/queries.c:374

```
    res = 0
    error_handled = <optimized out>
    __PRETTY_FUNCTION__ = "tglq_query_error"
    q = 0x555556c10cf0
```
#3  0x00007fffcaf7c2f3 in work_rpc_result (c=0x5555568c2d30, msg_id=<optimized out>, TLS=0x555556886ca0) at tgl/mtproto-client.c:857

```
    id = 140736600131296
```
#4  rpc_execute_answer (TLS=TLS@entry=0x555556886ca0, c=c@entry=0x5555568c2d30, msg_id=<optimized out>) at tgl/mtproto-client.c:955

No locals.
#5  0x00007fffcaf7cec2 in process_rpc_message (enc=0x7fffcc363fc0 <Response.20117>, len=<optimized out>, c=0x5555568c2d30, TLS=0x555556886ca0) at tgl/mtproto-client.c:1131

```
    MINSZ = 56
    S = 0x555556887600
    this_server_time = <optimized out>
    UNENCSZ = 24
    DC = <optimized out>
    l = <optimized out>
    sha1_buffer = "\250ybA\321\354\213\\\214\301\242\064\275\263\233\061\027\245\331", <incomplete sequence \326>
```
#6  rpc_execute (TLS=0x555556886ca0, c=0x5555568c2d30, op=<optimized out>, len=<optimized out>) at tgl/mtproto-client.c:1186

```
    DC = <optimized out>
    Response_len = <optimized out>
    Response = "\226\341N\333\337/\376p\321\354\213\\\214\301\242\064\275\263\233\061\027\245\331\326\377\265C\315@\250\003\024\177\204\006Ԑߖ1\001\350\250\022\331\034sU9\001\000\000\060\000\000\000\001m\\\363\000\310F\376\327\034sU\031\312D!\220\001\000\000\030PHOTO_INVALID_DIMENSIONS\000\000\000\032\000\000\000\024\000\000\000Y\264\326b\025ĵ\034\001\000\000\000\000(S\377\320\034sU[mc\020\000\000\000\000\016\061\064\071.154.167.51\000\273\001\000\000<\244\302.\003\000\000\000\000\000\000\000\017\061\064\071.154.175.100\273\001\000\000<\244\302.\004\000\000\000\000\000\000\000"...
    __PRETTY_FUNCTION__ = "rpc_execute"
    o = <optimized out>
    __func__ = "rpc_execute"
```
#7  0x00007fffcaf654c0 in try_rpc_read (c=0x5555568c2d30) at tgp-net.c:442

```
    len = 104
    t = 26
    op = -615587434
    TLS = 0x555556886ca0
```
#8  try_read (c=0x5555568c2d30) at tgp-net.c:488

```
    TLS = <optimized out>
    x = <optimized out>
```
#9  conn_try_read (arg=0x5555568c2d30, source=<optimized out>, cond=<optimized out>) at tgp-net.c:237

```
    c = 0x5555568c2d30
    TLS = <optimized out>
```
#10 0x00005555555c913e in ?? ()

No symbol table info available.
#11 0x00007ffff537ab4d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0

No symbol table info available.
#12 0x00007ffff537af20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0

No symbol table info available.
#13 0x00007ffff537b242 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0

No symbol table info available.
#14 0x00007ffff6623857 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0

No symbol table info available.
#15 0x000055555558f2c9 in main ()

No symbol table info available.

Thread 1 (Thread 0x7ffff7fa6a00 (LWP 5790)):
#0  tgp_msg_send_done (TLS=0x555556886ca0, callback_extra=<optimized out>, success=<optimized out>, M=0x0) at tgp-msg.c:152
#1  0x00007fffcaf84189 in send_msgs_on_error (TLS=0x555556886ca0, q=0x555556c10cf0, error_code=<optimized out>, error_len=<optimized out>, error=<optimized out>) at tgl/queries.c:1844
#2  0x00007fffcaf8ae13 in tglq_query_error (TLS=0x555556886ca0, id=6157296829555197952) at tgl/queries.c:374
#3  0x00007fffcaf7c2f3 in work_rpc_result (c=0x5555568c2d30, msg_id=<optimized out>, TLS=0x555556886ca0) at tgl/mtproto-client.c:857
#4  rpc_execute_answer (TLS=TLS@entry=0x555556886ca0, c=c@entry=0x5555568c2d30, msg_id=<optimized out>) at tgl/mtproto-client.c:955
#5  0x00007fffcaf7cec2 in process_rpc_message (enc=0x7fffcc363fc0 <Response.20117>, len=<optimized out>, c=0x5555568c2d30, TLS=0x555556886ca0) at tgl/mtproto-client.c:1131
#6  rpc_execute (TLS=0x555556886ca0, c=0x5555568c2d30, op=<optimized out>, len=<optimized out>) at tgl/mtproto-client.c:1186
#7  0x00007fffcaf654c0 in try_rpc_read (c=0x5555568c2d30) at tgp-net.c:442
#8  try_read (c=0x5555568c2d30) at tgp-net.c:488
#9  conn_try_read (arg=0x5555568c2d30, source=<optimized out>, cond=<optimized out>) at tgp-net.c:237
#10 0x00005555555c913e in ?? ()
#11 0x00007ffff537ab4d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff537af20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff537b242 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff6623857 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#15 0x000055555558f2c9 in main ()

**Comment by majn** [comment]
FIY: The crashing is now fixed, the downscaling isn't.

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple), which might already have this enhancement. For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
Of course, Pull Requests are still very much welcome!
