### ISSUE TITLE
Empathy support?

### ISSUE THREAD

**Issue by bjesus** [majn/telegram-purple#8]
Hey,
I can't get telegram-purple to work with GNOME Empathy. It shows okay as an option when adding a new account, but after inserting my phone number and clicking "Add", nothing happens. the window stays, and all I can do is manually close it.

Any idea why? Is anyone else experiencing this? Is this an Empathy bug?

Thanks a lot for your work.

**Comment by tfausak** [comment]
I could not log in to my account. No chat popped up and I never got a code from Telegram. I tried both Empathy (3.8.6) and Online Accounts (3.12.4-1), with telegram-purple 0.7.0 on Ubuntu 14.10.

**Comment by nemobis** [comment]
I got no popup in Fedora 25 (empathy-3.12.12-2.fc25.x86_64, purple-telegram-1.3.0-1.fc25.x86_64), only a "chat" with the Telegram service. In the end I was acknowledged as authenticated, but that might be because I logged in in Pidgin.
