### ISSUE TITLE
Лишние контакты

### ISSUE THREAD

**Issue by SeibelStan** [majn/telegram-purple#80]
Периодически в списке (только в в пиджине) появляются котакты на несколькознчные "не сотовые" номера, нередко после удаления появляется снова. Таких, если не удалять, может накопиться несколько штук. Так же, некоторые контакты зовутся Web Page - они плодятся ещё быстрее: за пару-тройку дней их уже четыре.

**Comment by 0nse** [comment]
Привет @SeibelStan,
could you please translate your issue into English? Are we talking about chat rooms (group chats) or contacts? Did some of the unwanted contacts disappear after some time? Also, please compare if your issue is covered by #81 and thus connected with Telegram stickers.

**Comment by majn** [comment]
According to google translate this seems like duplicate of https://github.com/majn/telegram-purple/issues/81 ;)
