### ISSUE TITLE
Receiving a sticker adds the sticker author

### ISSUE THREAD

**Issue by toadfan321** [majn/telegram-purple#81]
I'm using telegram-purple through bitlbee which I am connected to using weechat, which is all running on debian wheezy. I noticed over a few days that my contact list started becoming populated with people I did not know, and were not in any contact list, after further investigation I found out they were authors of stickerpacks that some of my friends had sent stickers from, which i assume afterward caused them to be added to my contacts. I'm not really sure how this would happen since from what I can tell nothing about the author or anything is sent with the sticker, but that's what's happened. I haven't really done much debugging and whatnot with this, just noticed that it was going on so i'm up for trying anything to help figure out what's going on.

**Comment by majn** [comment]
https://github.com/majn/telegram-purple/issues/99 Duplicate and also fixed.
