### ISSUE TITLE
phone code is always invalid

### ISSUE THREAD

**Issue by fauno** [majn/telegram-purple#82]
hi, i have telegram on my cellphone already but it's unclear to me if i can use it both on the phone and on pidgin?  anyway i've tried to use your plugin and the verification code is always rejected.

i saw in another issue that the telegram library may be outdated but i tried with a fresh recursive clone too.

here's a snip of the log regarding telegram-purple:

```
(21:22:04) plugins: probing /usr/lib/purple-2/telegram-purple.so
(21:22:04) prpl-telegram: tgprpl_status_types()
(21:23:32) prpl-telegram: tgprpl_login()
(21:23:32) prpl-telegram: base configuration path: 'XXXXXXXXXXXXXXXXX'
(21:23:32) prpl-telegram: public key '/etc/telegram-purple/server.pub' loaded successfully
(21:23:32) prpl-telegram: DC1 '' update: 149.154.175.50:443
(21:23:32) prpl-telegram: DC2 '' update: 149.154.167.51:443
(21:23:32) prpl-telegram: DC3 '' update: 149.154.175.100:443
(21:23:32) prpl-telegram: DC4 '' update: 149.154.167.91:443
(21:23:32) prpl-telegram: DC5 '' update: 149.154.171.5:443
(21:23:32) prpl-telegram: connect result: 15
(21:23:32) prpl-telegram: outbound rpc connection from dc #3 becomed ready
(21:23:32) prpl-telegram: connect result: 9
(21:23:32) prpl-telegram: outbound rpc connection from dc #1 becomed ready
(21:23:32) prpl-telegram: connect result: 14
(21:23:32) prpl-telegram: outbound rpc connection from dc #2 becomed ready
(21:23:32) prpl-telegram: connect result: 16
(21:23:32) prpl-telegram: outbound rpc connection from dc #4 becomed ready
(21:23:33) prpl-telegram: connect result: 17
(21:23:33) prpl-telegram: outbound rpc connection from dc #5 becomed ready
(21:23:34) prpl-telegram: adjusting CLOCK_MONOTONIC delta to 0,119667
(21:23:34) prpl-telegram: adjusting CLOCK_MONOTONIC delta to -0,237330
(21:23:35) prpl-telegram: adjusting CLOCK_MONOTONIC delta to 0,350222
(21:23:35) prpl-telegram: adjusting CLOCK_MONOTONIC delta to 0,020279
(21:23:36) prpl-telegram: adjusting CLOCK_MONOTONIC delta to -0,124444
(21:23:36) prpl-telegram: error for query #6162988654618268724: #303 PHONE_MIGRATE_1 (HANDLED)
(21:23:36) prpl-telegram: Alarm query 6162988654618268724
(21:23:36) prpl-telegram: Client is not registered, registering...
(21:23:36) prpl-telegram: tgprpl_blist_node_menu()
(21:23:36) prpl-telegram: tgprpl_blist_node_menu()
(21:24:09) prpl-telegram: tgprpl_send_typing()
(21:24:14) prpl-telegram: tgprpl_send_im()
(21:24:14) prpl-telegram: tgprpl_send_typing()
(21:24:14) prpl-telegram: error for query #6162988818150717160: #400 PHONE_CODE_INVALID
(21:24:14) prpl-telegram: Bad code...
(21:24:14) prpl-telegram: Client is not registered, registering...
(21:24:24) prpl-telegram: tgprpl_send_typing()
(21:24:27) prpl-telegram: tgprpl_close()
(21:24:27) plugins: Unloading plugin Telegram
```

**Comment by majn** [comment]
It should definitely be possible to run Telegram on Pidgin and on the smartphone, the protocol was made for that purpose.

Could you try to log in with the CLI client https://github.com/vysheng/tg and see if that works? It uses the same library, if that fails its probably a bug in libtg.

**Comment by fauno** [comment]
it actually worked on the first try, it sent me the code, i entered it and immediately received a notification telling me someone started a session from my ip

**Comment by fauno** [comment]
i solved it, i have pidgin-otr enabled and it was sending the code with the otr tag included.  i believe it's a whitespace added to the message, but i can't recall it's at the start or the end of it.

i think there's two ways of solving this: a) tell people to disable otr momentarily, or b) trim the messages sent to the registration contact :)

**Comment by majn** [comment]
Its weird that OTR would have any influence on that, did you use the popup prompt for entering the message, or did it use a regular "conversation"? The latter one is the fallback mode, that is only useful for clients like Empathy that don't support those prompts.

**Comment by fauno** [comment]
it opened a regular conversation asking me the code.  i had sms fallback enabled because it didn't ask me anything until i restarted pidgin. i'm on pidgin 2.10.11.

**Comment by majn** [comment]
Added some string sanitation for the fallback chat, OTR doesn't interfere with the fallback chat anymore.
