### ISSUE TITLE
Openstreetmaps fine or switch to Googlemaps?

### ISSUE THREAD

**Issue by majn** [majn/telegram-purple#87]
Is there anyone having issues with the map quality in his country, compared to Google Maps?

I've chosen OSM since according to my experience the maps are usually more detailed, but I've heard that there are some countries with very poorly mapped OSM maps.

How is the OSM map quality in your country? If its really bad somewhere I'll think about replacing it or at least providing a setting to change it.

**Comment by gnurbs** [comment]
here in switzerland, OSM is, in most parts, excellent. However a friend of mine came across a small village, which apparently did not exist at all in OSM.

Appart from map quality OSM is, obviously, a very open project, whereas gmaps probably uses their usage to contribute to googles ad business. For personal use that's obviously your choice, for projects many users of opensource software will favor OSM.

I have not yet seen maps in telegram-purple, did I miss something, or is this question unrelated to the project/for future features?

**Comment by majn** [comment]
@gnurbs If you receive a geo location you will get an OSM link to the position instead.

**Comment by jeroenpraat** [comment]
Absolutely OSM. Using Google Maps is out-of-order, cause that gives Google to option to track Telegram users. I also don't understand why the Android version uses Google Maps. That should change to OSM too, but that's not the question here.
