### ISSUE TITLE
telegram-purple not connecting succesfully

### ISSUE THREAD

**Issue by gnurbs** [majn/telegram-purple#88]
telegram-purple does not connect, pidgin -d shows these messages: (additional alarm querys were omitted)

```
(09:54:50) prpl-telegram: Alarm query 6170526124635186176
(09:54:56) prpl-telegram: Alarm query 6170526124635186176
(09:54:56) prpl-telegram: connect result: -1
(09:54:56) prpl-telegram: Connection not possible, either your network or a Telegram data center is down, or the Telegram network configuratio has changed.
```

**Comment by majn** [comment]
Might be related to the DDOS that seems to be going on  https://mobile.twitter.com/telegram/status/619837611419521024

**Comment by jeroenpraat** [comment]
I have the same from Europe. After a few tries with intervals it works. No problems using the Android app.

**Comment by shrewmus** [comment]
jeroenpraat + same from Europe

**Comment by SwooshyCueb** [comment]
They're being hit pretty hard right now. I've heard whispers on Twitter that this may be LINE's doing, but I don't have anything to back that up.

**Comment by majn** [comment]
The problem is probably amplified by the fact that it won't connect if one of the data centers isn't reachable (cause this is what tg and tgl does too). 

Libtgl already tries to patch this upstream: https://github.com/vysheng/tgl/commit/7bfaae149a08d1e205e5188d548c3d54e5a1ce64

**Comment by majn** [comment]
Pushed a hotfix, if this issue still occurs: https://github.com/majn/telegram-purple/commit/5a06970c23045dd5fa969ae23b867c8c6fe8ac56

**Comment by gnurbs** [comment]
awesome, seems to work great
