### ISSUE TITLE
Can't set username via pidgin?

### ISSUE THREAD

**Issue by BenWiederhake** [majn/telegram-purple#89]
Either I didn't find the button, or this is a missing feature: Setting the @username.

Workaround: Open Telegram Web (or any other client), log in, set username, log out.

**Comment by majn** [comment]
Its not possible, issues like that are very low priority for me, since its a one-time setting you can easily just do from official apps, and they don't really translate well into the pidgin interface.

**Comment by EionRobb** [comment]
@majn things like that normally end up in the Accounts menu in Pidgin, eg Accounts->{GTalk account}->Set User Info...

**Comment by BenWiederhake** [comment]
So it *does* translate well :P  
 I'll try and see whether I can make a dent at it.

**Comment by majn** [comment]
Well I'll be damned, guess then I'll have to implement it after all :D

**Comment by ghsrcgh** [comment]
It will be very good if priority for that will be upped.

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple). For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
Of course, Pull Requests are still very much welcome!
