### ISSUE TITLE
it doesn't reconnect when lost connect to server

### ISSUE THREAD

**Issue by shouya** [majn/telegram-purple#9]
Environment: Gentoo Linux, x86_64, Pidgin 2.10.10 (libpurple 2.10.10), the latest telegram-purple plugin. (this issue should be environment independent)

When telegram-purple is used under unstable network condition, as the connect temporarily down, the account will be *disabled*. While for other protocols, it simply shows as the connection does no longer work and will try to reconnect a few seconds later.

This is what it shows when telegram-purple loses connection.
![telegram](https://cloud.githubusercontent.com/assets/526598/4913583/ce946362-64b4-11e4-8395-6c473b3614be.png)

Pressing the re-enable button could actually take it back correctly. However, what I'm expecting telegram-purple to do is to automatically reconnect rather than disable the account.

I hope it works like gtalk:
![gtalk](https://cloud.githubusercontent.com/assets/526598/4913607/5a1012c4-64b5-11e4-8104-41fdbd5165f6.png)

Thank you ;-)

**Comment by majn** [comment]
This should work now.

**Comment by shouya** [comment]
Thank you. I'll check on it later.
