### ISSUE TITLE
Timer in secret chats does not work

### ISSUE THREAD

**Issue by heitorPB** [majn/telegram-purple#91]
Is it possible to make Telegram Timer in Secret Chats work as espected?

Messages are not deleted in Pidgin. Sent messages to a contact using Telegram in smartphone are not deleted on device, only the messages he sent are deleted for him, but not on Pidgin.

I am using pidgin 2.10.11-2, libpurple 2.10.11-2, telegram-purple 1.1.0beta2-2.

**Comment by majn** [comment]
Deleting message history in a libpurple plugin isn't possible (at least there's no way I know of).

**Comment by EionRobb** [comment]
Indeed, history is immutable.  The best you could do would be to write a system message to the conversation to say that the user has deleted this message.

**Comment by heitorPB** [comment]
Is it possible to 'refresh' the window? If we close and open it again, the text is lost. Is there a way to just 'refresh'? I have no idea if this is a secure way to do it.

**Comment by majn** [comment]
The message will still show up in the log, apart from all the other reasons why this wouldn't be a good idea ;)
