### ISSUE TITLE
Sound/Voice messages don't work

### ISSUE THREAD

**Issue by BenWiederhake** [majn/telegram-purple#92]
I just received a voice message via Telegram (using pidgin), and found that it doesn't work. Pidgin thinks there's a file to download (second screenshot), and offers me to download it (no screenshot). However, the download never happens, even though the file is very small (third screenshot).

Here's how it looks like on the web interface of Telegram ( https://web.telegram.org/#/login ) :
![sound1](https://cloud.githubusercontent.com/assets/2690845/8890925/26df0ff4-3313-11e5-881b-07c3f59f3e3a.png)
Within the chat:
![sound2](https://cloud.githubusercontent.com/assets/2690845/8890926/297b62bc-3313-11e5-9c59-8a4278f7d855.png)
In the file download overview window:
![sound3](https://cloud.githubusercontent.com/assets/2690845/8890924/20e5165c-3313-11e5-9635-512e59d8bf51.png)

**Comment by majn** [comment]
Should be fixed.
