### ISSUE TITLE
Users in a group are listed every time a message is received (using Finch)

### ISSUE THREAD

**Issue by Feirlane** [majn/telegram-purple#93]
Every time a new message arrives in a group chat the full user list is printed before the message, like so:
<pre>
(08:50:25) List of 1 user:
[ User1 ]
(08:50:25) List of 1 user:
[ User2 ]
(08:50:25) List of 1 user:
[ User3 ]
(08:50:25) User1: Hello World!
</pre>

On a group with lots of people, it's very difficult to follow a conversation with that list between every message. I think this didn't happen with earlier versions of the library, but I'm not sure when it started.

Cheers!

**Comment by majn** [comment]
Probably a few log messages that slip through, I'll look at it.

**Comment by RodrigoTjader** [comment]
I'm also seeing this on bitlbee-purple, it seems to be caused by commit 8c859ad82575381a5176c0af24b35ad25beb225d.

**Comment by majn** [comment]
fixed in v1.2.1
