### ISSUE TITLE
Feature request: disable notifications about voice messages in separate windows

### ISSUE THREAD

**Issue by Pastafarianist** [majn/telegram-purple#95]
When joining an active group chat whose users use voice messages, the plugin starts displaying notifications about all such messages, one window per message. If there are a lot of unread messages, this can get very nasty. Under KDE, at least,  about 150 windows are created before the plugin crashes.

If possible, please add an option to disable such notifications.

**Comment by majn** [comment]
A possible solution would be to just auto-download audio and video messages to avoid the regular file transfer handling (up to a certain size, maybe even configurable) and just print a simple file:/// link to the file path in those cases.

**Comment by BenWiederhake** [comment]
Ideally, all types of messages are then "played inline". In the case of an image, tht's obvious: the user never wants to start a separate image viewing program just to see the image.

Is there a "portable-ish" way to do something similar with (in order of decreasing importance) gif, webm, audio, video?

For reference (when purple3 and HTML5 arrive), web.telegram.org has a nice interface for playing audio messages.

**Comment by majn** [comment]
I dont think that its possible for videos, music and gifs.

- gifs used to work, but in a recent update telegram started to convert them to some video format (webm I believe) to "optimize" their size, so they will not work anymore unless we convert them back with ffmpeg.

- audios and videos never worked to begin with.

Pictures and regular gifs are already being displayed inline.

**Comment by majn** [comment]
On dev-1.4.0 have implemented an option to just auto-load or discard all file transfers. Additionally auto-load now works with all file types, not only pictures.
