### ISSUE TITLE
Fallback for inputs in not working with spectrum

### ISSUE THREAD

**Issue by NeoBelerophon** [majn/telegram-purple#96]
Hi,
I use telegram-purple with spectrum2. When I sign up for telegram I receive a SMS with the code but there is no request in the client chat window. The prompt should be forwarded to chat window like the message: "The only message I get is "Phone number not registered, please register you phone on a different client."

In log file I found:
` WARN  backend: Unhandled request input. primary=Enter Telegram Code`

Should telegram-base.c:475 handle this?

**Comment by majn** [comment]
Tried turning on fallback sms authentication manually?

**Comment by NeoBelerophon** [comment]
When you user Spectrum2 you're not able to use the pidgin setting dialogues because it's tunnelled through xmpp protocol.

**Comment by Manu311** [comment]
You can change settings, you just have to know the name and the value of it.
So assuming the name of the setting is compat-verification, you should be able to add a line like:
compat-verification=true
Under the [purple] section (which you may have to create) in your spectrum config file.
I've only used the gateway mode of Spectrum2 but this adds the option to the config file correctly and should work (I didn't create my account with telegram-purple thought).

**Comment by majn** [comment]
This seems to work if provided with the correct settings, so I'm marking it as wontfix. If libpurple clients don't implement all required functions there is little I can do about it.

**Comment by dturkin** [comment]
Hi,
I've added "compat-verification" to spectrum's transport configuration but that doesn't help. Every time I try to login to telegram account I receive verification code. Are there any other ideas how to pass this verification?
