### ISSUE TITLE
FTBFS of 20150525 version on s390

### ISSUE THREAD

**Issue by mcepl** [majn/telegram-purple#98]
I understand that this is probably not the highest priority bug, but just to let you know that the build crashes on s390 https://gist.github.com/mcepl/5dc42e3d7d8ac9cb420e

**Comment by BenWiederhake** [comment]
Are you still experiencing this bug? Could you please try this for me? (This adds some debug info and uses the newest version.)

    git clone --recursive --branch tmp/debug-tgp-98 git@github.com:BenWiederhake/tgl.git
    ./configure
    make

Or whatever is needed to build/crosscompile. In case you prefer chat, see README.md for the chat room invite link.

**Comment by mcepl** [comment]
Still not good https://gist.github.com/mcepl/bd8585ca30cbfda6adff

**Comment by BenWiederhake** [comment]
I removed the "verbose" requirement, so now it *always* generates the debug output I desired.

Please note that I don't have a s390 environment at hand, and I gave up cross compilation after trying for an hour. So sorry that I have to ask you to run it, just in order to get some debug info.

**Comment by BenWiederhake** [comment]
I forgot to push. Sorry. The last comment was about tgl/c1c80a1e13e2aaa362ebff90c8949a84f590d1e2 , which I only just now published.

**Comment by mcepl** [comment]
That's perfectly OK. Nobody sane has s390 environment (hint: I work for Red Hat ;)).

**Comment by BenWiederhake** [comment]
I noticed, and already wondered why you're not using the `rpm/*` files in telegram-purple :P

And just to repeat myself: Running `git clone --recursive --branch tmp/debug-tgp-98 git@github.com:BenWiederhake/tgl.git && cd tgl && ./configure && make` is probably a lot faster than trying to get it to work with buildd.

**Comment by mcepl** [comment]
https://gist.github.com/mcepl/7ae076880355a83bd7dc
first I don't have SSH access to your github account (perhaps, you prefer it that way), second ... well, see for yourself.

**Comment by BenWiederhake** [comment]
Strange, I firmly believed that it allows to pull through a git:// URL.

Since this is a bug in tgl, I'd like to keep it at [the upstream tgl bugtracker](https://github.com/vysheng/tgl/issues/58).

But don't worry, I'm still very interested in getting this fixed: s390{,x} are architectures with experimental support on Debian, and I'm interested in getting telegram-purple with support for all architectures into Debian. All hail transitivity.
