### ISSUE TITLE
Random users shows up in buddy list

### ISSUE THREAD

**Issue by tobiasa1** [majn/telegram-purple#99]
Hi,

Lately I have seen random users showing up in my buddy list in Pidgin that I have no connection with. I also get a loop of notices like "WebPage #XX is online, #29 is online, Mr X is online etc.", none of them in my contact list.

I do not have this problem with Telegram Desktop or the Android client.

**Comment by vanitasvitae** [comment]
I can confirm this. I assume it has to do with stickers maybe?

**Comment by 0nse** [comment]
A friend of mine and I can also confirm this. Not only do they appear randomly but disappear with no apparent reason as well. Afair, they all had a Russian name (not necessarily in cyrillic) in common and had a German phone number associated with them. This, however, might just be a coincidence.

**Comment by majn** [comment]
I've improved the buddy list handling in the current master, unknown users shouldn't be added anymore. Those that already exist need to be removed manually.

**Comment by vanitasvitae** [comment]
I think the Problem reoccured. I just reinstalled my whole system and now there are many new unknown people in my list.

**Comment by majn** [comment]
This shouldn't happen anymore, I only add buddies from the conversation list. Are you sure you are using the newest version and are you sure that those contacts aren't just still in your buddy list from previous versions?

**Comment by vanitasvitae** [comment]
Im pretty sure I use the latest version (I build it from source just 3 days ago). But maybe you are right, I just copied the .telegram-purple and .purple folder over from my backup. Which folders do I have to delete, to get rid of older data?

**Comment by majn** [comment]
The buddies are stored in .purple/blist.xml, but just delete them from your buddy list in pidgin ainstead of deleting files so you don't delete unrelated buddies.

**Comment by vanitasvitae** [comment]
Okay thank you :)
